import { ENVIRONMENTAL_PROP_REGISTRY, type EnvironmentalPropCategory } from '../environmentalProps.js';

export const DTD_D3_VALIDATOR_VERSION = 'catacombs.dtd_d3.asset_validator.v1';
export const AUTHORED_ASSET_ROOTS = ['src/dungeon/assets/catacombs', 'test/fixtures/assets/catacombs'] as const;
export type AuthoredAssetRuntimeStatus = 'APPROVED_AUTHORED'|'PRESENT_UNVALIDATED'|'REJECTED'|'MISSING'|'PROCEDURAL_ONLY';
export type AcceptanceStatus = 'ACCEPTED'|'ACCEPTED_WITH_RECORDED_EXCEPTION'|'PENDING_VISUAL_REVIEW'|'REJECTED'|'MISSING';
export type LoaderState = 'UNREQUESTED'|'LOADING'|'READY'|'FALLBACK'|'REJECTED'|'FAILED';
export interface DtdD3PerformanceBudget{fileSizeBytes:number;triangles:number;vertices:number;primitives:number;materials:number;textures:number;maxTextureDimension:number;decodedTextureBytes:number;nodes:number;drawCalls:number;animations:number;joints:number;morphTargets:number;}
export interface DtdD3ManifestEntry{assetId:string;registryId:string;requirementId:string;category:EnvironmentalPropCategory;relativePath:string;fileType:'glb'|'gltf';byteSize:number;sha256:string;dependencies:readonly string[];lodLevel:'high'|'medium'|'low';variant:string;provenanceId:string;licenseId:string;acceptanceResultId:string;acceptanceStatus:AcceptanceStatus;validatorVersion:string;lastValidationTimestamp:string;modelStats:{nodes:number;meshes:number;primitives:number;triangles:number;vertices:number;animations:number;skins:number;morphTargets:number;cameras:number;lights:number;bounds:{min:[number,number,number];max:[number,number,number]};};materialStats:{materials:number;textures:number;maxTextureDimension:number;decodedTextureBytes:number;slots:readonly string[];};transformConvention:{units:'meters';upAxis:'+y';forwardAxis:'+z';pivot:'floor_center'|'wall_mount'|'anchor_top';handedness:'right';normalizationScale:number;};collision:{policy:'decorative_only'|'canonical_footprint';shape:'aabb'|'none';canonicalFootprintAuthority:true;meshNeverAuthoritative:true;};budgetClass:'small_repeated_prop'|'medium_structural_prop'|'large_focal_prop'|'decorative_set';revision:number;}
export interface DtdD3Manifest{schemaVersion:'catacombs.dtd_d3.authored_assets.v1';updatedAt:string;approvedRoots:readonly string[];entries:readonly DtdD3ManifestEntry[];}
export const DTD_D3_PERFORMANCE_BUDGETS:Record<DtdD3ManifestEntry['budgetClass'],DtdD3PerformanceBudget>={small_repeated_prop:{fileSizeBytes:350_000,triangles:1500,vertices:1200,primitives:8,materials:3,textures:4,maxTextureDimension:1024,decodedTextureBytes:8_388_608,nodes:24,drawCalls:4,animations:0,joints:0,morphTargets:0},medium_structural_prop:{fileSizeBytes:900_000,triangles:4500,vertices:3500,primitives:12,materials:4,textures:6,maxTextureDimension:2048,decodedTextureBytes:25_165_824,nodes:48,drawCalls:6,animations:0,joints:0,morphTargets:0},large_focal_prop:{fileSizeBytes:1_500_000,triangles:8000,vertices:6500,primitives:16,materials:6,textures:8,maxTextureDimension:2048,decodedTextureBytes:33_554_432,nodes:72,drawCalls:8,animations:0,joints:0,morphTargets:0},decorative_set:{fileSizeBytes:700_000,triangles:3000,vertices:2500,primitives:10,materials:4,textures:6,maxTextureDimension:1024,decodedTextureBytes:12_582_912,nodes:36,drawCalls:5,animations:0,joints:0,morphTargets:0}};
export const DTD_D3_AUTHORED_ASSET_MANIFEST:DtdD3Manifest={schemaVersion:'catacombs.dtd_d3.authored_assets.v1',updatedAt:'2026-07-24T00:00:00Z',approvedRoots:AUTHORED_ASSET_ROOTS,entries:[]};
const normalizePath=(p:string)=>p.replaceAll('\\','/').replace(/\/+/gu,'/');
const ext=(p:string)=>p.slice(p.lastIndexOf('.')).toLowerCase();
const contained=(root:string,p:string)=>{const rr=normalizePath(root).replace(/\/$/u,''); const pp=normalizePath(p); return pp===rr||pp.startsWith(`${rr}/`);};
export function validateDtdD3Manifest(manifest:DtdD3Manifest=DTD_D3_AUTHORED_ASSET_MANIFEST){const errors:string[]=[]; const warnings:string[]=[]; const assetIds=new Set<string>(); const bindings=new Map<string,string>(); const registryIds=new Set(ENVIRONMENTAL_PROP_REGISTRY.map(e=>e.registryId)); for(const [i,e] of manifest.entries.entries()){const p=`entries[${i}]`; if(assetIds.has(e.assetId))errors.push(`${p}: duplicate assetId ${e.assetId}`); assetIds.add(e.assetId); const prior=bindings.get(`${e.registryId}|${e.lodLevel}|${e.variant}`); if(prior&&prior!==e.assetId)errors.push(`${p}: conflicting registry/lod/variant binding with ${prior}`); bindings.set(`${e.registryId}|${e.lodLevel}|${e.variant}`,e.assetId); if(!registryIds.has(e.registryId))errors.push(`${p}: unknown registryId ${e.registryId}`); const norm=normalizePath(e.relativePath); if(norm!==e.relativePath||norm.includes('/../')||norm.startsWith('../')||norm.startsWith('/')||/^[a-z]+:/iu.test(norm))errors.push(`${p}: unsafe relativePath`); if(!manifest.approvedRoots.some(root=>contained(root,norm)))errors.push(`${p}: path outside approved roots`); if(!['.glb','.gltf'].includes(ext(norm)))errors.push(`${p}: unsupported extension`); if(e.fileType!==ext(norm).slice(1))errors.push(`${p}: fileType does not match extension`); if(e.acceptanceStatus==='ACCEPTED'||e.acceptanceStatus==='ACCEPTED_WITH_RECORDED_EXCEPTION'){if(!e.provenanceId||!e.licenseId)errors.push(`${p}: accepted asset lacks provenance/license linkage`); if(!/^[a-f0-9]{64}$/u.test(e.sha256))errors.push(`${p}: sha256 must be a hex SHA-256 digest`); } for(const dep of e.dependencies){const d=normalizePath(dep); if(d!==dep||d.includes('/../')||d.startsWith('../')||d.startsWith('/')||/^[a-z]+:/iu.test(d)||!manifest.approvedRoots.some(root=>contained(root,d)))errors.push(`${p}: unsafe dependency ${dep}`);} const b=DTD_D3_PERFORMANCE_BUDGETS[e.budgetClass]; if(e.byteSize>b.fileSizeBytes)errors.push(`${p}: file size exceeds budget`); if(e.modelStats.triangles>b.triangles)errors.push(`${p}: triangles exceed budget`); if(e.modelStats.vertices>b.vertices)errors.push(`${p}: vertices exceed budget`); if(e.modelStats.primitives>b.primitives)errors.push(`${p}: primitives exceed budget`); if(e.materialStats.materials>b.materials||e.materialStats.textures>b.textures||e.materialStats.maxTextureDimension>b.maxTextureDimension||e.materialStats.decodedTextureBytes>b.decodedTextureBytes)errors.push(`${p}: material or texture budget exceeded`); if(e.modelStats.animations>b.animations||e.modelStats.skins>b.joints||e.modelStats.morphTargets>b.morphTargets||e.modelStats.cameras||e.modelStats.lights)errors.push(`${p}: unsupported scene-global or animated data`); if(e.transformConvention.units!=='meters'||e.transformConvention.upAxis!=='+y'||e.transformConvention.forwardAxis!=='+z'||e.transformConvention.normalizationScale<=0)errors.push(`${p}: invalid transform convention`); }
return {ok:errors.length===0,errors,warnings,approvedCount:manifest.entries.filter(e=>e.acceptanceStatus==='ACCEPTED'||e.acceptanceStatus==='ACCEPTED_WITH_RECORDED_EXCEPTION').length};}
export function authoredStatusForRequirement(requirementId:string,manifest:DtdD3Manifest=DTD_D3_AUTHORED_ASSET_MANIFEST):AuthoredAssetRuntimeStatus{const matches=manifest.entries.filter(e=>e.requirementId===requirementId); if(!matches.length)return 'MISSING'; if(matches.some(e=>e.acceptanceStatus==='ACCEPTED'||e.acceptanceStatus==='ACCEPTED_WITH_RECORDED_EXCEPTION'))return 'APPROVED_AUTHORED'; if(matches.some(e=>e.acceptanceStatus==='REJECTED'))return 'REJECTED'; return 'PRESENT_UNVALIDATED';}
export function resolveDtdD3AuthoredAsset(registryId:string,variant:string,quality:'low'|'medium'|'high',manifest:DtdD3Manifest=DTD_D3_AUTHORED_ASSET_MANIFEST){const lodOrder=quality==='high'?['high','medium','low']:quality==='medium'?['medium','high','low']:['low','medium','high']; for(const lod of lodOrder){const exact=manifest.entries.find(e=>e.registryId===registryId&&e.variant===variant&&e.lodLevel===lod&&(e.acceptanceStatus==='ACCEPTED'||e.acceptanceStatus==='ACCEPTED_WITH_RECORDED_EXCEPTION')); if(exact)return exact; const fallback=manifest.entries.find(e=>e.registryId===registryId&&e.lodLevel===lod&&(e.acceptanceStatus==='ACCEPTED'||e.acceptanceStatus==='ACCEPTED_WITH_RECORDED_EXCEPTION')); if(fallback)return fallback;} return undefined;}
