import type { ResolvedDungeon } from '../contracts/index.js'; import { resolvedDungeonFieldMetadata } from '../contracts/index.js'; import { canonicalStringify } from '../canonical/serializer.js'; import { checksumResolvedDungeon, verifyResolvedDungeonChecksum } from '../canonical/checksum.js'; import { summarizeTypedArray, isSupportedTypedArray } from '../canonical/typedArrays.js';
export function inspectContractTree(v:unknown):unknown{if(isSupportedTypedArray(v))return summarizeTypedArray(v); if(Array.isArray(v))return {type:'array',length:v.length,items:v.slice(0,10).map(inspectContractTree)}; if(v&&typeof v==='object') return Object.fromEntries(Object.entries(v).slice(0,50).map(([k,val])=>[k,inspectContractTree(val)])); return v;} export function authorityLabel(field:string){return resolvedDungeonFieldMetadata[field as keyof typeof resolvedDungeonFieldMetadata];} export function canonicalExport(dungeon:ResolvedDungeon):string{return canonicalStringify(dungeon as never);} export async function checksumForWorkbench(dungeon:ResolvedDungeon){return checksumResolvedDungeon(dungeon);} export async function verifyChecksumForWorkbench(dungeon:ResolvedDungeon,checksum:string){return verifyResolvedDungeonChecksum(dungeon,checksum);} export function serializeDiagnostics(d:GenerationDiagnostics):string{return JSON.stringify(d,null,2);}

import type { GraphDiagnosticMetrics, RouteLoop, ResolvedGraphPath } from '../graph.js';
import { articulationAndBridges, degreeMap } from '../graph.js';
import type { RoomGraph, ResolvedBranch, DepthLayer, GenerationDiagnostics } from '../contracts/index.js';
export interface CatacombsGraphWorkbenchView{readonly primaryTrunk:readonly string[];readonly secondaryTrunks:readonly ResolvedBranch[];readonly divergences:readonly string[];readonly reconvergences:readonly string[];readonly immediateLoops:readonly RouteLoop[];readonly conditionalLoops:readonly ResolvedBranch[];readonly secrets:readonly ResolvedBranch[];readonly deadEnds:readonly ResolvedBranch[];readonly criticalPaths:Readonly<{initial:ResolvedGraphPath;final:ResolvedGraphPath}>;readonly depthLayers:readonly DepthLayer[];readonly roomDegrees:Readonly<Record<string,number>>;readonly nodeFunctions:Readonly<Record<string,string>>;readonly articulationPoints:readonly string[];readonly bridgeEdges:readonly string[];readonly validationTargets:readonly unknown[];readonly candidateHistory:readonly unknown[];readonly metrics:GraphDiagnosticMetrics;}
export function buildCatacombsGraphWorkbenchView(input:{graph:RoomGraph;depthLayers:readonly DepthLayer[];criticalPaths:{initial:ResolvedGraphPath;final:ResolvedGraphPath};metrics:GraphDiagnosticMetrics;loops:readonly RouteLoop[];diagnostics:GenerationDiagnostics;}):CatacombsGraphWorkbenchView{const branches=input.graph.branches; const ab=articulationAndBridges(input.graph); return {primaryTrunk:input.graph.criticalPathNodeIds,secondaryTrunks:branches.filter(b=>b.kind==='secondary_trunk'),divergences:[...new Set(branches.map(b=>b.divergenceNodeId))].sort(),reconvergences:[...new Set(branches.map(b=>b.reconvergenceNodeId).filter(Boolean) as string[])].sort(),immediateLoops:input.loops.filter(l=>l.classification==='immediate_loop'),conditionalLoops:branches.filter(b=>b.kind==='conditional_loop'),secrets:branches.filter(b=>b.kind==='secret_loop'||b.purpose==='secret_reward'),deadEnds:branches.filter(b=>b.kind==='dead_end'),criticalPaths:input.criticalPaths,depthLayers:input.depthLayers,roomDegrees:Object.fromEntries(degreeMap(input.graph)),nodeFunctions:Object.fromEntries(input.graph.nodes.map(n=>[n.id,n.function])),articulationPoints:ab.articulationPointIds,bridgeEdges:ab.bridgeEdgeIds,validationTargets:input.diagnostics.issues.map(i=>i.target).filter(Boolean),candidateHistory:input.diagnostics.attemptHistory,metrics:input.metrics};}

import type { CatacombsRoutingResult } from '../catacombsRouting.js';
export function buildCatacombsRoutingWorkbenchView(result:CatacombsRoutingResult){if(!result.ok)return {ok:false,diagnostics:result.diagnostics.issues,candidateHistory:result.diagnostics.attemptHistory}; return {ok:true,corridors:result.corridors.map(c=>({id:c.id,graphEdgeId:c.graphEdgeId,category:c.category,width:c.width,bendCount:c.bendCount,strategy:c.strategy,centerline:c.centerline,footprint:c.footprint,initialTraversable:c.initialTraversable,finalTraversable:c.finalTraversable})),doorways:result.doorways,boundaries:result.boundaries,tileLayers:result.tileLayers.layers.map(l=>({id:l.id,type:l.type,length:l.length})),navigation:{width:result.navigation.width,height:result.navigation.height,initialReachableCells:result.navigation.initialReachableCells,finalReachableCells:result.navigation.finalReachableCells,regions:result.navigation.regions,portals:result.navigation.portals},reachability:{initial:result.metrics.initialReachablePercentage,final:result.metrics.finalReachablePercentage},distanceHeatmapLayer:'distanceFromStart',clearanceHeatmapLayer:'clearanceManhattan',candidateHistory:result.diagnostics.attemptHistory,diagnostics:result.diagnostics.issues,metrics:result.metrics};}
