import { generateCatacombs } from '../generationPipeline.js';
import { DEFAULT_DUNGEON_CONFIG, D3_GENERATION_FIELDS, OVERLAY_DEFINITIONS, WORKBENCH_ENVIRONMENTS, WORKBENCH_SCHEMA_FIELDS, WORKBENCH_VERSION } from './productionPipeline.js';
import { ThreeDungeonRenderer, DEFAULT_RENDERER_OPTIONS, type OverlayState, type RendererOptions } from '../rendering/index.js';
import type { DungeonConfig } from '../contracts/index.js';
import type { DungeonRenderInput } from '../renderInput.js';
import { WORKBENCH_CSS } from './styles.js';

type State='IDLE'|'VALIDATING'|'GENERATING'|'BUILDING_SCENE'|'ANIMATING'|'READY'|'FAILED'|'DISPOSED';
const IMPORT_LIMIT=1_000_000;
const allFields=[...WORKBENCH_SCHEMA_FIELDS,...D3_GENERATION_FIELDS] as readonly any[];
const $=<T extends Element>(root:ParentNode,sel:string)=>root.querySelector(sel) as T;
function el<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string){const n=document.createElement(tag); if(text)n.textContent=text; return n;}
function setPath(obj:any,path:string,value:any){const p=path.split('.'); let o=obj; while(p.length>1)o=o[p.shift()!]??={}; o[p[0]!]=value;}
function readValue(input:HTMLInputElement|HTMLSelectElement,field:any){if(field.type==='boolean')return (input as HTMLInputElement).checked; if(field.type==='integer')return Number.parseInt(input.value,10); if(field.type==='number')return Number.parseFloat(input.value); if(field.type==='array')return input.value?input.value.split(',').map(s=>s.trim()).filter(Boolean):[]; return input.value;}
function renderJson(root:HTMLElement,data:unknown){root.textContent=JSON.stringify(data,(_,v)=>ArrayBuffer.isView(v)?{type:v.constructor.name,length:(v as ArrayBufferView).byteLength}:v,2);}
function filterJson(data:unknown,filter:string):unknown{if(!filter)return data; if(data===null||typeof data!=='object')return String(data).toLowerCase().includes(filter)?data:undefined; if(Array.isArray(data)){const items=data.map(v=>filterJson(v,filter)).filter(v=>v!==undefined); return items.length?items:undefined;} const entries=Object.entries(data as Record<string,unknown>).map(([k,v])=>[k,String(k).toLowerCase().includes(filter)?v:filterJson(v,filter)] as const).filter(([,v])=>v!==undefined); return entries.length?Object.fromEntries(entries):{};}
export class CatacombsWorkbenchApp{private state:State='IDLE';private renderer=new ThreeDungeonRenderer();private current?:{config:DungeonConfig;generation:any;renderInput:DungeonRenderInput;checksum:string;renderCount:number};private generationToken=0;private lastCanonical='';private controls!:HTMLElement;private inspector!:HTMLElement;private stats!:HTMLElement;private status!:HTMLElement;private error!:HTMLElement;private overlayState:OverlayState={enabled:Object.fromEntries(OVERLAY_DEFINITIONS.map(o=>[o.id,true])),preset:'all'};private options:RendererOptions={...DEFAULT_RENDERER_OPTIONS};private regenTimer=0;
async mount(root:HTMLElement){document.head.appendChild(Object.assign(document.createElement('style'),{textContent:WORKBENCH_CSS})); root.replaceChildren(this.layout()); this.controls=$(root,'#controls'); this.inspector=$(root,'#inspector'); this.stats=$(root,'#stats'); this.status=$(root,'#status'); this.error=$(root,'#error'); this.renderControls(); this.renderOverlays($(root,'#overlays')); await this.renderer.mount($(root,'#viewport')); new ResizeObserver(e=>{const r=e[0]?.contentRect; if(r)this.renderer.resize(r.width,r.height,window.devicePixelRatio||1);}).observe($(root,'#viewport')); this.bind(root); await this.generateNow();}
private layout(){const frag=document.createDocumentFragment(); const header=el('header'); header.append(el('span','CATACOMBS WORKBENCH')); header.firstElementChild!.className='brand'; header.append(el('span',WORKBENCH_VERSION)); header.lastElementChild!.className='badge'; const env=el('select') as HTMLSelectElement; env.ariaLabel='Environment'; for(const e of WORKBENCH_ENVIRONMENTS){const o=el('option',e.label) as HTMLOptionElement; o.value=e.id; o.disabled=e.disabled; env.append(o);} header.append(env,button('generate','Generate'),button('random','Random seed'),button('replay','Replay animation'),button('export','Export'),button('import','Import'),button('compare','Compare seed +1'),el('span','IDLE')); header.lastElementChild!.id='status'; const left=el('aside'); left.className='panel'; left.append(el('h2','Production configuration'),el('div')); left.lastElementChild!.id='controls'; left.append(el('h2','Overlays'),el('div')); left.lastElementChild!.id='overlays'; const main=el('main'); main.id='viewport'; main.className='viewport'; main.setAttribute('aria-label','Three.js Catacombs viewport'); const right=el('aside'); right.className='panel'; right.append(el('h2','Inspectors'),this.inspectorButtons(),el('input') as HTMLInputElement,el('pre','Generate a dungeon.')); (right.children[2] as HTMLInputElement).id='filter'; (right.children[2] as HTMLInputElement).placeholder='Filter inspector JSON'; right.lastElementChild!.id='inspector'; const footer=el('footer'); footer.append(el('div')); footer.firstElementChild!.id='stats'; footer.firstElementChild!.className='stats'; footer.append(el('pre')); footer.lastElementChild!.id='error'; frag.append(header,left,main,right,footer); return frag;}
private inspectorButtons(){const d=el('div'); for(const id of ['Configuration','Routing','Construction','Gameplay','Assets','Renderer statistics','Validation','Diagnostic projection','Authorization'])d.append(button(`tab-${id}`,id)); return d;}
private renderControls(){this.controls.replaceChildren(); for(const f of allFields){const lab=el('label'); const meta=el('span',`${f.path} · ${f.canonical?'canonical/regenerates':'noncanonical/presentation'} · ${f.affectedStage??'generation'}`); meta.className='meta'; lab.append(el('span',f.label),meta); let input:HTMLInputElement|HTMLSelectElement; if(f.enum){input=el('select') as HTMLSelectElement; for(const v of f.enum){const o=el('option',v); (o as HTMLOptionElement).value=v; input.append(o);} } else {input=el('input') as HTMLInputElement; input.type=f.type==='boolean'?'checkbox':f.type==='integer'||f.type==='number'?'number':'text'; if(f.minimum!==undefined)(input as HTMLInputElement).min=String(f.minimum); if(f.maximum!==undefined)(input as HTMLInputElement).max=String(f.maximum);} input.dataset.path=f.path; const v=this.defaultValue(f.path); if((input as HTMLInputElement).type==='checkbox')(input as HTMLInputElement).checked=Boolean(v); else input.value=Array.isArray(v)?v.join(','):String(v??''); input.addEventListener('change',()=>this.onControl(f,input)); lab.append(input); this.controls.append(lab);} }
private defaultValue(path:string){const defaults:any={...DEFAULT_DUNGEON_CONFIG,generation:{sizeProfile:'small',targetRoomCount:18,areaBudget:14000,targetPackingDensity:.34,minimumRoomPadding:3,maximumNodeDegree:5,softForwardBiasWeight:.12},routing:{corridorWidth:2},renderer:this.options}; return path.split('.').reduce((o,k)=>o?.[k],defaults);}
private renderOverlays(root:HTMLElement){root.className='overlay-grid'; root.replaceChildren(); for(const o of OVERLAY_DEFINITIONS){const lab=el('label'); const cb=el('input') as HTMLInputElement; cb.type='checkbox'; cb.checked=true; cb.addEventListener('change',()=>{this.overlayState={...this.overlayState,enabled:{...this.overlayState.enabled,[o.id]:cb.checked}}; this.renderer.setOverlayState(this.overlayState);}); lab.append(cb,document.createTextNode(` ${o.label}`)); root.append(lab);}}
private bind(root:HTMLElement){root.addEventListener('click',e=>{const id=(e.target as HTMLElement).id; if(id==='generate')void this.generateNow(); if(id==='random'){($(root,'[data-path="rootSeed"]') as HTMLInputElement).value=String(Math.floor(Math.random()*1e9)); void this.generateNow();} if(id==='replay')void this.replay(); if(id==='export')this.exportBundle(); if(id==='import')void this.importBundle(); if(id==='compare')void this.compare(); if(id.startsWith('tab-'))this.showInspector(id.slice(4));}); $('#filter' in root?root:document,'#filter')?.addEventListener('input',()=>this.showInspector('Diagnostic projection'));}
private onControl(field:any,input:HTMLInputElement|HTMLSelectElement){const value=readValue(input,field); if(field.path.startsWith('renderer.')){setPath(this.options,field.path.replace('renderer.',''),value); this.renderer.updatePresentation(this.options); this.showStats(false); return;} clearTimeout(this.regenTimer); this.regenTimer=window.setTimeout(()=>void this.generateNow(),180);}
private projectConfig(){const config:any={...DEFAULT_DUNGEON_CONFIG}; const generation:any={}; const routing:any={}; for(const f of allFields){const input=this.controls.querySelector(`[data-path="${f.path}"]`) as HTMLInputElement|HTMLSelectElement|null; if(!input)continue; const v=readValue(input,f); if(f.path.startsWith('generation.'))setPath(generation,f.path.replace('generation.',''),v); else if(f.path.startsWith('routing.'))setPath(routing,f.path.replace('routing.',''),v); else if(!f.path.startsWith('renderer.'))setPath(config,f.path,v);} return {config:config as DungeonConfig,generation,routing};}
private validate(config:DungeonConfig,generation:any){const issues:string[]=[]; if(config.environmentId!=='catacombs')issues.push('Only Catacombs is active.'); if(!String(config.rootSeed).trim())issues.push('Seed is required.'); else if(!/^(0|[1-9][0-9]*)$/u.test(String(config.rootSeed)))issues.push('Seed must be a canonical unsigned integer.'); if(generation.targetRoomCount<12||generation.targetRoomCount>60)issues.push('Room count must be 12-60.'); return issues;}
async generateNow(){const token=++this.generationToken; this.setState('VALIDATING'); const {config,generation}=this.projectConfig(); const issues=this.validate(config,generation); if(issues.length){this.fail(issues.join('\n'));return;} const canonical=JSON.stringify({config,generation}); this.lastCanonical=canonical; this.setState('GENERATING'); await Promise.resolve(); let result; try{result=generateCatacombs({config,generation,requireReturnPortal:true});}catch(error){this.fail(`generation: ${error instanceof Error?error.message:String(error)}`);return;} if(token!==this.generationToken)return; if(!result.ok){this.fail(`${result.failure.stage}: ${result.failure.message}`); return;} this.setState('BUILDING_SCENE'); await this.renderer.render(result.renderInput,this.options); if(token!==this.generationToken)return; this.current={config,generation,renderInput:result.renderInput,checksum:this.fingerprint(result.renderInput),renderCount:(this.current?.renderCount??0)+1}; this.setState(this.options.animateBuild&&!this.options.reducedMotion?'ANIMATING':'READY'); window.setTimeout(()=>{if(token===this.generationToken)this.setState('READY');},this.options.animateBuild?500:0); this.showInspector('Diagnostic projection'); this.showStats(true);}
private async replay(){if(!this.current)return; const before=this.current.renderCount; await this.renderer.render(this.current.renderInput,this.options); this.current.renderCount=before; this.showStats(false);}
private showInspector(tab:string){if(!this.current){this.inspector.textContent='No dungeon generated.';return;} const data:any={Configuration:{config:this.current.config,generation:this.current.generation},Routing:this.current.renderInput.geometry,Construction:this.current.renderInput.construction,Gameplay:this.current.renderInput.gameplayPresentation,Assets:this.current.renderInput.construction.assetResolutions,'Renderer statistics':this.renderer.getStats(),Validation:{state:this.state},'Diagnostic projection':{renderInputVersion:this.current.renderInput.rendererContractVersion,checksum:this.current.checksum,nonAuthority:true},Authorization:{manifestVerification:'not supplied',checksumComparison:this.current.checksum,sensitiveAuthority:'not bundled'}}[tab]??{}; const filter=($('#filter' in document?document:document,'#filter') as HTMLInputElement|null)?.value?.toLowerCase(); renderJson(this.inspector,filter?filterJson(data,filter):data);}
private showStats(canonical:boolean){const s=this.renderer.getStats(); this.stats.replaceChildren(...Object.entries({state:this.state,rooms:this.current?.renderInput.geometry.tileLayers.layers.find(l=>l.id==='roomOwner')?.length??0,corridors:this.current?.renderInput.geometry.corridors.length??0,boundaries:this.current?.renderInput.geometry.boundaries.length??0,construction:this.current?.renderInput.construction.records.length??0,gameplay:this.current?.renderInput.gameplayPresentation.placements.length??0,drawCalls:s.drawCalls,triangles:s.triangles,checksum:this.current?.checksum??'none',measurement:canonical?'generation committed':'presentation only'}).map(([k,v])=>{const b=el('span',`${k}: ${v}`); b.className='badge'; return b;}));}
private exportBundle(){if(!this.current)return; const blob=new Blob([JSON.stringify({schemaVersion:'d3.workbench.bundle.v1',kind:'diagnostic-inspection-bundle',config:this.current.config,generation:this.current.generation,checksum:this.current.checksum},null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=el('a') as HTMLAnchorElement; a.href=url; a.download=`catacombs-${String(this.current.config.rootSeed).replace(/[^\w.-]/g,'_')}.json`; a.click(); setTimeout(()=>URL.revokeObjectURL(url),0);}
private async importBundle(){const input=el('input') as HTMLInputElement; input.type='file'; input.accept='application/json'; input.onchange=async()=>{const f=input.files?.[0]; if(!f)return; if(f.size>IMPORT_LIMIT){this.fail('Import rejected: file exceeds 1 MB.');return;} const text=await f.text(); if(/<script|function\s*\(|=>|\beval\b|privateKey/iu.test(text)){this.fail('Import rejected: executable or private-key-like content.');return;} const data=JSON.parse(text); if(data.schemaVersion!=='d3.workbench.bundle.v1'||!data.config){this.fail('Import rejected: unsupported schema/version.');return;} for(const [path,val] of Object.entries(data.config)){const input=this.controls.querySelector(`[data-path="${path}"]`) as HTMLInputElement|null; if(input)input.value=String(val);} await this.generateNow();}; input.click();}
private async compare(){const cur=this.projectConfig(); const seed=Number.parseInt(String(cur.config.rootSeed),10); const alt={...cur.config,rootSeed:Number.isFinite(seed)?String((seed+1)>>>0):String(cur.config.rootSeed)}; try{const a=generateCatacombs({config:cur.config,generation:cur.generation}); const b=generateCatacombs({config:alt,generation:cur.generation}); renderJson(this.inspector,{comparison:'seed/config comparison',classification:'Generation difference when renderInput fingerprints differ; renderer-only options excluded.',current:a.ok?this.fingerprint(a.renderInput):a.failure,alternate:b.ok?this.fingerprint(b.renderInput):b.failure});}catch(error){this.fail(`Compare failed: ${error instanceof Error?error.message:String(error)}`);}}
private fingerprint(v:unknown){let h=2166136261; const s=JSON.stringify(v); for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619); return `fnv1a-${(h>>>0).toString(16)}`;}
dispose(){this.generationToken++; clearTimeout(this.regenTimer); this.renderer.dispose(); this.setState('DISPOSED'); this.controls?.replaceChildren(); this.inspector?.replaceChildren(); this.stats?.replaceChildren(); this.error?.replaceChildren(); this.status?.parentElement?.parentElement?.replaceChildren();}
private setState(s:State){this.state=s; if(this.status)this.status.textContent=s;}
private fail(m:string){this.setState('FAILED'); this.error.textContent=m;}
}
function button(id:string,text:string){const b=el('button',text); b.id=id; return b;}
