import { createHash } from 'node:crypto'; import type { RngStreamName } from '../contracts/index.js';
export const RNG_ALGORITHM_VERSION='xoshiro128ss-sha256-v1'; export const RNG_NAMESPACES=['graph','roomAssignment','spatialEmbedding','corridorRouting','construction','encounters','hazards','objectives','bosses','props','naming','templates','subBiome','modifiers'] as const;
export interface RngSnapshot{readonly algorithmVersion:string;readonly rootSeed:string;readonly generatorVersion:string;readonly namespace:string;readonly state:readonly [number,number,number,number];readonly gaussianSpare?:number;}
const te=new TextEncoder(); function seedParts(rootSeed:string,generatorVersion:string,ns:string):[number,number,number,number]{const h=createHash('sha256').update(te.encode(`${RNG_ALGORITHM_VERSION}\0${generatorVersion}\0${rootSeed}\0${ns}`)).digest(); return [h.readUInt32LE(0),h.readUInt32LE(4),h.readUInt32LE(8),h.readUInt32LE(12)];}
function rotl(x:number,k:number){return ((x<<k)|(x>>>(32-k)))>>>0;} function validSeed(s:string){if(!/^(0|[1-9][0-9]*)$/.test(s)) throw new RangeError('rootSeed must be a canonical unsigned integer decimal string'); const n=BigInt(s); if(n>0xffffffffn) throw new RangeError('rootSeed exceeds uint32 maximum');}
export class DeterministicRng{#s:[number,number,number,number]; #spare:number|undefined; constructor(readonly rootSeed:string, readonly generatorVersion:string, readonly namespace:string, state?:readonly[number,number,number,number], spare?:number){validSeed(rootSeed); this.#s=state?[...state] as [number,number,number,number]:seedParts(rootSeed,generatorVersion,namespace); this.#spare=spare;}
nextUint32():number{const s=this.#s; const r=rotl(Math.imul(s[1],5)>>>0,7); const result=Math.imul(r,9)>>>0; const t=(s[1]<<9)>>>0; s[2]^=s[0]; s[3]^=s[1]; s[1]^=s[2]; s[0]^=s[3]; s[2]^=t; s[3]=rotl(s[3],11); return result;}
nextFloat01():number{return this.nextUint32()/0x100000000;} float(min:number,max:number){if(!Number.isFinite(min)||!Number.isFinite(max)||min>max) throw new RangeError('invalid float range'); return min+(max-min)*this.nextFloat01();}
intInclusive(min:number,max:number){if(!Number.isSafeInteger(min)||!Number.isSafeInteger(max)||min>max) throw new RangeError('invalid integer range'); const span=max-min+1; if(span<=0||span>0x100000000) throw new RangeError('integer range too large'); const limit=Math.floor(0x100000000/span)*span; let x=this.nextUint32(); while(x>=limit)x=this.nextUint32(); return min+(x%span);} chance(p:number){if(!Number.isFinite(p)||p<0||p>1) throw new RangeError('invalid probability'); return this.nextFloat01()<p;} pick<T>(a:readonly T[]):T{if(a.length===0) throw new RangeError('cannot pick from empty array'); return a[this.intInclusive(0,a.length-1)]!;} shuffle<T>(a:readonly T[]):T[]{const out=[...a]; for(let i=out.length-1;i>0;i--){const j=this.intInclusive(0,i); [out[i],out[j]]=[out[j]!,out[i]!];} return out;} gaussian(mean=0,standardDeviation=1){if(!Number.isFinite(mean)||!Number.isFinite(standardDeviation)||standardDeviation<0) throw new RangeError('invalid gaussian parameters'); if(this.#spare!==undefined){const z=this.#spare; this.#spare=undefined; return mean+z*standardDeviation;} let u=0,v=0; while(u===0)u=this.nextFloat01(); while(v===0)v=this.nextFloat01(); const mag=Math.sqrt(-2*Math.log(u)); const z0=mag*Math.cos(2*Math.PI*v); this.#spare=mag*Math.sin(2*Math.PI*v); return mean+z0*standardDeviation;} fork(namespace:string){return new DeterministicRng(this.rootSeed,this.generatorVersion,`${this.namespace}/${namespace}`);} forAttempt(attemptIndex:number){if(!Number.isSafeInteger(attemptIndex)||attemptIndex<0) throw new RangeError('invalid attemptIndex'); return this.fork(`attempt/${attemptIndex}`);} snapshot():RngSnapshot{return {algorithmVersion:RNG_ALGORITHM_VERSION,rootSeed:this.rootSeed,generatorVersion:this.generatorVersion,namespace:this.namespace,state:[...this.#s] as [number,number,number,number],...(this.#spare===undefined?{}:{gaussianSpare:this.#spare})};}}
export function createRngStream(rootSeed:string,generatorVersion:string,namespace:RngStreamName){return new DeterministicRng(rootSeed,generatorVersion,namespace);} export function deriveAttemptSeed(rootSeed:string,generatorVersion:string,attemptIndex:number){const r=new DeterministicRng(rootSeed,generatorVersion,'retry/attempt-seed').forAttempt(attemptIndex); return String(r.nextUint32());}
export interface AttemptDiagnostic{readonly attemptIndex:number;readonly rootSeed:string;readonly attemptSeed:string;readonly failedStage:string;readonly code:string;readonly message:string;} export function recordFailedAttempt(rootSeed:string,generatorVersion:string,attemptIndex:number,failedStage:string,code:string,message:string):AttemptDiagnostic{return {attemptIndex,rootSeed,attemptSeed:deriveAttemptSeed(rootSeed,generatorVersion,attemptIndex),failedStage,code,message};}
