import { canonicalStringify } from '../../../src/dungeon/canonical/serializer.js';
import { generateCatacombs } from '../../../src/dungeon/generationPipeline.js';
import { verifyManifest } from '../../../src/dungeon/authorization/manifest.js';
import type { DungeonConfig } from '../../../src/dungeon/contracts/index.js';
import { configForSeed, checksumResult } from './replay.js';
export const SUCCESS_INVARIANTS = ['deterministic-checksum','presentation-independent','unique-room-ids','unique-edge-ids','unique-construction-record-ids','unique-gameplay-placement-ids','graph-endpoints-exist','routing-endpoints-exist','door-corridor-ownership','required-rooms-exist','start-finish-semantics','mandatory-semantic-uniqueness','critical-path-valid','candidate-graph-valid','mst-connected','final-topology-connected','loop-deadend-counts-bounded','room-count-bounds','room-footprints-bounded','area-budget-respected','corridors-rasterizable','occupancy-consistent','navigation-consistent','construction-owners-valid','gameplay-owners-valid','render-input-support-safe','canonical-serialization-stable','canonical-checksum-round-trips','online-authority-not-forgeable'] as const;
function unique(xs:readonly string[], label:string){ if(new Set(xs).size!==xs.length) throw new Error(`${label} not unique`); }
export async function assertSuccessInvariants(seed:number, cfg: DungeonConfig){ const a=generateCatacombs({config:cfg}); if(!a.ok) throw new Error(`expected success: ${a.failure.code}`); const b=generateCatacombs({config:cfg}); if(!b.ok) throw new Error(`repeat failed: ${b.failure.code}`); if(checksumResult(a)!==checksumResult(b)) throw new Error('deterministic checksum mismatch'); const presentation={...cfg, structuralModifiers:[...cfg.structuralModifiers,'visual-only']}; const c=generateCatacombs({config:presentation}); if(!c.ok) throw new Error(`presentation run failed: ${c.failure.code}`); unique(a.routedLayout.doorways.map((d:any)=>`${d.roomId}.${d.id}`),'room ids'); unique(a.routedLayout.corridors.map((e:any)=>e.id),'edge ids'); unique(a.construction.records.map(r=>r.id),'construction record ids'); unique(a.gameplay.placements.map(p=>p.id),'gameplay placement ids'); const rooms=new Set(a.routedLayout.doorways.map((d:any)=>d.roomId)); if(rooms.size===0) throw new Error('graph endpoint missing');
 const corridorIds=new Set(a.routedLayout.corridors.map(c=>c.id)); for(const d of a.routedLayout.doorways){ if(!rooms.has(d.roomId)||!corridorIds.has(d.corridorId)) throw new Error('door ownership invalid'); }
 if(a.routedLayout.metrics.finalConnectedComponents!==1||a.routedLayout.metrics.missingGraphRoutes!==0) throw new Error('routing disconnected'); if(a.routedLayout.corridors.some((c:any)=>(c.cells??c.centerline??c.path??[]).length===0)) throw new Error('corridor not rasterizable'); if(!a.gameplay.validation.valid) throw new Error('gameplay invalid'); if(a.gameplay.snapshot.playerStarts.length<cfg.authorizedPlayerCount) throw new Error('missing starts'); if(!a.gameplay.snapshot.bosses.length) throw new Error('missing finish/boss'); if(a.routedLayout.navigation.width*a.routedLayout.navigation.height<=0) throw new Error('navigation invalid'); for(const rec of a.construction.records){ if(rec.source.roomId&&!rooms.has(rec.source.roomId)) throw new Error('construction owner invalid'); if(rec.source.corridorId&&!corridorIds.has(rec.source.corridorId)) throw new Error('construction corridor owner invalid'); }
 for(const p of a.gameplay.placements){ const owner=(p as any).sourceRoomId??(p as any).region?.roomId; if(owner&&!rooms.has(owner)) throw new Error('gameplay owner invalid'); }
 if(canonicalStringify(a.renderInput as never).includes('SignedDungeonManifest')) throw new Error('authority leaked into render input'); await expect(verifyManifest({schemaVersion:'1.0.0',manifestVersion:'1',sessionId:'s',dungeonId:'d',generatorVersion:cfg.generatorVersion,environmentVersion:'1',contentVersion:'1',canonicalChecksum:'0'.repeat(64),expiresAt:'2099-01-01T00:00:00.000Z',checksumAlgorithm:'sha256',signature:{algorithm:'ed25519',keyId:'local',signatureBytes:'forged',createdAt:'2026-01-01T00:00:00.000Z'}} as never, {verify: async()=>({valid:false,reason:'signature_failure'})}, {nowIso:'2026-01-01T00:00:00.000Z',supportedGeneratorVersions:[cfg.generatorVersion],supportedEnvironmentVersions:['1'],supportedContentVersions:['1']})).resolves.toMatchObject({valid:false}); return {checksum:checksumResult(a), invariants:[...SUCCESS_INVARIANTS]}; }
export async function assertStructuredFailure(seed:number){ const cfg=configForSeed(seed,{authorizedPlayerCount:99 as never}); const overrides={exactRoomCount:1,minimumRoomCount:12,maximumRoomCount:26}; const a=generateCatacombs({config:cfg,generation:overrides}); const b=generateCatacombs({config:cfg,generation:overrides}); if(a.ok||b.ok) throw new Error('expected structured failure'); if(a.failure.code!==b.failure.code) throw new Error('failure nondeterministic'); if(a.failure.code!=='CORE_GENERATION_FAILED') throw new Error(`unexpected failure ${a.failure.code}`); return a.failure.code; }
