import { createHash } from 'node:crypto';
import { canonicalStringify } from '../../../src/dungeon/canonical/serializer.js';
import { generateCatacombs } from '../../../src/dungeon/generationPipeline.js';
import { config as baseConfig } from '../fixtures/config.js';
import { T1_GENERATOR_VERSION, T1_SCHEMA_VERSION, normalizeT1Seed } from './seedModel.js';
import type { DungeonConfig } from '../../../src/dungeon/contracts/index.js';
export interface T1ReplayRecord { readonly suiteId:string; readonly seedSetVersion:string; readonly seed:number; readonly canonicalConfiguration:DungeonConfig; readonly generationOverrides?:Record<string,unknown>; readonly shardIndex:number; readonly shardCount:number; readonly caseIndex:number; readonly expectedInvariant?:string; readonly expectedResult:'success'|'failure'; readonly expectedFailureCode?:string; readonly actualResult?:string; readonly generatorVersion:string; readonly schemaVersion:string; readonly canonicalChecksum?:string; }
export function configForSeed(seed:number, extra:Partial<DungeonConfig>={}):DungeonConfig{ return baseConfig(String(normalizeT1Seed(seed)),{rootSeed:String(normalizeT1Seed(seed)),...extra}); }
export function checksumResult(r:Extract<ReturnType<typeof generateCatacombs>,{ok:true}>):string{ return createHash('sha256').update(canonicalStringify({renderInput:r.renderInput,construction:r.construction.canonicalProjection,gameplay:r.gameplay.canonicalProjection} as never)).digest('hex'); }
export function makeReplayRecord(input:Omit<T1ReplayRecord,'generatorVersion'|'schemaVersion'>):T1ReplayRecord{ normalizeT1Seed(input.seed); return {...input,generatorVersion:T1_GENERATOR_VERSION,schemaVersion:T1_SCHEMA_VERSION}; }
export function runReplayRecord(record:T1ReplayRecord){ if(record.generatorVersion!==T1_GENERATOR_VERSION) throw new Error('unsupported generator version'); if(record.schemaVersion!==T1_SCHEMA_VERSION) throw new Error('unsupported schema version'); normalizeT1Seed(record.seed); if(record.canonicalConfiguration.rootSeed!==String(record.seed)) throw new Error('configuration seed mismatch'); const r=generateCatacombs({config:record.canonicalConfiguration,generation:record.generationOverrides as never}); if(record.expectedResult==='success'){ if(!r.ok) throw new Error(`expected success got ${r.failure.code}`); const checksum=checksumResult(r); if(record.canonicalChecksum&&checksum!==record.canonicalChecksum) throw new Error(`checksum mismatch ${checksum}`); return {ok:true as const, checksum}; } if(r.ok) throw new Error('expected failure got success'); if(!record.expectedFailureCode) throw new Error('missing expected failure code'); if(r.failure.code!==record.expectedFailureCode) throw new Error(`failure code mismatch ${r.failure.code}`); return {ok:true as const, failureCode:r.failure.code}; }
