import type { ConstructionRecord } from './construction.js';
import type { Footprint } from './assetRegistry.js';

export const ENVIRONMENTAL_PROP_TAXONOMY_VERSION = 'catacombs.environmental_props.dtd_d2.v1';
export type EnvironmentalPropCategory = 'COFFIN'|'SARCOPHAGUS'|'TOMB_MARKER'|'PILLAR'|'BROKEN_PILLAR'|'RUBBLE'|'DEBRIS'|'CANDLE'|'CANDLE_CLUSTER'|'STATUE'|'SHRINE'|'CHAIN'|'WALL_DECORATION'|'FLOOR_DECORATION'|'ARCHITECTURAL_TRIM'|'UNKNOWN_ENVIRONMENTAL_PROP';
export type EnvironmentalPlacementSurface = 'FLOOR'|'WALL_ADJACENT'|'WALL_MOUNTED'|'CORNER'|'ROOM_CENTER'|'CORRIDOR_EDGE'|'HANGING_SAFE_FALLBACK';
export interface EnvironmentalPropRegistryEntry { readonly category:EnvironmentalPropCategory; readonly registryId:string; readonly name:string; readonly displayCategory:'structural'|'burial'|'ritual'|'wall'|'floor'|'small_decor'|'fallback'; readonly supportedSurfaces:readonly EnvironmentalPlacementSurface[]; readonly decorativeFootprint:Footprint; readonly clearancePolicy:'ignore_navigation'|'edge_only'|'preserve_lane'|'reserved_clearance'|'diagnostic_only'; readonly orientationPolicy:'free_cardinal'|'face_wall'|'face_center'|'axis_aligned'|'safe_fallback'; readonly prototypeGeometryFamily:string; readonly defaultScaleRange:readonly [number,number]; readonly qualityProfileBehavior:'same_semantics_simplified_mesh'|'always_low_poly'; readonly materialFamily:string; readonly selectionBehavior:'selectable'|'selectable_with_bounds'|'diagnostic_selectable'; readonly defaultVisible:boolean; readonly inspectorDescription:string; readonly futureAuthoredModelRequired:boolean; readonly assetRequirementId:string; }
const fp=(w:number,h:number,d=1):Footprint=>({shape:'rect',w,h,d});
export const ENVIRONMENTAL_PROP_REGISTRY: readonly EnvironmentalPropRegistryEntry[] = ([
  ['COFFIN','Stone or wooden coffin','burial','FLOOR',fp(1.2,2.4,.8),'edge_only','face_center','coffin','old_wood','DTD-D3-CATACOMBS-STONE-COFFIN'],
  ['SARCOPHAGUS','Raised stone sarcophagus','burial','FLOOR',fp(2,3,1),'reserved_clearance','axis_aligned','sarcophagus','carved_stone','DTD-D3-CATACOMBS-STONE-SARCOPHAGUS'],
  ['TOMB_MARKER','Tomb or grave marker','burial','WALL_ADJACENT',fp(.8,.4,1.2),'edge_only','face_wall','tomb_marker','carved_stone','DTD-D3-CATACOMBS-TOMB-MARKER-SET'],
  ['PILLAR','Intact structural pillar','structural','ROOM_CENTER',fp(1,1,3),'reserved_clearance','axis_aligned','pillar','crypt_masonry','DTD-D3-CATACOMBS-INTACT-PILLAR'],
  ['BROKEN_PILLAR','Broken structural pillar','structural','ROOM_CENTER',fp(1.4,1.4,1.5),'preserve_lane','axis_aligned','broken_pillar','rubble','DTD-D3-CATACOMBS-BROKEN-PILLAR'],
  ['RUBBLE','Collapsed stone rubble','floor','CORNER',fp(1.5,1.5,.5),'preserve_lane','free_cardinal','rubble','rubble','DTD-D3-CATACOMBS-RUBBLE-SET'],
  ['DEBRIS','Small debris dressing','floor','FLOOR',fp(1,1,.25),'ignore_navigation','free_cardinal','debris','rubble','DTD-D3-CATACOMBS-DEBRIS-SET'],
  ['CANDLE','Single candle','small_decor','FLOOR',fp(.2,.2,.4),'ignore_navigation','free_cardinal','candle','wax','DTD-D3-CATACOMBS-CANDLE-SET'],
  ['CANDLE_CLUSTER','Candle cluster','small_decor','FLOOR',fp(.8,.8,.45),'ignore_navigation','free_cardinal','candle_cluster','wax','DTD-D3-CATACOMBS-CANDLE-SET'],
  ['STATUE','Memorial statue','ritual','ROOM_CENTER',fp(1.2,1.2,2.4),'reserved_clearance','face_center','statue','carved_stone','DTD-D3-CATACOMBS-STATUE-SET'],
  ['SHRINE','Small shrine composition','ritual','WALL_ADJACENT',fp(1.8,1,.9),'edge_only','face_wall','shrine','carved_stone','DTD-D3-CATACOMBS-SHRINE-SET'],
  ['CHAIN','Restrained hanging chain fallback','wall','WALL_MOUNTED',fp(.3,.3,1.5),'ignore_navigation','face_wall','chain','corroded_iron','DTD-D3-CATACOMBS-CHAIN-SET'],
  ['WALL_DECORATION','Wall plaque or banner','wall','WALL_MOUNTED',fp(1,.15,1.2),'ignore_navigation','face_wall','wall_decoration','cloth','DTD-D3-CATACOMBS-WALL-DECORATION-SET'],
  ['FLOOR_DECORATION','Floor accent or inset','floor','FLOOR',fp(1,1,.05),'ignore_navigation','free_cardinal','floor_decoration','worn_stone','DTD-D3-CATACOMBS-ARCHITECTURAL-TRIM-SET'],
  ['ARCHITECTURAL_TRIM','Architectural trim','structural','WALL_ADJACENT',fp(2,.3,.3),'ignore_navigation','axis_aligned','architectural_trim','carved_stone','DTD-D3-CATACOMBS-ARCHITECTURAL-TRIM-SET'],
  ['UNKNOWN_ENVIRONMENTAL_PROP','Unknown environmental prop','fallback','FLOOR',fp(.8,.8,.8),'diagnostic_only','safe_fallback','unknown_environmental_prop','worn_stone','DTD-D3-CATACOMBS-UNKNOWN-FALLBACK']
] as readonly any[]).map(([category,name,displayCategory,surface,decorativeFootprint,clearancePolicy,orientationPolicy,prototypeGeometryFamily,materialFamily,assetRequirementId]): EnvironmentalPropRegistryEntry=>({category:category as EnvironmentalPropCategory,registryId:`catacombs.environmental_prop.${String(category).toLowerCase()}`,name,displayCategory:displayCategory as EnvironmentalPropRegistryEntry['displayCategory'],supportedSurfaces:[surface as EnvironmentalPlacementSurface],decorativeFootprint:decorativeFootprint as Footprint,clearancePolicy:clearancePolicy as EnvironmentalPropRegistryEntry['clearancePolicy'],orientationPolicy:orientationPolicy as EnvironmentalPropRegistryEntry['orientationPolicy'],prototypeGeometryFamily:String(prototypeGeometryFamily),defaultScaleRange:[.9,1.12] as const,qualityProfileBehavior:'same_semantics_simplified_mesh' as const,materialFamily:String(materialFamily),selectionBehavior:category==='UNKNOWN_ENVIRONMENTAL_PROP'?'diagnostic_selectable' as const:'selectable' as const,defaultVisible:true,inspectorDescription:String(name),futureAuthoredModelRequired:category!=='UNKNOWN_ENVIRONMENTAL_PROP',assetRequirementId:String(assetRequirementId)}));
const byCategory = new Map(ENVIRONMENTAL_PROP_REGISTRY.map(e=>[e.category,e]));
const familyMap:Record<string,EnvironmentalPropCategory>={coffin:'COFFIN',sarcophagus:'SARCOPHAGUS',burial_slab:'TOMB_MARKER',grave_marker:'TOMB_MARKER',round_column:'PILLAR',square_pillar:'PILLAR',broken_masonry:'BROKEN_PILLAR',rubble:'RUBBLE',bone_pile:'DEBRIS',skull_pile:'DEBRIS',candle:'CANDLE',brazier:'CANDLE_CLUSTER',wall_torch:'CANDLE',memorial_statuary:'STATUE',altar:'SHRINE',reliquary:'SHRINE',chain:'CHAIN',banner:'WALL_DECORATION',soot:'FLOOR_DECORATION',moisture_moss:'FLOOR_DECORATION',stone_baseboard:'ARCHITECTURAL_TRIM'};
export function environmentalCategoryForRecord(record:ConstructionRecord):EnvironmentalPropCategory|undefined{ if(record.category==='column'||record.category==='pillar')return 'PILLAR'; if(record.category==='trim')return 'ARCHITECTURAL_TRIM'; if(record.category==='decal')return 'FLOOR_DECORATION'; if(!['prop','prop cluster','fixture'].includes(record.category))return undefined; return familyMap[record.requestedAssetFamily]??'UNKNOWN_ENVIRONMENTAL_PROP'; }
export function environmentalRegistryEntry(category:EnvironmentalPropCategory){ return byCategory.get(category)??byCategory.get('UNKNOWN_ENVIRONMENTAL_PROP')!; }
export interface EnvironmentalPropView { readonly id:string; readonly category:EnvironmentalPropCategory; readonly registryId:string; readonly recordId:string; readonly assetRegistryId?:string; readonly ownerType:'room'|'corridor'|'doorway'|'boundary'|'unknown'; readonly ownerId?:string; readonly surface:EnvironmentalPlacementSurface; readonly position:{readonly x:number; readonly y:number; readonly z:number}; readonly orientation:number; readonly scale:readonly [number,number,number]; readonly validationState:'valid'|'warning'|'invalid'; readonly warnings:readonly string[]; readonly compositionGroupId:string; readonly deterministicVariant:string; readonly prototypeGeometryFamily:string; readonly assetRequirementId:string; readonly description:string; }
export function buildEnvironmentalPropViews(records:readonly ConstructionRecord[]):EnvironmentalPropView[]{const seen=new Set<string>(); return records.flatMap((r):EnvironmentalPropView[]=>{const cat=environmentalCategoryForRecord(r); if(!cat)return []; const e=environmentalRegistryEntry(cat); const warnings:string[]=[]; if(seen.has(r.id))warnings.push('duplicate-id'); seen.add(r.id); const p=r.transform.position; if(![p.x,p.y,p.z,r.transform.orientation,...r.transform.scale].every(Number.isFinite))warnings.push('invalid-transform'); const ownerId=r.source.roomId??r.source.corridorId??r.source.doorwayId??r.source.boundaryId; const ownerType=r.source.roomId?'room':r.source.corridorId?'corridor':r.source.doorwayId?'doorway':r.source.boundaryId?'boundary':'unknown'; if(!ownerId)warnings.push('missing-owner'); const wallish=r.placementRole.includes('wall')||cat==='WALL_DECORATION'||cat==='CHAIN'; const surface=wallish?'WALL_MOUNTED':ownerType==='corridor'?'CORRIDOR_EDGE':cat==='PILLAR'?'ROOM_CENTER':e.supportedSurfaces[0]!; return [{id:`environment.${r.id}`,category:cat,registryId:e.registryId,recordId:r.id,...(r.resolvedAssetId?{assetRegistryId:r.resolvedAssetId}:{}),ownerType, ...(ownerId?{ownerId}:{}),surface,position:p,orientation:r.transform.orientation,scale:r.transform.scale,validationState:warnings.includes('invalid-transform')?'invalid':warnings.length?'warning':'valid',warnings,compositionGroupId:r.canonicalTags.find(t=>t.startsWith('catacombs.prop_cluster.'))??`${ownerType}.${ownerId??'unknown'}.environment`,deterministicVariant:r.canonicalVariant?.id??r.deterministicVariant.candidateIds.join('|')??'unknown',prototypeGeometryFamily:e.prototypeGeometryFamily,assetRequirementId:e.assetRequirementId,description:e.inspectorDescription}];}).sort((a,b)=>a.id.localeCompare(b.id));}
export function summarizeEnvironmentalProps(records:readonly ConstructionRecord[]){const views=buildEnvironmentalPropViews(records); const byCategory=views.reduce<Record<string,number>>((m,v)=>{m[v.category]=(m[v.category]??0)+1;return m;},{}); return {total:views.length,byCategory,fallbackKindCount:views.filter(v=>v.category==='UNKNOWN_ENVIRONMENTAL_PROP').length,missingOwnerCount:views.filter(v=>v.ownerType==='unknown').length,invalidTransformCount:views.filter(v=>v.validationState==='invalid').length,prototypeRequirementCount:views.filter(v=>environmentalRegistryEntry(v.category).futureAuthoredModelRequired).length};}
