import type { DungeonConfig } from './contracts/index.js';
import type { GameplayPlacementRecord, GameplayPlacementKind, GameplayRegion } from './gameplay.js';

export type GameplayPlacementCategory='player_start'|'encounter'|'elite_encounter'|'boss'|'hazard'|'loot'|'objective'|'interaction'|'encounter_area'|'unknown';
export type GameplayPlacementVisualState='valid'|'warning'|'invalid'|'unsupported'|'missing_position'|'unknown_category'|'missing_owner';
export interface GameplayPlacementView{readonly id:string;readonly resultKey:'primary'|'comparison';readonly kind:string;readonly category:GameplayPlacementCategory;readonly position?:{readonly x:number;readonly y:number;readonly z:number;readonly yaw?:number};readonly owner:{readonly type:'room'|'corridor'|'boss_arena'|'global'|'unknown';readonly id?:string};readonly groupId?:string;readonly canonicalRegion?:GameplayRegion;readonly canonicalAreas:readonly GameplayRegion[];readonly validationState:GameplayPlacementVisualState;readonly issues:readonly string[];readonly tags:readonly string[];readonly description:string;readonly metadata:Readonly<Record<string,string|number|boolean>>;}
export interface GameplayOverlayState{readonly enabled:boolean;readonly markers:boolean;readonly areas:boolean;readonly labels:boolean;readonly ownership:boolean;readonly validation:boolean;readonly categories:Readonly<Record<GameplayPlacementCategory,boolean>>;readonly selectedPlacementId?:string;readonly hoveredPlacementId?:string;}
export interface GameplayPlacementLegendEntry{readonly category:GameplayPlacementCategory;readonly label:string;readonly color:number;readonly shape:string;readonly description:string;readonly count:number;readonly visible:boolean;}
export const GAMEPLAY_CATEGORY_ORDER:readonly GameplayPlacementCategory[]=['player_start','encounter','elite_encounter','boss','hazard','loot','objective','interaction','encounter_area','unknown'];
export const GAMEPLAY_CATEGORY_STYLES:Readonly<Record<GameplayPlacementCategory,{label:string;color:number;emissive:number;shape:string;scale:number;y:number;description:string}>>={
 player_start:{label:'Player start',color:0x3d8bff,emissive:0x071b44,shape:'octagonal pad + beacon',scale:1.05,y:.38,description:'Canonical player entrance/start socket.'},
 encounter:{label:'Encounter',color:0xd84a4a,emissive:0x330606,shape:'cone + ground ring',scale:1,y:.62,description:'Encounter or spawn-group placement record.'},
 elite_encounter:{label:'Elite encounter',color:0xb04dff,emissive:0x2b0644,shape:'reinforced diamond + ring',scale:1.18,y:.7,description:'Encounter/spawn-group containing elite threat metadata.'},
 boss:{label:'Boss',color:0xff4fc3,emissive:0x48092f,shape:'large crown beacon',scale:1.75,y:.9,description:'Boss arena or boss spawn anchor.'},
 hazard:{label:'Hazard / trap',color:0xffb020,emissive:0x442500,shape:'warning plate + spike',scale:1.1,y:.35,description:'Hazard telegraph/effect placement.'},
 loot:{label:'Loot / reward',color:0xffd84d,emissive:0x4a3500,shape:'chest block + beacon',scale:1,y:.46,description:'Reward presentation point; no loot authority.'},
 objective:{label:'Objective',color:0x25d7ff,emissive:0x063844,shape:'pillar + ring',scale:1.2,y:.7,description:'Server-authorized objective placement.'},
 interaction:{label:'Interaction / event',color:0xdffcff,emissive:0x123b3d,shape:'small obelisk + square plate',scale:.95,y:.55,description:'Event, recovery, checkpoint, or interaction marker.'},
 encounter_area:{label:'Encounter area',color:0xff7d7d,emissive:0x240000,shape:'transparent region bounds',scale:1,y:.08,description:'Canonical region/bounds visualization.'},
 unknown:{label:'Unknown / diagnostic',color:0xd6d6d6,emissive:0x202020,shape:'neutral cube + diagnostic ring',scale:1,y:.55,description:'Supported fallback for unrecognized or presentation-invalid records.'}
};
export const DEFAULT_GAMEPLAY_OVERLAY_STATE:GameplayOverlayState={enabled:true,markers:true,areas:true,labels:false,ownership:true,validation:true,categories:Object.fromEntries(GAMEPLAY_CATEGORY_ORDER.map(c=>[c,true])) as Record<GameplayPlacementCategory,boolean>};
export function categoryForGameplayKind(kind:string,tags:readonly string[]=[]):GameplayPlacementCategory{switch(kind as GameplayPlacementKind){case 'PLAYER_START':return 'player_start';case 'ENCOUNTER':case 'MONSTER_SPAWN_GROUP':return tags.includes('elite')?'elite_encounter':'encounter';case 'REINFORCEMENT_SOCKET':case 'EVENT':case 'LATE_JOIN':case 'RECOVERY':case 'CHECKPOINT_RETURN':return 'interaction';case 'HAZARD':return 'hazard';case 'OBJECTIVE':return 'objective';case 'BOSS':return 'boss';case 'REWARD_PRESENTATION':return 'loot';default:return 'unknown';}}
function finite(n:unknown):n is number{return typeof n==='number'&&Number.isFinite(n);} function pos(p:any){if(p?.transform&&finite(p.transform.x)&&finite(p.transform.y)&&finite(p.transform.z))return {x:p.transform.x,y:p.transform.y,z:p.transform.z,yaw:finite(p.transform.yaw)?p.transform.yaw:0}; if(p?.region&&finite(p.region.x)&&finite(p.region.y))return {x:p.region.x,y:p.region.y,z:0,yaw:0}; return undefined;}
function areas(p:any):GameplayRegion[]{return [p.region,p.telegraphRegion,p.effectRegion,p.arrivalRegion,...(Array.isArray(p.safeRegions)?p.safeRegions:[]),...(Array.isArray(p.reservedAbilityRegions)?p.reservedAbilityRegions:[])].filter((r:any)=>r&&finite(r.x)&&finite(r.y)&&finite(r.w)&&finite(r.h)&&r.w>=0&&r.h>=0);}
export function buildGameplayPlacementViews(placements:readonly GameplayPlacementRecord[],config?:Pick<DungeonConfig,'gameType'|'difficulty'|'authorizedPlayerCount'>,resultKey:'primary'|'comparison'='primary'):readonly GameplayPlacementView[]{const seen=new Set<string>(); return [...placements].sort((a,b)=>a.id.localeCompare(b.id)).map((p,i)=>{const issues:string[]=[]; const category=categoryForGameplayKind(p.kind,p.tags??[]); const position=pos(p); if(!position)issues.push('missing_position'); if(!p.sourceRoomId&&!p.sourceCorridorId)issues.push('missing_owner'); if(seen.has(p.id))issues.push('duplicate_presentation_id'); seen.add(p.id); const validationState:GameplayPlacementVisualState=issues.includes('missing_position')?'missing_position':issues.includes('missing_owner')?'missing_owner':category==='unknown'?'unknown_category':'valid'; const owner:GameplayPlacementView['owner']=p.sourceRoomId?{type:p.kind==='BOSS'?'boss_arena':'room',id:p.sourceRoomId}:p.sourceCorridorId?{type:'corridor',id:p.sourceCorridorId}:{type:'unknown'}; const groupId=(p as any).encounterDefinitionId??(p as any).monsterFamilyId??(p as any).bossDefinitionId??(p as any).objectiveDefinitionId; const view:GameplayPlacementView={id:p.id||`placement.${i}`,resultKey,kind:p.kind,category,owner,canonicalAreas:areas(p),validationState,issues,tags:p.tags??[],description:GAMEPLAY_CATEGORY_STYLES[category].description,metadata:{...(config?{gameType:config.gameType,difficulty:config.difficulty,authorizedPlayerCount:config.authorizedPlayerCount}:{}),canonicalAreaCount:areas(p).length},...(position?{position}:{}),...(groupId?{groupId}:{}),...((p as any).region?{canonicalRegion:(p as any).region}:{} )}; return view;});}
export function buildGameplayLegendEntries(views:readonly GameplayPlacementView[],state:GameplayOverlayState=DEFAULT_GAMEPLAY_OVERLAY_STATE):readonly GameplayPlacementLegendEntry[]{const counts=new Map<GameplayPlacementCategory,number>(); for(const v of views)counts.set(v.category,(counts.get(v.category)??0)+1); return GAMEPLAY_CATEGORY_ORDER.filter(c=>(counts.get(c)??0)>0).map(category=>({...GAMEPLAY_CATEGORY_STYLES[category],category,count:counts.get(category)??0,visible:state.enabled&&state.categories[category]!==false}));}
export function summarizeGameplayPlacement(view:GameplayPlacementView){return {id:view.id,result:view.resultKey,category:GAMEPLAY_CATEGORY_STYLES[view.category].label,kind:view.kind,owner:view.owner,groupId:view.groupId,position:view.position,canonicalRegion:view.canonicalRegion?{id:view.canonicalRegion.id,roomId:view.canonicalRegion.roomId,corridorId:view.canonicalRegion.corridorId,x:view.canonicalRegion.x,y:view.canonicalRegion.y,w:view.canonicalRegion.w,h:view.canonicalRegion.h}:undefined,canonicalAreaCount:view.canonicalAreas.length,validationState:view.validationState,issues:view.issues,tags:view.tags.slice(0,8),description:view.description,metadata:view.metadata};}
