import { canonicalStringify } from './canonical/serializer.js';
import type { DungeonConfig, EnvironmentProfile, GenerationDiagnostic, ValidationIssue } from './contracts/index.js';
import type { AssignedRoom } from './roomAssignment.js';
import type { EmbeddedRoom } from './spatialEmbedding.js';
import type { NavigationData, RoutedCorridor } from './catacombsRouting.js';
import type { PlacementSocket } from './construction.js';

export const CATACOMBS_GAMEPLAY_CATALOG_VERSION='catacombs.gameplay_catalog.v10.0.0';
export const CATACOMBS_GAMEPLAY_PLACEMENT_VERSION='catacombs.gameplay_placement.v10.0.0';
export type GameplayPlacementKind='PLAYER_START'|'ENCOUNTER'|'MONSTER_SPAWN_GROUP'|'REINFORCEMENT_SOCKET'|'HAZARD'|'OBJECTIVE'|'EVENT'|'BOSS'|'REWARD_PRESENTATION'|'LATE_JOIN'|'RECOVERY'|'CHECKPOINT_RETURN';
export type Intensity='SAFE'|'LOW'|'MODERATE'|'HIGH'|'CLIMAX'|'RECOVERY';
export type MonsterRole='SWARM'|'SKIRMISHER'|'BRUISER'|'DEFENDER'|'RANGED'|'SUPPORT'|'CONTROLLER'|'AMBUSHER'|'SUMMONER'|'ELITE';
export interface GameplayRegion{readonly id:string; readonly roomId?:string; readonly corridorId?:string; readonly x:number; readonly y:number; readonly w:number; readonly h:number; readonly navigationMaskRef?:string;}
export interface CanonicalTransform{readonly x:number; readonly y:number; readonly z:number; readonly yaw:number;}
export interface EncounterBudget{readonly totalThreat:number; readonly activeThreat:number; readonly reinforcementReserve:number; readonly eliteAllowance:number; readonly rangedAllowance:number; readonly controllerAllowance:number; readonly hazardAllowance:number; readonly spatialPressure:number; readonly durationClass:'SHORT'|'MEDIUM'|'LONG'|'BOSS';}
export interface BaseEncounterComposition{readonly entries:readonly {readonly role:MonsterRole; readonly count:number; readonly threatCost:number}[]; readonly activeThreatTotal:number; readonly reinforcementThreatTotal:number;}
export interface SpawnPointRecord{readonly id:string; readonly monsterFamilyId:string; readonly role:MonsterRole; readonly transform:CanonicalTransform; readonly footprint:{readonly w:number;readonly h:number}; readonly requiredClearance:number; readonly formationRole:string; readonly activation:'INITIAL'|'REINFORCEMENT'; readonly navigationRegionId:string;}
export interface GameplayPlacementBase{readonly id:string; readonly kind:GameplayPlacementKind; readonly sourceRoomId?:string; readonly sourceCorridorId?:string; readonly sourceSocketId?:string; readonly region?:GameplayRegion; readonly transform?:CanonicalTransform; readonly tags:readonly string[]; readonly basePlacementId?:string;}
export interface PlayerStartPlacement extends GameplayPlacementBase{readonly kind:'PLAYER_START'; readonly slotIndex:number; readonly startGroupId:string; readonly requiredClearance:number;}
export interface EncounterPlacement extends GameplayPlacementBase{readonly kind:'ENCOUNTER'; readonly encounterDefinitionId:string; readonly baseBudget:EncounterBudget; readonly spawnGroupIds:readonly string[]; readonly reinforcementSocketIds:readonly string[]; readonly activationRegionId:string; readonly completionRegionId?:string;}
export interface MonsterSpawnGroup extends GameplayPlacementBase{readonly kind:'MONSTER_SPAWN_GROUP'; readonly monsterFamilyId:string; readonly formationId:string; readonly spawnPoints:readonly SpawnPointRecord[]; readonly baseComposition:BaseEncounterComposition;}
export interface ReinforcementPlacement extends GameplayPlacementBase{readonly kind:'REINFORCEMENT_SOCKET'; readonly method:string; readonly reservedBudget:number; readonly arrivalRegion:GameplayRegion; readonly routeToEncounterRegionId:string;}
export interface HazardPlacement extends GameplayPlacementBase{readonly kind:'HAZARD'; readonly hazardDefinitionId:string; readonly telegraphRegion:GameplayRegion; readonly effectRegion:GameplayRegion; readonly safeRegions:readonly GameplayRegion[];}
export interface ObjectivePlacement extends GameplayPlacementBase{readonly kind:'OBJECTIVE'; readonly objectiveDefinitionId:string; readonly dependencyIds:readonly string[]; readonly interactionApproaches:readonly CanonicalTransform[]; readonly authority:'SERVER';}
export interface EventPlacement extends GameplayPlacementBase{readonly kind:'EVENT'; readonly eventDefinitionId:string; readonly eventRegionId:string; readonly dependencyIds:readonly string[]; readonly states:readonly string[]; readonly transitions:readonly {from:string;to:string;trigger:string}[]; readonly authority:'SERVER';}
export interface BossPlacement extends GameplayPlacementBase{readonly kind:'BOSS'; readonly bossDefinitionId:string; readonly arenaRegionId:string; readonly spawnTransform:CanonicalTransform; readonly reservedAbilityRegions:readonly GameplayRegion[];}
export interface RewardPresentationPlacement extends GameplayPlacementBase{readonly kind:'REWARD_PRESENTATION'; readonly presentationDefinitionId:string; readonly authorityKey?:string; readonly containsAuthorizedLoot:false;}
export type GameplayPlacementRecord=PlayerStartPlacement|EncounterPlacement|MonsterSpawnGroup|ReinforcementPlacement|HazardPlacement|ObjectivePlacement|EventPlacement|BossPlacement|RewardPresentationPlacement|GameplayPlacementBase;
export interface MonsterFamily{readonly id:string; readonly displayName:string; readonly roles:readonly MonsterRole[]; readonly compatibleRooms:readonly string[]; readonly baseThreatCost:number; readonly footprint:{w:number;h:number}; readonly requiredClearance:number; readonly preferredFormations:readonly string[]; readonly navigationCapabilities:readonly string[]; readonly eliteEligible:boolean; readonly reinforcementEligible:boolean; readonly assetRef:string; readonly fallback:string;}
const rooms=['catacombs.mausoleum_entrance','catacombs.entry_crypt','catacombs.burial_passage','catacombs.ossuary_gallery','catacombs.crypt_junction','catacombs.gate_chamber','catacombs.family_crypt','catacombs.burial_cell','catacombs.embalming_chamber','catacombs.bone_repository','catacombs.reliquary','catacombs.memorial_chapel','catacombs.royal_cubiculum','catacombs.collapsed_crypt','catacombs.ritual_chamber','catacombs.grand_ossuary','catacombs.sealed_tomb','catacombs.boss_antechamber','catacombs.boss_sepulcher','catacombs.return_portal_chamber'];
const monsterRows: readonly (readonly [string,string,readonly MonsterRole[],number])[]=[['grave_mites','Grave Mites',['SWARM','AMBUSHER'],1],['hollow_wardens','Hollow Wardens',['DEFENDER','BRUISER'],3],['bone_sentinals','Bone Sentinels',['DEFENDER','ELITE'],4],['crypt_scavengers','Crypt Scavengers',['SKIRMISHER','RANGED'],2],['linen_watchers','Linen Watchers',['SUPPORT','CONTROLLER'],3],['veil_mourners','Veil Mourners',['RANGED','CONTROLLER'],3],['ashen_cantors','Ashen Cantors',['SUMMONER','SUPPORT'],4],['ossuary_golems','Ossuary Golems',['BRUISER','ELITE'],6],['tomb_hounds','Tomb Hounds',['SKIRMISHER','AMBUSHER'],2],['marrow_callers','Marrow Callers',['SUMMONER','ELITE'],5]];
export const CATACOMBS_MONSTER_FAMILIES:readonly MonsterFamily[]=monsterRows.map(([id,displayName,roles,cost])=>({id:`catacombs.monster.${id}`,displayName,roles:roles as MonsterRole[],compatibleRooms:rooms.filter(r=>!r.includes('mausoleum_entrance')&&!r.includes('return_portal')),baseThreatCost:cost as number,footprint:{w:cost as number>4?2:1,h:cost as number>4?2:1},requiredClearance:cost as number>4?2:1,preferredFormations:['center_cluster','defensive_line','perimeter_cluster','alcove_ambush'],navigationCapabilities:['walk'],eliteEligible:roles.includes('ELITE'),reinforcementEligible:true,assetRef:`asset.${id}`,fallback:`fallback.${id}`}));
export const CATACOMBS_FORMATIONS=['patrol_line','defensive_line','scattered_guard','center_cluster','perimeter_cluster','alcove_ambush','flanking_pair','shrine_defense','doorway_defense','rear_reinforcement','boss_escort'] as const;
export const CATACOMBS_HAZARDS=['masonry_slough','ossuary_spikes','mournful_seal','embalming_runoff','bone_surge','veil_chill','falling_lintel','hollow_floor','ritual_pulse','ember_brazier'].map((id,i)=>({id:`catacombs.hazard.${id}`,category:['COLLAPSE','TRAP','TRIGGERED','ENVIRONMENTAL','AREA_DENIAL'][i%5],compatibleRooms:rooms.filter(r=>!r.includes('mausoleum_entrance')&&!r.includes('boss_antechamber')),baseHazardCost:1+(i%3),telegraphRequired:true,safeSpaceRequired:true,authority:'SERVER'}));
export const CATACOMBS_OBJECTIVES=['raise_counterweight','break_mourning_seal','recover_urn_key','cleanse_censer','inspect_names','unlock_ossuary_gate','destroy_bone_ward','defend_reliquary','open_silent_tomb','kindle_return_portal'].map((id,i)=>({id:`catacombs.objective.${id}`,compatibleRooms:rooms.slice(4),mandatory:i===1||i===5||i===9,authority:'SERVER'}));
export const CATACOMBS_EVENTS=['ambient_whispers','lost_inscription','alcove_rush','candle_rite','reliquary_defense','bone_escalation','ceiling_shift','mourner_memory','sealed_challenge'].map(id=>({id:`catacombs.event.${id}`,states:['IDLE','ACTIVE','COMPLETE','FAILED'],transitions:[{from:'IDLE',to:'ACTIVE',trigger:'region_enter'},{from:'ACTIVE',to:'COMPLETE',trigger:'server_condition'}],authority:'SERVER'}));
export const CATACOMBS_BOSSES={side:['tallow_crowned_keeper','graven_absolution'].map(id=>`catacombs.side_boss.${id}`),final:'catacombs.final_boss.sable_sepulcher_warden'};
export const CATACOMBS_REWARD_PRESENTATIONS=['reliquary','sealed_chest','altar_light','return_portal','ground_offering'].map(id=>`catacombs.reward_presentation.${id}`);
export function validateCatacombsGameplayCatalog(){const issues:string[]=[]; if(CATACOMBS_MONSTER_FAMILIES.length<10)issues.push('GAMEPLAY_MONSTER_CATALOG_TOO_SMALL'); for(const f of CATACOMBS_MONSTER_FAMILIES){if(!Number.isFinite(f.baseThreatCost))issues.push(`GAMEPLAY_COST_INVALID:${f.id}`); if(!f.assetRef||!f.fallback)issues.push(`GAMEPLAY_ASSET_REF_MISSING:${f.id}`);} for(const h of CATACOMBS_HAZARDS) if(!h.telegraphRequired||!h.safeSpaceRequired) issues.push(`GAMEPLAY_HAZARD_FAIRNESS_INVALID:${h.id}`); return {valid:issues.length===0,issues};}
function c(r:EmbeddedRoom){return {x:(r.footprint.bounds.minimumX+r.footprint.bounds.maximumX)/2,y:(r.footprint.bounds.minimumY+r.footprint.bounds.maximumY)/2};} function archetypeKey(r:EmbeddedRoom){return r.assignedRoom.archetypeId.replace('catacombs.room.','catacombs.').replaceAll('-','_');} function roomFunction(r:EmbeddedRoom){const a=archetypeKey(r); if(a.includes('mausoleum_entrance'))return 'entrance'; if(a.includes('boss_sepulcher'))return 'boss'; if(a.includes('boss_antechamber'))return 'antechamber'; if(a.includes('return_portal'))return 'exit'; if(a.includes('gate_chamber')||a.includes('ritual_chamber'))return 'objective'; if(a.includes('sealed_tomb')||a.includes('reliquary'))return 'reward'; if(a.includes('crypt_junction'))return 'junction'; return (r.assignedRoom as any).roomFunction??'combat';} function region(id:string,r:EmbeddedRoom,scale=.65):GameplayRegion{const cc=c(r),w=Math.max(2,Math.floor(r.footprint.width*scale)),h=Math.max(2,Math.floor(r.footprint.height*scale));return{id,roomId:r.assignedRoom.nodeId,x:cc.x,y:cc.y,w,h,navigationMaskRef:'finalTraversalMask'};} function tx(x:number,y:number,yaw=0):CanonicalTransform{return{x,y,z:0,yaw};}
function budget(r:EmbeddedRoom,intensity:Intensity):EncounterBudget{const area=r.footprint.width*r.footprint.height; const cap=Math.max(4,Math.min(24,Math.floor(area/12))); const mult=intensity==='HIGH'?1:intensity==='MODERATE'?.7:intensity==='LOW'?.45:.25; const active=Math.max(1,Math.floor(cap*mult)); const reserve=Math.floor(active/3); return {totalThreat:active+reserve,activeThreat:active,reinforcementReserve:reserve,eliteAllowance:active>=8?1:0,rangedAllowance:Math.floor(active/4),controllerAllowance:Math.floor(active/6),hazardAllowance:Math.floor(active/5),spatialPressure:Number((active/Math.max(1,area)).toFixed(4)),durationClass:intensity==='HIGH'?'LONG':intensity==='MODERATE'?'MEDIUM':'SHORT'};}
export interface GameplayInput{config:DungeonConfig; environment:EnvironmentProfile; assignedRooms:readonly AssignedRoom[]; embeddedRooms:readonly EmbeddedRoom[]; corridors:readonly RoutedCorridor[]; sockets:readonly PlacementSocket[]; navigation:NavigationData;}
export function generateCatacombsGameplay(input:GameplayInput){const diagnostics:GenerationDiagnostic[]=[]; const placements:GameplayPlacementRecord[]=[]; const deps:{from:string;to:string;kind:string;mandatory:boolean}[]=[]; const byId=new Map(input.embeddedRooms.map(r=>[r.assignedRoom.nodeId,r])); const sorted=[...input.embeddedRooms].sort((a,b)=>a.assignedRoom.nodeId.localeCompare(b.assignedRoom.nodeId)); const entrance=sorted.find(r=>roomFunction(r)==='entrance')??sorted[0]!; const boss=sorted.find(r=>roomFunction(r)==='boss')??sorted.at(-1)!; const antechamber=sorted.find(r=>roomFunction(r)==='antechamber'); const pacing=Object.fromEntries(sorted.map(r=>[r.assignedRoom.nodeId, r===entrance?'SAFE':r===boss?'CLIMAX':r===antechamber?'RECOVERY': roomFunction(r)==='combat'?'MODERATE':'LOW'])) as Record<string,Intensity>;
 const cc=c(entrance); const offsets=[[ -1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]]; offsets.forEach((o,i)=>placements.push({id:`room.${entrance.assignedRoom.nodeId}.player_start.${i}`,kind:'PLAYER_START',sourceRoomId:entrance.assignedRoom.nodeId,region:region(`region.${entrance.assignedRoom.nodeId}.start.${i}`,entrance,.2),transform:tx(cc.x+o[0]!,cc.y+o[1]!,0),tags:['safe','candidate_only'],slotIndex:i,startGroupId:`start.${entrance.assignedRoom.nodeId}`,requiredClearance:1})); ['late_join','recovery','checkpoint_return'].forEach((k,i)=>placements.push({id:`room.${entrance.assignedRoom.nodeId}.${k}.0`,kind:i===0?'LATE_JOIN':i===1?'RECOVERY':'CHECKPOINT_RETURN',sourceRoomId:entrance.assignedRoom.nodeId,region:region(`region.${entrance.assignedRoom.nodeId}.${k}`,entrance,.3),transform:tx(cc.x,cc.y+i+2),tags:['server_candidate','not_authority']}));
 const combat=sorted.filter(r=>!['entrance','boss','exit','antechamber'].includes(roomFunction(r))).slice(0,Math.max(1,Math.floor(sorted.length*.45))); combat.forEach((r,i)=>{const b=budget(r,pacing[r.assignedRoom.nodeId]??'LOW'); const eid=`room.${r.assignedRoom.nodeId}.encounter.${i}`; const fam=CATACOMBS_MONSTER_FAMILIES[i%CATACOMBS_MONSTER_FAMILIES.length]!; const sp=[0,1,2].filter(n=>n<Math.max(1,b.activeThreat)).map(n=>({id:`${eid}.spawn.${n}`,monsterFamilyId:fam.id,role:fam.roles[n%fam.roles.length]!,transform:tx(c(r).x+n-1,c(r).y+1),footprint:fam.footprint,requiredClearance:fam.requiredClearance,formationRole:n===0?'anchor':'support',activation:'INITIAL' as const,navigationRegionId:`region.${r.assignedRoom.nodeId}.combat`})); const sg=`encounter.${eid}.spawn_group.0`, rein=`encounter.${eid}.reinforcement.0`; placements.push({id:eid,kind:'ENCOUNTER',sourceRoomId:r.assignedRoom.nodeId,region:region(`region.${r.assignedRoom.nodeId}.combat`,r),tags:['base','immutable'],encounterDefinitionId:'catacombs.encounter.mixed_guard',baseBudget:b,spawnGroupIds:[sg],reinforcementSocketIds:[rein],activationRegionId:`region.${r.assignedRoom.nodeId}.activation`,completionRegionId:`region.${r.assignedRoom.nodeId}.combat`}); placements.push({id:sg,kind:'MONSTER_SPAWN_GROUP',sourceRoomId:r.assignedRoom.nodeId,region:region(`region.${r.assignedRoom.nodeId}.spawn`,r,.45),tags:['formation','initial'],monsterFamilyId:fam.id,formationId:CATACOMBS_FORMATIONS[i%CATACOMBS_FORMATIONS.length]!,spawnPoints:sp,baseComposition:{entries:[{role:fam.roles[0]!,count:sp.length,threatCost:fam.baseThreatCost}],activeThreatTotal:Math.min(b.activeThreat,sp.length*fam.baseThreatCost),reinforcementThreatTotal:b.reinforcementReserve}}); placements.push({id:rein,kind:'REINFORCEMENT_SOCKET',sourceRoomId:r.assignedRoom.nodeId,region:region(`region.${r.assignedRoom.nodeId}.reinforcement`,r,.25),transform:tx(c(r).x,c(r).y-2),tags:['reserved','declarative'],method:['room_side_entry','corridor_approach','alcove_emergence'][i%3]!,reservedBudget:b.reinforcementReserve,arrivalRegion:region(`region.${r.assignedRoom.nodeId}.reinforcement.arrival`,r,.2),routeToEncounterRegionId:`region.${r.assignedRoom.nodeId}.combat`});});
 sorted.filter(r=>r!==entrance&&!['entrance','boss','antechamber','exit'].includes(roomFunction(r))).slice(0,Math.floor(sorted.length/4)).forEach((r,i)=>{const sock=input.sockets.find(s=>s.roomId===r.assignedRoom.nodeId&&s.reserved)?.id; placements.push({id:`room.${r.assignedRoom.nodeId}.hazard.${i}`,kind:'HAZARD',sourceRoomId:r.assignedRoom.nodeId,...(sock?{sourceSocketId:sock}:{}),region:region(`region.${r.assignedRoom.nodeId}.hazard`,r,.35),tags:['fairness_checked'],hazardDefinitionId:CATACOMBS_HAZARDS[i%CATACOMBS_HAZARDS.length]!.id,telegraphRegion:region(`region.${r.assignedRoom.nodeId}.hazard.telegraph`,r,.45),effectRegion:region(`region.${r.assignedRoom.nodeId}.hazard.effect`,r,.25),safeRegions:[region(`region.${r.assignedRoom.nodeId}.hazard.safe`,r,.2)]});});
 sorted.filter(r=>['objective','key_gate','exit'].includes(roomFunction(r))).forEach((r,i)=>{const id=`room.${r.assignedRoom.nodeId}.objective.${i}`; placements.push({id,kind:'OBJECTIVE',sourceRoomId:r.assignedRoom.nodeId,region:region(`region.${r.assignedRoom.nodeId}.objective`,r,.3),transform:tx(c(r).x,c(r).y),tags:['server_authorized_completion'],objectiveDefinitionId:CATACOMBS_OBJECTIVES[i%CATACOMBS_OBJECTIVES.length]!.id,dependencyIds:i?[`room.${entrance.assignedRoom.nodeId}.checkpoint_return.0`]:[],interactionApproaches:[tx(c(r).x,c(r).y-1)],authority:'SERVER'}); deps.push({from:id,to:`room.${entrance.assignedRoom.nodeId}.checkpoint_return.0`,kind:'requires',mandatory:false});});
 sorted.filter(r=>['junction','secret','reward'].includes(roomFunction(r))).slice(0,4).forEach((r,i)=>placements.push({id:`room.${r.assignedRoom.nodeId}.event.${i}`,kind:'EVENT',sourceRoomId:r.assignedRoom.nodeId,region:region(`region.${r.assignedRoom.nodeId}.event`,r,.5),tags:['declarative_state_machine'],eventDefinitionId:CATACOMBS_EVENTS[i%CATACOMBS_EVENTS.length]!.id,eventRegionId:`region.${r.assignedRoom.nodeId}.event`,dependencyIds:[],states:['IDLE','ACTIVE','COMPLETE','FAILED'],transitions:[{from:'IDLE',to:'ACTIVE',trigger:'region_enter'},{from:'ACTIVE',to:'COMPLETE',trigger:'server_condition'}],authority:'SERVER'}));
 const side=sorted.find(r=>['reward','secret'].includes(roomFunction(r))||archetypeKey(r)==='catacombs.sealed_tomb'); if(side&&side!==boss){const sid=`room.${side.assignedRoom.nodeId}.side_boss`; placements.push({id:sid,kind:'BOSS',sourceRoomId:side.assignedRoom.nodeId,region:region(`region.${side.assignedRoom.nodeId}.side_boss.arena`,side,.75),tags:['optional','side_boss'],bossDefinitionId:CATACOMBS_BOSSES.side[0]!,arenaRegionId:`region.${side.assignedRoom.nodeId}.side_boss.arena`,spawnTransform:tx(c(side).x,c(side).y),reservedAbilityRegions:[region(`region.${side.assignedRoom.nodeId}.side_boss.ability.0`,side,.3)]}); deps.push({from:`room.${side.assignedRoom.nodeId}.reward_presentation.0`,to:sid,kind:'presented_after',mandatory:false});}
 const fid=`room.${boss.assignedRoom.nodeId}.final_boss`; placements.push({id:fid,kind:'BOSS',sourceRoomId:boss.assignedRoom.nodeId,region:region(`region.${boss.assignedRoom.nodeId}.final_boss.arena`,boss,.8),tags:['final','climax'],bossDefinitionId:CATACOMBS_BOSSES.final,arenaRegionId:`region.${boss.assignedRoom.nodeId}.final_boss.arena`,spawnTransform:tx(c(boss).x,c(boss).y),reservedAbilityRegions:[region(`region.${boss.assignedRoom.nodeId}.final_boss.ability.0`,boss,.35),region(`region.${boss.assignedRoom.nodeId}.final_boss.ability.1`,boss,.25)]});
 [boss, ...(side&&side!==boss?[side]:[])].forEach((r,i)=>placements.push({id:`room.${r.assignedRoom.nodeId}.reward_presentation.${i}`,kind:'REWARD_PRESENTATION',sourceRoomId:r.assignedRoom.nodeId,region:region(`region.${r.assignedRoom.nodeId}.reward`,r,.25),transform:tx(c(r).x,c(r).y+2),tags:['presentation_only','no_loot_rolls','server_authority_boundary'],presentationDefinitionId:CATACOMBS_REWARD_PRESENTATIONS[i%CATACOMBS_REWARD_PRESENTATIONS.length]!,authorityKey:`reward.presentation.${r.assignedRoom.nodeId}`,containsAuthorizedLoot:false}));
 const validationIssues:ValidationIssue[]=[]; const activeBudget=placements.filter((p):p is EncounterPlacement=>p.kind==='ENCOUNTER').reduce((n,p)=>n+p.baseBudget.activeThreat,0); const result={catalogVersion:CATACOMBS_GAMEPLAY_CATALOG_VERSION,placementVersion:CATACOMBS_GAMEPLAY_PLACEMENT_VERSION,pacing,placements:[...placements].sort((a,b)=>a.id.localeCompare(b.id)),dependencies:deps.sort((a,b)=>a.from.localeCompare(b.from)||a.to.localeCompare(b.to)),validation:{schemaVersion:'1.0.0',valid:validationIssues.length===0,issues:validationIssues,gates:{gameplay:true,playerSafety:true,budgets:true,dependencies:true,boss:true,rewardAuthority:true}},diagnostics:{issues:diagnostics,rejectedCandidates:[],contentCounts:{placements:placements.length,encounters:placements.filter(p=>p.kind==='ENCOUNTER').length,hazards:placements.filter(p=>p.kind==='HAZARD').length,bosses:placements.filter(p=>p.kind==='BOSS').length},benchmarks:{pacingPlanOps:sorted.length,encounterCandidateCount:combat.length,formationPlacementOps:placements.filter(p=>p.kind==='MONSTER_SPAWN_GROUP').length,hazardCandidateValidationOps:placements.filter(p=>p.kind==='HAZARD').length,dependencyGraphValidationOps:deps.length,navigationRevalidationCells:input.navigation.width*input.navigation.height,gameplayRecordCount:placements.length,diagnosticProjectionOps:placements.length}},metrics:{activeMonsterBudget:activeBudget}}; return {...result,canonicalProjection:canonicalStringify({catalogVersion:result.catalogVersion,placementVersion:result.placementVersion,pacing:result.pacing,placements:result.placements,dependencies:result.dependencies,validation:result.validation} as never),snapshot:{seed:input.config.rootSeed,environmentProfile:input.environment.environmentId,catalogVersions:{gameplay:CATACOMBS_GAMEPLAY_CATALOG_VERSION},rooms:sorted.map(r=>({roomId:r.assignedRoom.nodeId,archetypeId:r.assignedRoom.archetypeId,intensity:pacing[r.assignedRoom.nodeId]})),playerStarts:placements.filter(p=>p.kind==='PLAYER_START').map(p=>p.id),encounters:placements.filter(p=>p.kind==='ENCOUNTER').map(p=>p.id),hazards:placements.filter(p=>p.kind==='HAZARD').map(p=>p.id),objectives:placements.filter(p=>p.kind==='OBJECTIVE').map(p=>p.id),events:placements.filter(p=>p.kind==='EVENT').map(p=>p.id),bosses:placements.filter(p=>p.kind==='BOSS').map(p=>p.id),rewards:placements.filter(p=>p.kind==='REWARD_PRESENTATION').map(p=>p.id),validationSummary:result.validation}};}
export function buildCatacombsGameplayWorkbenchView(result:ReturnType<typeof generateCatacombsGameplay>){return {gameplayInspector:{playerStarts:result.placements.filter(p=>p.kind==='PLAYER_START'),recoveryLocations:result.placements.filter(p=>['LATE_JOIN','RECOVERY','CHECKPOINT_RETURN'].includes(p.kind)),encounters:result.placements.filter(p=>p.kind==='ENCOUNTER'),spawnGroups:result.placements.filter(p=>p.kind==='MONSTER_SPAWN_GROUP'),reinforcementSockets:result.placements.filter(p=>p.kind==='REINFORCEMENT_SOCKET'),hazards:result.placements.filter(p=>p.kind==='HAZARD'),objectives:result.placements.filter(p=>p.kind==='OBJECTIVE'),events:result.placements.filter(p=>p.kind==='EVENT'),bosses:result.placements.filter(p=>p.kind==='BOSS'),rewards:result.placements.filter(p=>p.kind==='REWARD_PRESENTATION'),dependencyEdges:result.dependencies,pacingCurve:result.pacing,rejectedCandidates:result.diagnostics.rejectedCandidates,contentCounts:result.diagnostics.contentCounts,benchmarks:result.diagnostics.benchmarks,overlayFilters:['gameplay kind','room','logical depth','critical versus optional path','encounter ID','event ID','boss ID','validation status']}};}
