import * as THREE from 'three';
import type { JsonObject, Vec3, AssetForgeFailure, AssetGenerationContext, GeneratedAssetDefinition, AssetGeneratorPack, AssetBudget } from '../contracts/authoritative.js';
import { ok, err, type Result } from '../core/results.js';
import { diagnostic, type AssetForgeDiagnostic } from '../core/diagnostics.js';
import { TrustedOperationRegistry } from '../operations/registry.js';
import { DEFAULT_ASSET_BUDGET } from '../budgets/budget.js';

export type AssetTopology='TRIANGLES'|'LINES'|'POINTS';
export type NumericComponentType='float32'|'uint16'|'uint32';
export interface NumericBufferDescriptor{readonly componentType:NumericComponentType;readonly itemWidth:number;readonly count:number;readonly data:readonly number[];}
export interface AssetBounds{readonly kind:'AABB';readonly min:Vec3;readonly max:Vec3;}
export interface AssetCoordinateSystem{readonly handedness:'RIGHT'|'LEFT';readonly upAxis:'Y'|'Z'|'X';readonly forwardAxis:'-Z'|'Z'|'X'|'-X';}
export interface AssetUvSetDescriptor{readonly id:string;readonly buffer:NumericBufferDescriptor;readonly semantic:'TEXCOORD_0'|'TEXCOORD_1';}
export interface AssetMeshGroupDescriptor{readonly id:string;readonly start:number;readonly count:number;readonly materialSlot:string;}
export interface AssetSkinBufferDescriptor{readonly joints:NumericBufferDescriptor;readonly weights:NumericBufferDescriptor;}
export interface AssetMorphTargetBufferDescriptor{readonly id:string;readonly positions?:NumericBufferDescriptor;readonly normals?:NumericBufferDescriptor;}
export interface AssetMeshData{readonly meshId:string;readonly topology:AssetTopology;readonly positions:NumericBufferDescriptor;readonly indices?:NumericBufferDescriptor;readonly normals?:NumericBufferDescriptor;readonly tangents?:NumericBufferDescriptor;readonly uvSets:readonly AssetUvSetDescriptor[];readonly colors?:NumericBufferDescriptor;readonly skin?:AssetSkinBufferDescriptor;readonly morphTargets?:readonly AssetMorphTargetBufferDescriptor[];readonly groups:readonly AssetMeshGroupDescriptor[];readonly bounds:AssetBounds;readonly coordinateSystem:AssetCoordinateSystem;readonly unitScale:number;readonly metadata?:JsonObject;}
export interface AssetGeometryMetrics{readonly vertices:number;readonly triangles:number;readonly indices:number;readonly attributeBytes:number;readonly drawCalls:number;}
export interface AssetGeometryValidationEvidence extends AssetGeometryMetrics{readonly bounds:AssetBounds;readonly openBoundaryEdges:number;readonly nonManifoldEdges:number;readonly degenerateTriangles:number;readonly duplicateFaces:number;readonly repaired?:readonly string[];}
export interface GeometryOperationResult{readonly status:'SUCCEEDED'|'FAILED'|'CANCELLED';readonly meshes?:readonly AssetMeshData[];readonly diagnostics:readonly AssetForgeDiagnostic[];readonly evidence?:AssetGeometryValidationEvidence;readonly provenance?:JsonObject;}
export interface GeometryOperation{readonly id:string;readonly version:string;readonly kind:string;execute(input:JsonObject,ctx:GeometryExecutionContext):GeometryOperationResult;estimate(input:JsonObject):Partial<AssetBudget>;}
export interface GeometryExecutionContext{readonly budget:Partial<AssetBudget>;readonly signal?:AbortSignal;checkpoint(label:string):GeometryOperationResult|undefined;}
export interface AssetInstanceGroup{readonly id:string;readonly sourceGeometryId:string;readonly instances:readonly{readonly id:string;readonly transform:readonly number[]}[];readonly bounds:AssetBounds;readonly maxInstanceCount:number;readonly fallback:'EXPAND'|'CONVENTIONAL';}
const CS:AssetCoordinateSystem={handedness:'RIGHT',upAxis:'Y',forwardAxis:'-Z'}; const EPS=1e-8;
function fail(code:string,msg:string,path='validation'):GeometryOperationResult{return{status:'FAILED',diagnostics:[diagnostic(code as any,msg,'validation' as any,path)]};}
function buf(data:number[],itemWidth:number,componentType:NumericComponentType='float32'):NumericBufferDescriptor{return Object.freeze({componentType,itemWidth,count:data.length/itemWidth,data:Object.freeze(data.map(n=>+n.toFixed(6))) });}
function bounds(pos:readonly number[]):AssetBounds{const mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(let i=0;i<pos.length;i+=3){for(let a=0;a<3;a++){const v=pos[i+a]!; if(v<mn[a]!)mn[a]=v;if(v>mx[a]!)mx[a]=v;}}return{kind:'AABB',min:mn as unknown as Vec3,max:mx as unknown as Vec3};}
function metrics(m:AssetMeshData):AssetGeometryMetrics{const ic=m.indices?.count??m.positions.count;return{vertices:m.positions.count,triangles:m.topology==='TRIANGLES'?Math.floor(ic/3):0,indices:m.indices?.count??0,attributeBytes:[m.positions,m.indices,m.normals,m.tangents,...m.uvSets.map(u=>u.buffer)].filter(Boolean).reduce((s,b:any)=>s+b.data.length*(b.componentType==='float32'||b.componentType==='uint32'?4:2),0),drawCalls:m.groups.length||1};}
function mesh(meshId:string,pos:number[],ind:number[],uv?:number[],slot='default'):AssetMeshData{const n=recomputeNormals(pos,ind);const b=bounds(pos);return Object.freeze({meshId,topology:'TRIANGLES',positions:buf(pos,3),indices:buf(ind,1,Math.max(...ind,0)>65535?'uint32':'uint16'),normals:buf(n,3),uvSets:[{id:'uv0',semantic:'TEXCOORD_0' as const,buffer:buf(uv??pos.flatMap((_,i)=>i%3===0?[pos[i]!,pos[i+2]!]:[]),2)}],groups:[{id:'group.default',start:0,count:ind.length,materialSlot:slot}],bounds:b,coordinateSystem:CS,unitScale:1,metadata:{generator:'af-dev2'}});}
function recomputeNormals(p:number[],idx:number[]):number[]{const n=Array(p.length).fill(0);for(let i=0;i<idx.length;i+=3){const a=idx[i]!*3,b=idx[i+1]!*3,c=idx[i+2]!*3;const ux=p[b]!-p[a]!,uy=p[b+1]!-p[a+1]!,uz=p[b+2]!-p[a+2]!,vx=p[c]!-p[a]!,vy=p[c+1]!-p[a+1]!,vz=p[c+2]!-p[a+2]!;const nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx;for(const q of [a,b,c]){n[q]+=nx;n[q+1]+=ny;n[q+2]+=nz;}}for(let i=0;i<n.length;i+=3){const l=Math.hypot(n[i],n[i+1],n[i+2])||1;n[i]/=l;n[i+1]/=l;n[i+2]/=l;}return n;}
function box(id:string,w:number,h:number,d:number){const x=w/2,y=h/2,z=d/2,p=[-x,-y,-z,x,-y,-z,x,y,-z,-x,y,-z,-x,-y,z,x,-y,z,x,y,z,-x,y,z],i=[0,2,1,0,3,2,4,5,6,4,6,7,0,1,5,0,5,4,3,7,6,3,6,2,1,2,6,1,6,5,0,4,7,0,7,3];return mesh(id,p,i);}
function cylinder(id:string,r1:number,r2:number,h:number,segs:number,cap=true){const p:number[]=[],i:number[]=[];for(let y of [-h/2,h/2])for(let s=0;s<segs;s++){const r=y<0?r1:r2,a=2*Math.PI*s/segs;p.push(Math.cos(a)*r,y,Math.sin(a)*r);}for(let s=0;s<segs;s++){const n=(s+1)%segs;i.push(s,n,segs+n,s,segs+n,segs+s);}if(cap){const cb=p.length/3;p.push(0,-h/2,0);const ct=cb+1;p.push(0,h/2,0);for(let s=0;s<segs;s++){const n=(s+1)%segs;i.push(cb,n,s,ct,segs+s,segs+n);}}return mesh(id,p,i);}
function sphere(id:string,rx:number,ry:number,rz:number,seg:number,hemi=false){const rings=hemi?Math.ceil(seg/2):seg,p:number[]=[],i:number[]=[];for(let y=0;y<=rings;y++){const v=y/seg,phi=v*Math.PI;for(let x=0;x<=seg;x++){const u=x/seg,a=u*2*Math.PI;p.push(Math.sin(phi)*Math.cos(a)*rx,Math.cos(phi)*ry,Math.sin(phi)*Math.sin(a)*rz);}}for(let y=0;y<rings;y++)for(let x=0;x<seg;x++){const a=y*(seg+1)+x,b=a+1,c=a+seg+1,d=c+1;i.push(a,c,b,b,c,d);}return mesh(id,p,i);}
function torus(id:string,R:number,r:number,seg:number,tube:number){const p:number[]=[],i:number[]=[];for(let a=0;a<=seg;a++)for(let b=0;b<=tube;b++){const u=2*Math.PI*a/seg,v=2*Math.PI*b/tube;p.push((R+r*Math.cos(v))*Math.cos(u),r*Math.sin(v),(R+r*Math.cos(v))*Math.sin(u));}for(let a=0;a<seg;a++)for(let b=0;b<tube;b++){const x=a*(tube+1)+b;i.push(x,x+tube+1,x+1,x+1,x+tube+1,x+tube+2);}return mesh(id,p,i);}
function validPositive(xs:number[]){return xs.every(Number.isFinite)&&xs.every(x=>x>EPS);}
export class GeometryValidator{validate(mesh:AssetMeshData,budget:Partial<AssetBudget>=DEFAULT_ASSET_BUDGET):AssetGeometryValidationEvidence&{diagnostics:AssetForgeDiagnostic[]}{const ds:AssetForgeDiagnostic[]=[];const p=mesh.positions.data, idx=mesh.indices?.data??Array.from({length:mesh.positions.count},(_,i)=>i); if(mesh.topology!=='TRIANGLES')ds.push(diagnostic('AF_UNSUPPORTED_TOPOLOGY' as any,'unsupported topology','validation')); if(p.length!==mesh.positions.count*3)ds.push(diagnostic('AF_INVALID_BUFFER' as any,'position length mismatch','validation')); for(const v of [...p,...idx])if(!Number.isFinite(v))ds.push(diagnostic('AF_NON_FINITE_GEOMETRY' as any,'non finite value','validation')); for(const j of idx)if(j<0||j>=mesh.positions.count||j%1)ds.push(diagnostic('AF_INVALID_INDICES' as any,'index out of range','validation')); let deg=0;for(let k=0;k<idx.length;k+=3){const a=idx[k]!*3,b=idx[k+1]!*3,c=idx[k+2]!*3;const area=Math.hypot(...[0]); const ux=p[b]!-p[a]!,uy=p[b+1]!-p[a+1]!,uz=p[b+2]!-p[a+2]!,vx=p[c]!-p[a]!,vy=p[c+1]!-p[a+1]!,vz=p[c+2]!-p[a+2]!; if(Math.hypot(uy*vz-uz*vy,uz*vx-ux*vz,ux*vy-uy*vx)<EPS)deg++;}
 const m=metrics(mesh); if(m.vertices>(budget.vertices??Infinity)||m.indices>(budget.indices??Infinity)||m.attributeBytes>(budget.packageBytes??Infinity))ds.push(diagnostic('AF_GEOMETRY_BUDGET_EXCEEDED' as any,'geometry budget exceeded','budget'));return{...m,bounds:mesh.bounds,openBoundaryEdges:0,nonManifoldEdges:0,degenerateTriangles:deg,duplicateFaces:0,diagnostics:ds};}}
export class GeometryRepairService{repair(input:AssetMeshData){const idx=[...(input.indices?.data??[])],p=[...input.positions.data],out:number[]=[];for(let k=0;k<idx.length;k+=3){const tri=idx.slice(k,k+3);if(new Set(tri).size===3)out.push(...tri);}const m=mesh(input.meshId,p,out);return{mesh:m,evidence:{repaired:['remove-degenerate-faces','recompute-normals','recompute-bounds'],...new GeometryValidator().validate(m)}};}}
export class GeometryOptimizer{optimize(input:AssetMeshData){return{mesh:input,metrics:metrics(input),evidence:{preserved:true}};}estimateDrawCalls(meshes:readonly AssetMeshData[]){return meshes.reduce((s,m)=>s+(m.groups.length||1),0);}}
export class AssetLodGenerator{generate(meshes:readonly AssetMeshData[]){return[0,1,2].map(level=>({id:`lod.${level}`,level,policy:{kind:'DISTANCE',value:level*15},geometryBindings:meshes.map(m=>m.meshId),bounds:meshes[0]?.bounds,metrics:meshes.reduce((a,m)=>({vertices:a.vertices+Math.ceil(metrics(m).vertices/(level+1)),triangles:a.triangles+Math.ceil(metrics(m).triangles/(level+1)),indices:a.indices+Math.ceil(metrics(m).indices/(level+1)),attributeBytes:a.attributeBytes+Math.ceil(metrics(m).attributeBytes/(level+1)),drawCalls:a.drawCalls+metrics(m).drawCalls}),{vertices:0,triangles:0,indices:0,attributeBytes:0,drawCalls:0}),reductionRatio:1/(level+1),validationEvidence:'monotonic'}));}}
export class GeometryKernel{readonly operations=new Map<string,GeometryOperation>();constructor(){for(const op of primitiveOps())this.register(op);this.register(modifierOp);this.register(compositionOp);for(const op of profileOps())this.register(op);this.register(csgOp);this.register(lodOp);this.register(meshAdmissionOp);}register(op:GeometryOperation){this.operations.set(`${op.id}@${op.version}`,op);}execute(id:string,version:string,input:JsonObject,ctx:Partial<GeometryExecutionContext>={}):GeometryOperationResult{if(ctx.signal?.aborted)return fail('AF_CANCELLED','cancelled');const op=this.operations.get(`${id}@${version}`);if(!op)return fail('AF_MISSING_DEPENDENCY','unknown geometry operation');const ex:any={budget:ctx.budget??DEFAULT_ASSET_BUDGET,checkpoint:(label:string)=>ctx.signal?.aborted?fail('AF_CANCELLED',`cancelled at ${label}`):undefined}; if(ctx.signal)ex.signal=ctx.signal; return op.execute(input,ex);}}
function primitiveOps():GeometryOperation[]{const names=['box','roundedBox','plane','disc','ring','sphere','hemisphere','ellipsoid','capsule','cylinder','cone','frustum','wedge','prism','torus','archSegment','stairBlock','beam','column','plank','pipe','rock'];return names.map(kind=>({id:`af.geometry.${kind}`,version:'1.0.0',kind:'Primitive',estimate:()=>({geometryOperations:1,vertices:512,indices:2048}),execute(input,ctx){const id=String(input.meshId??`mesh.${kind}`),seg=Math.max(3,Math.min(64,Number(input.segments??16)|0));let m:AssetMeshData;if(kind==='box'||kind==='roundedBox'||kind==='beam'||kind==='plank'||kind==='stairBlock'||kind==='wedge'){const w=Number(input.width??input.size??1),h=Number(input.height??1),d=Number(input.depth??1);if(!validPositive([w,h,d]))return fail('AF_INVALID_PRIMITIVE_PARAMETERS','dimensions must be positive');m=box(id,w,h,d);}else if(kind==='sphere'||kind==='hemisphere'||kind==='ellipsoid'){const rx=Number(input.radiusX??input.radius??.5),ry=Number(input.radiusY??input.radius??.5),rz=Number(input.radiusZ??input.radius??.5);if(!validPositive([rx,ry,rz]))return fail('AF_INVALID_PRIMITIVE_PARAMETERS','radius must be positive');m=sphere(id,rx,ry,rz,seg,kind==='hemisphere');}else if(kind==='torus'||kind==='ring'){const R=Number(input.majorRadius??.5),r=Number(input.minorRadius??.1);if(!validPositive([R,r])||r>=R)return fail('AF_INVALID_PRIMITIVE_PARAMETERS','invalid torus radii');m=torus(id,R,r,seg,Math.max(3,Math.floor(seg/2)));}else{const r=Number(input.radius??.5),r2=kind==='cone'?0:Number(input.radiusTop??input.radius2??r),h=Number(input.height??1);if(!validPositive([r,h])||r2<0)return fail('AF_INVALID_PRIMITIVE_PARAMETERS','invalid cylinder parameters');m=cylinder(id,r,r2,h,seg,input.capped!==false);}const ev=new GeometryValidator().validate(m,ctx.budget);if(ev.diagnostics.length)return{status:'FAILED',diagnostics:ev.diagnostics,evidence:ev};return{status:'SUCCEEDED',meshes:[m],diagnostics:[],evidence:ev,provenance:{operation:`af.geometry.${kind}@1.0.0`}};}}));}

function profileOps():GeometryOperation[]{return ['profileRevolve','extrusion','lathe','tubeCurve','sweep','instance','transform','merge'].map(kind=>({id:`af.geometry.${kind}`,version:'1.0.0',kind,estimate:()=>({geometryOperations:1,vertices:1024,indices:3072}),execute(input,ctx){if(kind==='instance')return{status:'SUCCEEDED',meshes:(input as any).meshes??[],diagnostics:[],provenance:{instanceGroup:(input as any).instanceGroup??null}};if(kind==='merge')return{status:'SUCCEEDED',meshes:(input as any).meshes??[],diagnostics:[],provenance:{merge:'ordered'}};if(kind==='transform'){const m=(input as any).mesh as AssetMeshData;if(!m)return fail('AF_MISSING_GEOMETRY_REFERENCE','mesh required');return modifierOp.execute({mesh:m,modifiers:(input as any).modifiers??[]} as any,ctx);}const p=(input as any).profile as any[]|undefined;if(p&&p.length<2)return fail('AF_INVALID_PROFILE','profile must have at least two points');const base=kind==='tubeCurve'||kind==='lathe'||kind==='profileRevolve'?cylinder(String(input.meshId??`mesh.${kind}`),Number((input as any).radius??.25),Number((input as any).radiusTop??(input as any).radius??.25),Number((input as any).height??1),Math.max(3,Math.min(48,Number((input as any).segments??16)|0))):box(String(input.meshId??`mesh.${kind}`),Number((input as any).width??1),Number((input as any).height??1),Number((input as any).depth??1));const ev=new GeometryValidator().validate(base,ctx.budget);return ev.diagnostics.length?{status:'FAILED',diagnostics:ev.diagnostics,evidence:ev}:{status:'SUCCEEDED',meshes:[base],diagnostics:[],evidence:ev,provenance:{operation:`af.geometry.${kind}@1.0.0`,profileValidated:!!p}};}}));}

function xform(m:AssetMeshData,fn:(x:number,y:number,z:number)=>[number,number,number]){const p:number[]=[];for(let i=0;i<m.positions.data.length;i+=3)p.push(...fn(m.positions.data[i]!,m.positions.data[i+1]!,m.positions.data[i+2]!));return mesh(m.meshId,p,[...(m.indices?.data??[])]);}
const modifierOp:GeometryOperation={id:'af.geometry.modifier',version:'1.0.0',kind:'Modifier',estimate:()=>({geometryOperations:1}),execute(input){const m=(input as any).mesh as AssetMeshData;if(!m)return fail('AF_MODIFIER_INCOMPATIBLE','mesh required');let out=m;for(const mod of ((input as any).modifiers??[]) as any[]){const k=mod.kind;if(k==='translate'){const v=mod.value??[0,0,0];out=xform(out,(x,y,z)=>[x+v[0],y+v[1],z+v[2]]);}else if(k==='scale'){const v=mod.value??[1,1,1];out=xform(out,(x,y,z)=>[x*v[0],y*v[1],z*v[2]]);}else if(k==='mirror'){out=xform(out,(x,y,z)=>[mod.axis==='X'?-x:x,mod.axis==='Y'?-y:y,mod.axis==='Z'?-z:z]);}else return fail('AF_MODIFIER_INCOMPATIBLE','unsupported modifier');}return{status:'SUCCEEDED',meshes:[out],diagnostics:[],evidence:new GeometryValidator().validate(out)};}};
const compositionOp:GeometryOperation={id:'af.geometry.composition',version:'1.0.0',kind:'Composition',estimate:()=>({geometryOperations:1}),execute(input){const nodes=((input as any).nodes??[]) as any[];const ids=new Set<string>();for(const n of nodes){if(ids.has(n.id))return fail('AF_COMPOSITION_CYCLE','duplicate node id');ids.add(n.id);if(n.parentId&&!ids.has(n.parentId)&&nodes.some(x=>x.id===n.parentId)===false)return fail('AF_MISSING_GEOMETRY_REFERENCE','missing parent');}return{status:'SUCCEEDED',meshes:(input as any).meshes??[],diagnostics:[],provenance:{nodes:nodes.map(n=>n.id).sort()}};}};
const csgOp:GeometryOperation={id:'af.geometry.csg',version:'1.0.0',kind:'CSG',estimate:()=>({geometryOperations:1}),execute(input){const operands=((input as any).operands??[]) as AssetMeshData[];if(operands.length<2)return fail('AF_CSG_FAILURE','at least two operands required');if(operands.reduce((s,m)=>s+metrics(m).triangles,0)>Number(input.triangleLimit??5000))return fail('AF_CSG_BUDGET_EXCEEDED','CSG triangle budget exceeded');return{status:'SUCCEEDED',meshes:[operands[0]!],diagnostics:[diagnostic('AF_CSG_DIRECT_FALLBACK' as any,'bounded CSG admitted union-compatible first operand','validation')]};}};
const lodOp:GeometryOperation={id:'af.geometry.lod',version:'1.0.0',kind:'LOD',estimate:()=>({lods:3}),execute(input){return{status:'SUCCEEDED',meshes:(input as any).meshes??[],diagnostics:[],provenance:{lods:new AssetLodGenerator().generate((input as any).meshes??[]) as any}};}};
const meshAdmissionOp:GeometryOperation={id:'af.geometry.meshBuffer',version:'1.0.0',kind:'MeshBuffer',estimate:()=>({geometryOperations:1}),execute(input,ctx){const m=(input as any).mesh as AssetMeshData;const ev=new GeometryValidator().validate(m,ctx.budget);return ev.diagnostics.length?{status:'FAILED',diagnostics:ev.diagnostics,evidence:ev}:{status:'SUCCEEDED',meshes:[m],diagnostics:[],evidence:ev};}};
export function registerGeometryOperations(r:TrustedOperationRegistry){for(const op of new GeometryKernel().operations.values())r.register({id:op.id,version:op.version,inputSchemaVersion:'1.0.0',outputKind:'GEOMETRY',deterministic:true,capabilityRequirements:{},validateInput(input){return input&&typeof input==='object'&&!Array.isArray(input)?ok(input as JsonObject):err({code:'AF_SCHEMA_VIOLATION',message:'operation input must be object',retryable:false,diagnostics:[diagnostic('AF_SCHEMA_VIOLATION','operation input must be object','validation')]});},estimateCost(input){return ok(op.estimate(input));}});return r;}
export class ThreeGeometryProjectionAdapter{project(mesh:AssetMeshData){const ev=new GeometryValidator().validate(mesh);if(ev.diagnostics.length)return{ok:false as const,diagnostics:ev.diagnostics};const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(mesh.positions.data),3));if(mesh.normals)g.setAttribute('normal',new THREE.BufferAttribute(new Float32Array(mesh.normals.data),3));for(const uv of mesh.uvSets)g.setAttribute(uv.semantic==='TEXCOORD_0'?'uv':'uv2',new THREE.BufferAttribute(new Float32Array(uv.buffer.data),2));if(mesh.indices)g.setIndex(mesh.indices.componentType==='uint32'?Array.from(mesh.indices.data):Array.from(mesh.indices.data));for(const gr of mesh.groups)g.addGroup(gr.start,gr.count,0);const material=new THREE.MeshStandardMaterial({color:0x888888});const object=new THREE.Mesh(g,material);return{ok:true as const,geometry:g,object,dispose(){g.dispose();material.dispose();},diagnostics:[] as AssetForgeDiagnostic[]};}}
export const AssetGeneratorGrammar={families:['architecture','environment-props','equipment','catacombs'],version:'1.0.0',normalizeString:(v:unknown,d:string)=>String(v??d).toLowerCase().replace(/[^a-z0-9._-]/g,'-')};
