import type { Result } from '../core/results.js';
import type { AssetForgeDiagnostic } from '../core/diagnostics.js';

export type JsonPrimitive = null | boolean | number | string;
export type JsonValue = JsonPrimitive | readonly JsonValue[] | JsonObject;
export type JsonObject = { readonly [key: string]: JsonValue };
export type StableId = string & { readonly __stableId: unique symbol };
export type SemanticVersion = string & { readonly __semanticVersion: unique symbol };
export type Vec2 = readonly [number, number];
export type Vec3 = readonly [number, number, number];
export type Quaternion = readonly [number, number, number, number];
export interface TransformDescriptor { readonly position: Vec3; readonly rotation: Quaternion; readonly scale: Vec3; }
export interface BoundsDescriptor { readonly kind: 'AABB' | 'SPHERE'; readonly min?: Vec3; readonly max?: Vec3; readonly center?: Vec3; readonly radius?: number; }
export interface ColorDescriptor { readonly colorSpace: 'SRGB' | 'LINEAR'; readonly rgba: readonly [number, number, number, number]; }
export interface NumericRange { readonly min: number; readonly max: number; }
export interface UnitDeclaration { readonly unit: 'METER' | 'CENTIMETER' | 'MILLIMETER'; readonly metersPerUnit: number; }
export interface CoordinateSystemDeclaration { readonly handedness: 'LEFT' | 'RIGHT'; readonly upAxis: 'X' | 'Y' | 'Z'; readonly forwardAxis: 'X' | 'Y' | 'Z' | '-X' | '-Y' | '-Z'; }
export type AssetRecipeOrigin = 'PROCEDURAL' | 'REFERENCE' | 'HYBRID' | 'IMPORTED';
export interface AssetRecipeMetadata { readonly name?: string; readonly labels?: readonly string[]; readonly authoringTool?: string; readonly audit?: JsonObject; }
export interface AssetReferenceDescriptor { readonly id: StableId; readonly kind: 'PACKAGE' | 'TEXTURE' | 'MATERIAL' | 'GEOMETRY' | 'MANIFEST'; readonly packageId?: string; readonly version?: string; readonly checksum?: string; readonly uri?: string; }
export interface AssetOperationRef { readonly operationId: string; readonly operationVersion: string; readonly parameters: JsonObject; }
export type AssetTopologyIntent = 'TRIANGLES' | 'QUADS' | 'LINES' | 'POINTS' | 'VOLUME';
export interface GeometryCommon { readonly id: StableId; readonly operation: AssetOperationRef; readonly vertexBudget: number; readonly indexBudget: number; readonly topology: AssetTopologyIntent; readonly uv: 'NONE' | 'PLANAR' | 'TRIPLANAR' | 'GENERATED' | 'PRESERVE'; readonly normals: 'NONE' | 'FLAT' | 'SMOOTH' | 'PRESERVE'; readonly tangents?: 'NONE' | 'GENERATE' | 'PRESERVE'; readonly bounds: BoundsDescriptor; readonly coordinateSystem: CoordinateSystemDeclaration; readonly unitScale: UnitDeclaration; }
export type AssetGeometryDescriptor =
 | (GeometryCommon & { readonly kind: 'PRIMITIVE' | 'PROFILE_REVOLVE' | 'EXTRUSION' | 'LATHE' | 'TUBE_CURVE' | 'INSTANCE' | 'COMPOSITION_GRAPH' | 'BOUNDED_MODIFIER' | 'CONTROLLED_CSG' | 'SDF_ASSEMBLY' })
 | (GeometryCommon & { readonly kind: 'MESH_BUFFER'; readonly attributes: readonly string[]; readonly encodedBufferRef: string })
 | (GeometryCommon & { readonly kind: 'EXTERNAL_PACKAGE_REF'; readonly referenceId: StableId });
export interface MaterialTextureRef { readonly kind: 'PACKAGE_TEXTURE' | 'GENERATED_TEXTURE'; readonly referenceId?: StableId; readonly generator?: AssetOperationRef; readonly channel?: string; }
interface MaterialCommon { readonly id: StableId; readonly name?: string; readonly parameters: JsonObject; readonly textures?: readonly MaterialTextureRef[]; }
export type AssetMaterialDescriptor = MaterialCommon & ({ readonly family: 'STANDARD_PBR' | 'UNLIT' | 'TRANSPARENT_CUTOUT' | 'EMISSIVE' | 'LAYERED' | 'TRIPLANAR' | 'SDF_INFLUENCE' | 'ANIMATED_CHANNEL' } | { readonly family: 'TRUSTED_SHADER'; readonly shaderFamilyId: string; readonly shaderFamilyVersion: string });
export interface AssetComponentDescriptor { readonly id: StableId; readonly parentId?: StableId; readonly children?: readonly StableId[]; readonly transform: TransformDescriptor; readonly pivot?: Vec3; readonly anchor?: Vec3; readonly visible: boolean; readonly renderIntent: 'OPAQUE' | 'TRANSPARENT' | 'SHADOW_ONLY' | 'COLLISION_ONLY' | 'HIDDEN'; readonly geometry?: AssetGeometryDescriptor; readonly materialBindings: readonly { readonly slot: string; readonly materialId: StableId }[]; readonly instanceOf?: StableId; readonly instanceCount?: number; readonly destructibleGroupId?: StableId; readonly tags?: readonly string[]; }
export interface AssetRigDescriptor { readonly id: StableId; readonly kind: 'SKELETAL' | 'PROCEDURAL'; readonly bones: readonly { readonly id: StableId; readonly parentId?: StableId; readonly bind: TransformDescriptor; readonly axis?: Vec3; readonly limits?: readonly NumericRange[] }[]; readonly skins?: readonly { readonly componentId: StableId; readonly joints: readonly StableId[]; readonly maxInfluences: number }[]; readonly attachments?: readonly { readonly boneId: StableId; readonly socketId: StableId }[]; readonly morphTargets?: readonly { readonly id: StableId; readonly componentId: StableId }[]; readonly capabilities: readonly string[]; readonly compatibility: JsonObject; }
export type AnimationStateSemantic = 'IDLE' | 'LOCOMOTION' | 'ATTACK' | 'ABILITY' | 'HIT' | 'STUN' | 'KNOCKBACK' | 'DEATH' | 'CUSTOM';
export interface AssetAnimationSetDescriptor { readonly clips: readonly { readonly id: StableId; readonly kind: 'BAKED' | 'PROCEDURAL'; readonly durationSeconds: number; readonly loop: boolean; readonly tracks: readonly { readonly target: StableId; readonly property: string; readonly keyCount: number }[]; readonly events?: readonly { readonly timeSeconds: number; readonly id: StableId; readonly payload?: JsonObject }[] }[]; readonly graph?: { readonly states: readonly { readonly id: StableId; readonly semantic: AnimationStateSemantic; readonly clipId?: StableId }[]; readonly transitions: readonly { readonly from: StableId; readonly to: StableId; readonly condition?: JsonObject }[]; readonly parameters: readonly { readonly id: StableId; readonly type: 'NUMBER' | 'BOOLEAN' | 'TRIGGER' }[] }; readonly fixedStepHz?: number; readonly rootMotion: 'NONE' | 'EXTRACT' | 'APPLY'; readonly runtimeRequirements: readonly string[]; }
export type ColliderShape = { readonly kind: 'BALL'; readonly radius: number } | { readonly kind: 'CUBOID'; readonly halfExtents: Vec3 } | { readonly kind: 'CAPSULE' | 'CYLINDER' | 'CONE'; readonly radius: number; readonly halfHeight: number } | { readonly kind: 'CONVEX_HULL'; readonly points: readonly Vec3[] } | { readonly kind: 'COMPOUND'; readonly children: readonly ColliderShape[] } | { readonly kind: 'HEIGHTFIELD'; readonly rows: number; readonly columns: number; readonly heightsRef: string } | { readonly kind: 'TRIMESH_STATIC'; readonly geometryId: StableId };
export interface AssetPhysicsDescriptor { readonly rigidBodies: readonly { readonly id: StableId; readonly componentId?: StableId; readonly bodyType: 'STATIC' | 'DYNAMIC' | 'KINEMATIC'; readonly transform: TransformDescriptor; readonly massPolicy: 'DENSITY' | 'MASS' | 'AUTO'; readonly mass?: number; readonly density?: number; readonly ccd?: boolean }[]; readonly colliders: readonly { readonly id: StableId; readonly bodyId: StableId; readonly shape: ColliderShape; readonly sensor?: boolean; readonly friction?: number; readonly restitution?: number; readonly collisionGroups?: number; readonly solverGroups?: number; readonly materialId?: StableId }[]; readonly joints?: readonly { readonly id: StableId; readonly a: StableId; readonly b: StableId; readonly kind: 'FIXED' | 'REVOLUTE' | 'PRISMATIC' | 'SPHERICAL' }[]; readonly hitboxes?: readonly { readonly id: StableId; readonly colliderId: StableId }[]; readonly hurtboxes?: readonly { readonly id: StableId; readonly colliderId: StableId }[]; readonly materials?: readonly { readonly id: StableId; readonly friction: number; readonly restitution: number }[]; readonly stabilityTests?: JsonObject; }
export interface AssetSocketDescriptor { readonly id: StableId; readonly kind: 'ATTACHMENT' | 'HAND_GRIP' | 'PROJECTILE_ORIGIN' | 'VFX_ORIGIN' | 'AUDIO_ORIGIN' | 'LOOT_POINT' | 'INTERACTION_ANCHOR' | 'DOOR_PIVOT' | 'AI_TARGET' | 'NAVIGATION' | 'SUPPORT_POLYGON'; readonly target: { readonly componentId?: StableId; readonly boneId?: StableId; readonly transformId?: StableId }; readonly transform: TransformDescriptor; readonly dimensions?: Vec3; }
export interface AssetInteractionDescriptor { readonly id: StableId; readonly kind: 'USE' | 'OPEN' | 'GRAB' | 'ATTACK' | 'DESTRUCTIBLE' | 'HITBOX_BINDING' | 'HURTBOX_BINDING' | 'CUSTOM'; readonly socketId?: StableId; readonly componentId?: StableId; readonly physicsId?: StableId; readonly semantics: JsonObject; }
export interface AssetLodDescriptor { readonly id: StableId; readonly level: number; readonly policy: { readonly kind: 'SCREEN_SIZE' | 'DISTANCE'; readonly value: number }; readonly geometrySubstitutions?: Readonly<Record<string, StableId>>; readonly materialSubstitutions?: Readonly<Record<string, StableId>>; readonly rigReduction?: JsonObject; readonly animationReduction?: JsonObject; readonly physicsReduction?: JsonObject; readonly renderMode: 'CONVENTIONAL' | 'INSTANCED' | 'CROWD' | 'IMPOSTOR'; }
export interface AssetForgeRecipe { readonly schemaVersion: string; readonly recipeId: string; readonly origin: AssetRecipeOrigin; readonly generator: { readonly id: string; readonly version: string; readonly familyId: string; readonly profileId?: string }; readonly seed: string; readonly parameters: Readonly<Record<string, JsonValue>>; readonly components: readonly AssetComponentDescriptor[]; readonly materials: readonly AssetMaterialDescriptor[]; readonly rig?: AssetRigDescriptor; readonly animations?: AssetAnimationSetDescriptor; readonly physics?: AssetPhysicsDescriptor; readonly sockets: readonly AssetSocketDescriptor[]; readonly interactions: readonly AssetInteractionDescriptor[]; readonly lods: readonly AssetLodDescriptor[]; readonly references?: readonly AssetReferenceDescriptor[]; readonly metadata: AssetRecipeMetadata; }
export interface AssetRuntimeCapabilities { readonly webgl: 1 | 2; readonly maxTextureSize: number; readonly maxVertices: number; readonly floatTextures: boolean; readonly maxSkinJoints: number; readonly instancing: boolean; readonly sdf: boolean; readonly rapier: boolean; readonly animation: 'NONE' | 'BAKED' | 'GRAPH' | 'PROCEDURAL'; readonly glb: boolean; }
export type AssetCapabilityResolution = { readonly status: 'SUPPORTED'; readonly capabilities: AssetRuntimeCapabilities; readonly notes: readonly string[] } | { readonly status: 'DEGRADED'; readonly capabilities: AssetRuntimeCapabilities; readonly degradations: readonly string[] } | { readonly status: 'REJECTED'; readonly missing: readonly string[]; readonly diagnostics: readonly AssetForgeDiagnostic[] };
export interface AssetBudget { readonly components: number; readonly hierarchyDepth: number; readonly geometryOperations: number; readonly vertices: number; readonly indices: number; readonly instances: number; readonly bones: number; readonly skinInfluences: number; readonly animationClips: number; readonly animationTracks: number; readonly animationKeys: number; readonly animationDurationSeconds: number; readonly colliders: number; readonly joints: number; readonly materials: number; readonly textures: number; readonly textureDimension: number; readonly textureDecodedBytes: number; readonly lods: number; readonly externalDependencies: number; readonly packageBytes: number; readonly workUnits: number; readonly diagnostics: number; readonly inputDepth: number; readonly collectionSize: number; }
export interface AssetForgeFailure { readonly code: string; readonly message: string; readonly diagnostics: readonly AssetForgeDiagnostic[]; readonly retryable: boolean; }
export type AssetGenerationStage = 'ADMISSION' | 'MIGRATION' | 'NORMALIZATION' | 'RESOLUTION' | 'CAPABILITY' | 'GENERATION' | 'GEOMETRY' | 'MATERIAL' | 'RIG' | 'ANIMATION' | 'PHYSICS' | 'LOD' | 'VALIDATION' | 'PACKAGING' | 'INTEGRITY';
export interface AssetIntegrityRecord { readonly algorithm: 'sha256'; readonly serializationVersion: string; readonly digest: string; readonly identityDigest: string; }
export interface AssetProvenance { readonly recipeId: string; readonly originalSchemaVersion: string; readonly normalizedConfigurationDigest: string; readonly generator: { readonly id: string; readonly version: string }; readonly trustedOperations: readonly { readonly id: string; readonly version: string }[]; readonly rootSeed: string; readonly seedDerivationVersion: string; readonly dependencies: readonly { readonly id: string; readonly checksum?: string }[]; readonly migrationPath: readonly string[]; readonly validationProfile: string; readonly runtimeContractVersion: string; readonly compatibility: JsonObject; }
export interface GeneratedAssetDefinition { readonly contractVersion: string; readonly recipe: AssetForgeRecipe; readonly components: readonly AssetComponentDescriptor[]; readonly geometries: readonly AssetGeometryDescriptor[]; readonly materials: readonly AssetMaterialDescriptor[]; readonly rig?: AssetRigDescriptor; readonly animations?: AssetAnimationSetDescriptor; readonly physics?: AssetPhysicsDescriptor; readonly sockets: readonly AssetSocketDescriptor[]; readonly interactions: readonly AssetInteractionDescriptor[]; readonly lods: readonly AssetLodDescriptor[]; readonly dependencies: readonly AssetReferenceDescriptor[]; readonly capabilities: AssetCapabilityResolution; readonly diagnostics: readonly AssetForgeDiagnostic[]; readonly validation: { readonly profile: string; readonly passed: boolean; readonly diagnostics: readonly AssetForgeDiagnostic[] }; readonly provenance: AssetProvenance; readonly integrity: AssetIntegrityRecord; }
export type AssetGenerationSuccess<T = GeneratedAssetDefinition> = { readonly status: 'SUCCEEDED'; readonly asset: T; readonly diagnostics: readonly AssetForgeDiagnostic[] };
export type AssetGenerationFailure = { readonly status: 'FAILED' | 'CANCELLED'; readonly failure: AssetForgeFailure; readonly diagnostics: readonly AssetForgeDiagnostic[] };
export type AssetGenerationResult<T = GeneratedAssetDefinition> = AssetGenerationSuccess<T> | AssetGenerationFailure;
export interface AssetGenerationRequest { readonly recipe: unknown; readonly targetSchemaVersion?: string; readonly capabilities?: Partial<AssetRuntimeCapabilities>; readonly budget?: Partial<AssetBudget>; }
export interface AssetGenerationOptions { readonly signal?: AbortSignal; readonly onProgress?: (event: { readonly stage: AssetGenerationStage; readonly completedWork: number; readonly totalWork?: number }) => void; readonly registry?: import('../generators/registry.js').AssetGeneratorRegistry; readonly operations?: import('../operations/registry.js').TrustedOperationRegistry; readonly migrations?: import('../migrations/registry.js').AssetRecipeMigrationRegistry; }
export interface AssetGenerationContext<TConfig extends JsonObject = JsonObject> { readonly recipe: AssetForgeRecipe; readonly config: TConfig; readonly random: import('../random/deterministicRandom.js').DeterministicRandomContext; readonly budget: import('../budgets/budget.js').AssetBudgetReservation; readonly operations: import('../operations/registry.js').TrustedOperationRegistry; readonly signal?: AbortSignal; readonly progress: (stage: AssetGenerationStage, work?: number) => void; }
export interface AssetGeneratorDescriptor { readonly id: string; readonly version: string; readonly familyIds: readonly string[]; readonly supportedOrigins: readonly AssetRecipeOrigin[]; readonly capabilities: Partial<AssetRuntimeCapabilities>; readonly requiredTrustedOperations: readonly { readonly id: string; readonly version: string }[]; readonly inputSchemaVersion: string; readonly outputContractVersion: string; readonly budgetLimits: AssetBudget; readonly migrationCompatibility: readonly string[]; readonly runtimeRequirements: Partial<AssetRuntimeCapabilities>; }
export interface AssetGeneratorPack<TConfig extends JsonObject = JsonObject, TAsset extends GeneratedAssetDefinition = GeneratedAssetDefinition> { readonly descriptor: AssetGeneratorDescriptor; normalizeConfig(input: unknown): Result<TConfig, AssetForgeFailure>; generate(context: AssetGenerationContext<TConfig>): Promise<AssetGenerationResult<TAsset>>; }
export interface TrustedOperationDescriptor { readonly id: string; readonly version: string; readonly inputSchemaVersion: string; readonly outputKind: 'GEOMETRY' | 'MATERIAL' | 'TEXTURE' | 'SDF' | 'UTILITY'; readonly deterministic: true; readonly capabilityRequirements: Partial<AssetRuntimeCapabilities>; estimateCost(input: JsonObject): Result<Partial<AssetBudget>, AssetForgeFailure>; validateInput(input: unknown): Result<JsonObject, AssetForgeFailure>; }
export interface AssetRecipeMigration { readonly id: string; readonly sourceVersion: string; readonly targetVersion: string; migrate(input: JsonObject): Result<JsonObject, AssetForgeFailure>; }
