import * as THREE from 'three';
import type { DungeonRenderInput } from '../renderInput.js';
import { createMaterials, type DungeonMaterials } from './materials.js';
import { buildEnvironmentalPropViews, environmentalRegistryEntry, type EnvironmentalPropView } from '../environmentalProps.js';
import { buildGameplayPlacementViews, DEFAULT_GAMEPLAY_OVERLAY_STATE, GAMEPLAY_CATEGORY_STYLES, type GameplayPlacementCategory, type GameplayPlacementView, summarizeGameplayPlacement } from '../gameplayPresentation.js';
import { boundaryTransform, DOOR_GEOMETRY, FLOOR_GEOMETRY, MARKER_GEOMETRY, tileToWorld, WALL_GEOMETRY } from './geometry.js';
import { QUALITY_PROFILES } from './quality.js';
import { SafeAssetLoader } from './assetLoader.js';
import type { DungeonRendererContract, OverlayState, RendererOptions, RendererStats } from './types.js';

/** Coordinate mapping: tile X => world X, tile Y => world Z, tile level/elevation => world Y. Boundaries use n/e/s/w side normals and rotate wall length around world Y. */
export class ThreeDungeonRenderer implements DungeonRendererContract{private renderer?:THREE.WebGLRenderer;private scene=new THREE.Scene();private camera=new THREE.OrthographicCamera(-20,20,14,-14,.1,2000);private container?:HTMLElement;private raf=0;private dungeonGroup=new THREE.Group();private overlayGroup=new THREE.Group();private materials:DungeonMaterials=createMaterials();private owned:(THREE.Object3D|THREE.Material|THREE.BufferGeometry)[]=[];private options?:RendererOptions;private overlayState:OverlayState={enabled:{},preset:'all'};private assets=new SafeAssetLoader();private stats:RendererStats={objects:0,geometries:0,materials:0,drawCalls:0,triangles:0,generationToken:0,assetErrors:[]};private listeners:Array<()=>void>=[];private dragging=false;private moved=false;private last={x:0,y:0};private gameplayGroup=new THREE.Group();private gameplayMarkerGroup=new THREE.Group();private gameplayAreaGroup=new THREE.Group();private gameplayViews=new Map<string,GameplayPlacementView>();private gameplayObjects=new Map<string,THREE.Object3D>();private selectedGameplayId:string|undefined;private environmentalGroup=new THREE.Group();private environmentalViews=new Map<string,EnvironmentalPropView>();private environmentalObjects=new Map<string,THREE.Object3D>();private selectedEnvironmentalId:string|undefined;
async mount(container:HTMLElement){this.container=container; this.scene.background=new THREE.Color(0x07080d); this.scene.fog=new THREE.Fog(0x07080d,70,190); this.camera.position.set(35,42,35); this.camera.lookAt(0,0,0); this.scene.add(new THREE.HemisphereLight(0xb7c7ff,0x1e1720,1.5)); const key=new THREE.DirectionalLight(0xffe0a8,1.4); key.position.set(20,45,10); this.scene.add(key); this.dungeonGroup.name='dungeon-records'; this.overlayGroup.name='production-overlays'; this.gameplayGroup.name='gameplay.visualization'; this.environmentalGroup.name='environmental.props'; this.gameplayMarkerGroup.name='gameplay.markers'; this.gameplayAreaGroup.name='gameplay.areas'; this.gameplayGroup.add(this.gameplayAreaGroup,this.gameplayMarkerGroup); this.scene.add(this.dungeonGroup,this.environmentalGroup,this.gameplayGroup,this.overlayGroup); this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); this.renderer.outputColorSpace=THREE.SRGBColorSpace; container.replaceChildren(this.renderer.domElement); this.installControls(this.renderer.domElement); this.resize(container.clientWidth||800,container.clientHeight||500,(globalThis as any).devicePixelRatio||1); this.loop();}
async render(input:DungeonRenderInput,options:RendererOptions){this.options=options; this.disposeDungeon(); const token=this.assets.beginGeneration(); this.stats={objects:0,geometries:0,materials:Object.keys(this.materials).length,drawCalls:0,triangles:0,generationToken:token,assetErrors:[]}; this.applyQuality(options); this.buildFloors(input); this.buildBoundaries(input); await this.buildConstruction(input,token); this.buildEnvironmentalProps(input); this.buildGameplay(input); this.buildOverlays(input); this.frameInput(input); this.applyAnimation(options);}
updatePresentation(options:Partial<RendererOptions>){this.options={...(this.options??options as RendererOptions),...options}; if(this.options)this.applyQuality(this.options); this.applyWallFade();}
setOverlayState(state:OverlayState){this.overlayState=state; for(const o of this.overlayGroup.children)o.visible=state.enabled[o.name]??true; this.applyGameplayOverlayState(); this.applyEnvironmentalOverlayState();}
selectGameplayPlacement(id?:string){this.selectedGameplayId=id&&this.gameplayViews.has(id)?id:undefined; this.applyGameplaySelection();}
selectEnvironmentalProp(id?:string){this.selectedEnvironmentalId=id&&this.environmentalViews.has(id)?id:undefined; this.applyEnvironmentalSelection();}
getSelectedEnvironmentalProp(){const v=this.selectedEnvironmentalId?this.environmentalViews.get(this.selectedEnvironmentalId):undefined; return v?{placementId:v.id,recordId:v.recordId,category:v.category,assetRegistryId:v.assetRegistryId,ownerType:v.ownerType,ownerId:v.ownerId,surface:v.surface,position:v.position,rotation:v.orientation,scale:v.scale,compositionGroupId:v.compositionGroupId,deterministicVariant:v.deterministicVariant,validationState:v.validationState,warnings:v.warnings,prototypeGeometryFamily:v.prototypeGeometryFamily,assetRequirementId:v.assetRequirementId,prototypeStatus:'procedural-dtd-d2',authoredStatus:'required-dtd-d3',description:v.description}:undefined;}
getSelectedGameplayPlacement(){const v=this.selectedGameplayId?this.gameplayViews.get(this.selectedGameplayId):undefined; return v?summarizeGameplayPlacement(v):undefined;}
resize(width:number,height:number,pixelRatio:number){if(!this.renderer)return; const q=QUALITY_PROFILES[this.options?.quality??'medium']; this.renderer.setPixelRatio(Math.min(pixelRatio,q.pixelRatioCap)); this.renderer.setSize(Math.max(1,width),Math.max(1,height),false); const aspect=width/Math.max(1,height), span=34; this.camera.left=-span*aspect; this.camera.right=span*aspect; this.camera.top=span; this.camera.bottom=-span; this.camera.updateProjectionMatrix();}
disposeDungeon(){this.assets.beginGeneration(); for(const o of [...this.dungeonGroup.children,...this.overlayGroup.children,...this.gameplayGroup.children,...this.environmentalGroup.children]){o.removeFromParent(); this.disposeObject(o);} this.dungeonGroup.clear(); this.overlayGroup.clear(); this.gameplayGroup.clear(); this.environmentalGroup.clear(); this.gameplayMarkerGroup=new THREE.Group(); this.gameplayAreaGroup=new THREE.Group(); this.gameplayMarkerGroup.name='gameplay.markers'; this.gameplayAreaGroup.name='gameplay.areas'; this.gameplayGroup.add(this.gameplayAreaGroup,this.gameplayMarkerGroup); this.gameplayViews.clear(); this.gameplayObjects.clear(); this.environmentalViews.clear(); this.environmentalObjects.clear(); this.selectedGameplayId=undefined; this.selectedEnvironmentalId=undefined; this.owned=[]; this.stats.objects=0;}
dispose(){((globalThis as any).cancelAnimationFrame??(()=>undefined))(this.raf); for(const off of this.listeners)off(); this.listeners=[]; this.disposeDungeon(); Object.values(this.materials).forEach(m=>m.dispose()); this.assets.dispose(); this.renderer?.dispose(); this.container?.replaceChildren();}
getStats(){const r=this.renderer?.info.render; return {...this.stats,drawCalls:r?.calls??this.stats.drawCalls,triangles:r?.triangles??this.stats.triangles,objects:this.dungeonGroup.children.length+this.overlayGroup.children.length+this.gameplayGroup.children.length+this.environmentalGroup.children.length};}
private add(o:THREE.Object3D,group=this.dungeonGroup){group.add(o); this.stats.objects++; return o;}
private buildFloors(input:DungeonRenderInput){const layers=input.geometry.tileLayers.layers.find(l=>l.id==='tileType'); const raw=layers?Uint8Array.from(atob(layers.base64), c => c.charCodeAt(0)):new Uint8Array(); const w=input.geometry.tileLayers.width; const roomCount=raw.filter(v=>v===1||v===3).length, corCount=raw.filter(v=>v===2).length; const room=new THREE.InstancedMesh(FLOOR_GEOMETRY,this.materials.room,roomCount); room.name='rooms.floor'; const cor=new THREE.InstancedMesh(FLOOR_GEOMETRY,this.materials.corridor,corCount); cor.name='corridors.floor'; let ri=0,ci=0; const m=new THREE.Matrix4(); raw.forEach((v,i)=>{if(!v)return; const x=i%w, y=Math.floor(i/w), p=tileToWorld(x,y,0); p.y=-.04; m.makeTranslation(p.x,p.y,p.z); if(v===1||v===3)room.setMatrixAt(ri++,m); else if(v===2)cor.setMatrixAt(ci++,m);}); this.add(room); this.add(cor);}
private buildBoundaries(input:DungeonRenderInput){const uniq=new Set<string>(); const walls=input.geometry.boundaries.filter(b=>!b.boundaryType.includes('door')); const doors=input.geometry.boundaries.filter(b=>b.boundaryType.includes('door')); const wm=new THREE.InstancedMesh(WALL_GEOMETRY,this.materials.wall,walls.length); wm.name='walls.boundary'; const dm=new THREE.InstancedMesh(DOOR_GEOMETRY,this.materials.doorway,doors.length); dm.name='doorways.boundary'; const mx=new THREE.Matrix4(); let wi=0,di=0; for(const b of [...walls,...doors]){const key=`${b.tile.x},${b.tile.y},${b.side},${b.boundaryType}`; if(uniq.has(key))continue; uniq.add(key); const t=boundaryTransform(b.tile,b.side); mx.compose(t.position,new THREE.Quaternion().setFromEuler(new THREE.Euler(0,t.rotationY,0)),new THREE.Vector3(1,1,1)); if(b.boundaryType.includes('door'))dm.setMatrixAt(di++,mx); else wm.setMatrixAt(wi++,mx);} this.add(wm); this.add(dm);}
private async buildConstruction(input:DungeonRenderInput,token:number){const group=new THREE.Group(); group.name='construction.records'; for(const r of input.construction.records){const load=await this.assets.load(r.resolvedAssetId??r.requestedAssetFamily,undefined,token); if(load.stale)return; if(!load.ok)this.stats.assetErrors.push(`${r.id}: ${load.error}`); const mesh=new THREE.Mesh(new THREE.BoxGeometry(.55,.55,.55),load.ok?this.materials.fallback:this.materials.fallback); mesh.name=`construction.${r.id}`; mesh.position.set(r.transform.position.x,.28,r.transform.position.y); group.add(mesh);} this.add(group);}

private buildEnvironmentalProps(input:DungeonRenderInput){const views=buildEnvironmentalPropViews(input.construction.records); this.stats.environmentalProps=views.length; let renderable=0; for(const view of views){this.environmentalViews.set(view.id,view); if(view.validationState==='invalid')continue; const obj=this.createEnvironmentalPrototype(view); this.environmentalGroup.add(obj); this.environmentalObjects.set(view.id,obj); renderable++;} this.stats.environmentalRenderableProps=renderable; this.applyEnvironmentalOverlayState(); this.applyEnvironmentalSelection();}
private envMaterial(view:EnvironmentalPropView){const entry=environmentalRegistryEntry(view.category); const colors:Record<string,number>={old_wood:0x5b3922,carved_stone:0x8b8578,crypt_masonry:0x6f6b62,rubble:0x57534d,wax:0xffe7a1,corroded_iron:0x403d38,cloth:0x6f2530,worn_stone:0x77736a}; return new THREE.MeshStandardMaterial({color:colors[entry.materialFamily]??0x999999,emissive:view.category.includes('CANDLE')?0x442b08:0,roughness:.8});}
private createEnvironmentalPrototype(view:EnvironmentalPropView){const g=new THREE.Group(); g.name=`environmental.prop.${view.category}.${view.id}`; g.userData={environmentalPropId:view.id,selectable:true,category:view.category,validationState:view.validationState}; const mat=this.envMaterial(view); const add=(mesh:THREE.Mesh,x=0,y=0,z=0)=>{mesh.position.set(x,y,z); g.add(mesh);}; const q=this.options?.quality??'medium'; const radial=q==='low'?6:10; switch(view.category){case 'COFFIN': add(new THREE.Mesh(new THREE.BoxGeometry(1.0,.45,1.8),mat),0,.23,0); add(new THREE.Mesh(new THREE.BoxGeometry(.8,.18,1.55),mat),0,.55,0); break; case 'SARCOPHAGUS': add(new THREE.Mesh(new THREE.BoxGeometry(1.25,.45,2.0),mat),0,.22,0); add(new THREE.Mesh(new THREE.BoxGeometry(1.05,.25,1.75),mat),0,.58,0); break; case 'TOMB_MARKER': add(new THREE.Mesh(new THREE.BoxGeometry(.75,1.1,.16),mat),0,.55,0); break; case 'PILLAR': add(new THREE.Mesh(new THREE.CylinderGeometry(.35,.4,2.3,radial),mat),0,1.15,0); break; case 'BROKEN_PILLAR': add(new THREE.Mesh(new THREE.CylinderGeometry(.35,.45,.9,radial),mat),0,.45,0); add(new THREE.Mesh(new THREE.BoxGeometry(.45,.22,.35),mat),.45,.12,.25); break; case 'RUBBLE': case 'DEBRIS': for(let i=0;i<(view.category==='RUBBLE'?5:3);i++)add(new THREE.Mesh(new THREE.DodecahedronGeometry(.18+(i%2)*.08,0),mat),(i-2)*.22,.14,(i%2)*.22); break; case 'CANDLE': add(new THREE.Mesh(new THREE.CylinderGeometry(.07,.08,.35,8),mat),0,.18,0); add(new THREE.Mesh(new THREE.SphereGeometry(.08,8,4),this.envMaterial(view)),0,.4,0); break; case 'CANDLE_CLUSTER': for(let i=0;i<4;i++){add(new THREE.Mesh(new THREE.CylinderGeometry(.055,.07,.25+.05*i,8),mat),(i-1.5)*.16,.13+.025*i,(i%2)*.14);} break; case 'STATUE': add(new THREE.Mesh(new THREE.BoxGeometry(.75,.35,.75),mat),0,.18,0); add(new THREE.Mesh(new THREE.CylinderGeometry(.18,.24,.85,radial),mat),0,.78,0); add(new THREE.Mesh(new THREE.SphereGeometry(.2,radial,6),mat),0,1.35,0); break; case 'SHRINE': add(new THREE.Mesh(new THREE.BoxGeometry(1,.35,.55),mat),0,.18,0); add(new THREE.Mesh(new THREE.BoxGeometry(1.05,1.1,.16),mat),0,.75,-.28); break; case 'CHAIN': for(let i=0;i<5;i++)add(new THREE.Mesh(new THREE.TorusGeometry(.08,.018,6,10),mat),0,.9-i*.18,0); break; case 'WALL_DECORATION': add(new THREE.Mesh(new THREE.BoxGeometry(.9,.7,.08),mat),0,.7,0); break; case 'FLOOR_DECORATION': add(new THREE.Mesh(new THREE.BoxGeometry(1,.035,1),mat),0,.02,0); break; case 'ARCHITECTURAL_TRIM': add(new THREE.Mesh(new THREE.BoxGeometry(1.4,.2,.18),mat),0,.1,0); break; default: add(new THREE.Mesh(new THREE.BoxGeometry(.6,.6,.6),mat),0,.3,0);} if(view.validationState!=='valid')add(new THREE.Mesh(new THREE.BoxGeometry(.95,.05,.95),new THREE.MeshBasicMaterial({color:0xffcc00,wireframe:true})),0,.05,0); g.position.set(view.position.x,.02,view.position.y); g.rotation.y=view.orientation; return g;}
private applyEnvironmentalOverlayState(){const state=this.overlayState.environmental??{enabled:true,structural:true,decorative:true,bounds:false,validation:true,labels:false,categories:{}}; this.environmentalGroup.visible=state.enabled; for(const [id,obj] of this.environmentalObjects){const view=this.environmentalViews.get(id); const entry=view?environmentalRegistryEntry(view.category):undefined; const structural=entry?.displayCategory==='structural'; obj.visible=!!view&&state.enabled&&(state.categories[view.category]!==false)&&(structural?state.structural:state.decorative)&&(state.validation||view.validationState==='valid');}}
private applyEnvironmentalSelection(){for(const [id,obj] of this.environmentalObjects)obj.scale.setScalar(id===this.selectedEnvironmentalId?1.25:1);}

private buildGameplay(input:DungeonRenderInput){const views=buildGameplayPlacementViews(input.gameplayPresentation.placements); this.stats.gameplayPlacements=views.length; let renderable=0, areaCount=0; for(const view of views){this.gameplayViews.set(view.id,view); if(view.position&&Number.isFinite(view.position.x)&&Number.isFinite(view.position.y)&&Number.isFinite(view.position.z)){const marker=this.createGameplayMarker(view); this.gameplayMarkerGroup.add(marker); this.gameplayObjects.set(view.id,marker); renderable++;} for(const a of view.canonicalAreas){const area=this.createGameplayArea(view.category,a.x,a.y,a.w,a.h,view.id); this.gameplayAreaGroup.add(area); areaCount++;}} this.stats.gameplayRenderablePlacements=renderable; this.stats.gameplayAreas=areaCount; this.gameplayGroup.name='gameplay_visualization'; this.applyGameplayOverlayState(); this.applyGameplaySelection();}
private createGameplayMaterial(category:GameplayPlacementCategory,opacity=1){const s=GAMEPLAY_CATEGORY_STYLES[category]; return new THREE.MeshStandardMaterial({color:s.color,emissive:s.emissive,roughness:.65,transparent:opacity<1,opacity});}
private createGameplayMarker(view:GameplayPlacementView){const style=GAMEPLAY_CATEGORY_STYLES[view.validationState==='valid'?view.category:'unknown']; const group=new THREE.Group(); group.name=`gameplay.marker.${view.category}.${view.id}`; group.userData={gameplayPlacementId:view.id,selectable:true,category:view.category,validationState:view.validationState}; const mat=this.createGameplayMaterial(view.validationState==='valid'?view.category:'unknown'); const ring=new THREE.Mesh(new THREE.TorusGeometry(.42*style.scale,.035,6,24),mat); ring.rotation.x=Math.PI/2; ring.position.y=.04; group.add(ring); let body:THREE.Object3D; if(view.category==='player_start')body=new THREE.Mesh(new THREE.CylinderGeometry(.34,.42,.16,8),mat); else if(view.category==='boss')body=new THREE.Mesh(new THREE.ConeGeometry(.55,.95,5),mat); else if(view.category==='hazard')body=new THREE.Mesh(new THREE.ConeGeometry(.34,.58,3),mat); else if(view.category==='loot')body=new THREE.Mesh(new THREE.BoxGeometry(.58,.36,.42),mat); else if(view.category==='objective')body=new THREE.Mesh(new THREE.CylinderGeometry(.2,.28,.85,6),mat); else if(view.category==='interaction')body=new THREE.Mesh(new THREE.BoxGeometry(.3,.7,.3),mat); else if(view.category==='elite_encounter')body=new THREE.Mesh(new THREE.OctahedronGeometry(.42),mat); else if(view.category==='unknown')body=new THREE.Mesh(new THREE.BoxGeometry(.48,.48,.48),mat); else body=new THREE.Mesh(MARKER_GEOMETRY,mat); body.position.y=style.y; group.add(body); if(view.validationState!=='valid'){const warn=new THREE.Mesh(new THREE.BoxGeometry(.9,.08,.9),this.createGameplayMaterial('unknown')); warn.position.y=.1; group.add(warn);} group.position.set(view.position!.x,0.08,view.position!.y); return group;}
private createGameplayArea(category:GameplayPlacementCategory,x:number,y:number,w:number,h:number,id:string){const mat=this.createGameplayMaterial(category,.18); const mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.05,w),.035,Math.max(.05,h)),mat); mesh.name=`gameplay.area.${category}.${id}`; mesh.position.set(x,.11,y); mesh.userData={gameplayPlacementId:id,selectable:false,canonicalArea:true}; return mesh;}
private applyGameplayOverlayState(){const state=this.overlayState.gameplay??DEFAULT_GAMEPLAY_OVERLAY_STATE; this.gameplayGroup.visible=state.enabled; this.gameplayMarkerGroup.visible=state.enabled&&state.markers; this.gameplayAreaGroup.visible=state.enabled&&state.areas; for(const [id,obj] of this.gameplayObjects){const view=this.gameplayViews.get(id); obj.visible=!!view&&(state.categories[view.category]!==false||view.validationState!=='valid');} for(const obj of this.gameplayAreaGroup.children){const id=String(obj.userData.gameplayPlacementId??''); const view=this.gameplayViews.get(id); obj.visible=!!view&&state.enabled&&state.areas&&state.categories[view.category]!==false;}}
private applyGameplaySelection(){for(const [id,obj] of this.gameplayObjects){obj.scale.setScalar(id===this.selectedGameplayId?1.35:1);}}
private buildOverlays(input:DungeonRenderInput){const mk=(name:string,points:THREE.Vector3[])=>{const g=new THREE.BufferGeometry().setFromPoints(points); const l=new THREE.LineSegments(g,this.materials.overlay); l.name=name; this.add(l,this.overlayGroup);}; mk('corridor_centerlines',input.geometry.corridors.flatMap(c=>c.centerline.slice(1).flatMap((p,i)=>[tileToWorld(c.centerline[i]!.x+.5,c.centerline[i]!.y+.5,.05),tileToWorld(p.x+.5,p.y+.5,.05)]))); mk('doorways',input.geometry.doorways.flatMap(d=>d.cells.map(c=>tileToWorld(c.x+.5,c.y+.5,.12)))); this.setOverlayState(this.overlayState);}
private applyQuality(o:RendererOptions){const q=QUALITY_PROFILES[o.quality]; this.renderer?.shadowMap&&(this.renderer.shadowMap.enabled=q.shadows); this.resize(this.container?.clientWidth||800,this.container?.clientHeight||500,(globalThis as any).devicePixelRatio||1);}
private applyAnimation(o:RendererOptions){if(!o.animateBuild||o.reducedMotion)return; let i=0; for(const child of this.dungeonGroup.children){child.visible=false; setTimeout(()=>{child.visible=true;},(i++*160)/Math.max(.25,o.animationSpeed));}}
private applyWallFade(){const mat=this.materials.wall; mat.opacity=this.options?.wallFading?.valueOf()?0.62:1; mat.needsUpdate=true;}
private frameInput(input:DungeonRenderInput){const pts=input.geometry.corridors.flatMap(c=>c.footprint); if(!pts.length)return; const minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)); const cx=(minX+maxX)/2,cy=(minY+maxY)/2; this.camera.position.set(cx+35,45,cy+35); this.camera.lookAt(cx,0,cy);}
private installControls(canvas:HTMLCanvasElement){const down=(e:PointerEvent)=>{this.dragging=true;this.moved=false;this.last={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}; const move=(e:PointerEvent)=>{if(!this.dragging)return; const dx=(e.clientX-this.last.x)*-.04,dy=(e.clientY-this.last.y)*.04; if(Math.abs(dx)+Math.abs(dy)>.08)this.moved=true; this.camera.position.x+=dx;this.camera.position.z+=dy; this.last={x:e.clientX,y:e.clientY};}; const up=(e:PointerEvent)=>{if(!this.moved)this.pickScene(e,canvas); this.dragging=false;}; const wheel=(e:WheelEvent)=>{e.preventDefault(); const z=1+Math.sign(e.deltaY)*.08; this.camera.zoom=THREE.MathUtils.clamp(this.camera.zoom/z,.35,3.5); this.camera.updateProjectionMatrix();}; const ctx=(e:Event)=>e.preventDefault(); canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('contextmenu',ctx); this.listeners.push(()=>canvas.removeEventListener('pointerdown',down),()=>canvas.removeEventListener('pointermove',move),()=>canvas.removeEventListener('pointerup',up),()=>canvas.removeEventListener('wheel',wheel),()=>canvas.removeEventListener('contextmenu',ctx));}

private pickScene(e:PointerEvent,canvas:HTMLCanvasElement){const rect=canvas.getBoundingClientRect(); const mouse=new THREE.Vector2(((e.clientX-rect.left)/Math.max(1,rect.width))*2-1,-(((e.clientY-rect.top)/Math.max(1,rect.height))*2-1)); const ray=new THREE.Raycaster(); ray.setFromCamera(mouse,this.camera); const envHit=ray.intersectObjects([...this.environmentalObjects.values()],true).find(h=>h.object.userData.selectable!==false); const envId=envHit?.object.parent?.userData.environmentalPropId??envHit?.object.userData.environmentalPropId; if(typeof envId==='string'){this.selectGameplayPlacement(undefined); this.selectEnvironmentalProp(envId); canvas.dispatchEvent(new CustomEvent('environmental-prop-selected',{bubbles:true,detail:this.getSelectedEnvironmentalProp()})); return;} this.selectEnvironmentalProp(undefined); this.pickGameplay(e,canvas);}
private pickGameplay(e:PointerEvent,canvas:HTMLCanvasElement){const rect=canvas.getBoundingClientRect(); const mouse=new THREE.Vector2(((e.clientX-rect.left)/Math.max(1,rect.width))*2-1,-(((e.clientY-rect.top)/Math.max(1,rect.height))*2-1)); const ray=new THREE.Raycaster(); ray.setFromCamera(mouse,this.camera); const targets=[...this.gameplayObjects.values()]; const hit=ray.intersectObjects(targets,true).find(h=>h.object.userData.selectable!==false); const id=hit?.object.parent?.userData.gameplayPlacementId??hit?.object.userData.gameplayPlacementId; this.selectGameplayPlacement(typeof id==='string'?id:undefined); canvas.dispatchEvent(new CustomEvent('gameplay-placement-selected',{bubbles:true,detail:this.getSelectedGameplayPlacement()}));}
private loop=()=>{this.raf=requestAnimationFrame(this.loop); if(this.renderer)this.renderer.render(this.scene,this.camera);};
private disposeObject(o:THREE.Object3D){const sharedMaterials=new Set<THREE.Material>(Object.values(this.materials)); const sharedGeometries=new Set<THREE.BufferGeometry>([FLOOR_GEOMETRY,WALL_GEOMETRY,DOOR_GEOMETRY,MARKER_GEOMETRY]); o.traverse(x=>{const m=x as THREE.Mesh; if(m.geometry&&!sharedGeometries.has(m.geometry))m.geometry.dispose(); const mat=m.material; if(Array.isArray(mat))mat.forEach(mm=>{if(!sharedMaterials.has(mm))mm.dispose();}); else if(mat&&!sharedMaterials.has(mat))mat.dispose();});}
}
