import { AssetGeneratorRegistry, GeneratorImplementationRegistry, ValidationRuleRegistry, ValidationImplementationRegistry, AssetEnvironmentPackRegistry, AssetRequirementRegistry, AssetForgeCancellationContext, executeGenerationRequest, executeValidationRules, createGovernanceHandoff, validateGeneratorOutput, describeAssetForgeRuntimeCapabilities, CATACOMBS_ENVIRONMENT_PACK, CATACOMBS_REQUIREMENTS, CATACOMBS_GENERATORS, CATACOMBS_VALIDATION_RULES, CATACOMBS_GENERATOR_IMPLEMENTATIONS, CATACOMBS_VALIDATION_IMPLEMENTATIONS, CATACOMBS_PACK_ID, CATACOMBS_PACK_VERSION, ANCIENT_OSSUARY_PROFILE, ANCIENT_OSSUARY_PROFILE_ID, CATACOMBS_BUDGET_CEILINGS, CORE_ASSET_BUDGET_CEILINGS, CATACOMBS_GEOMETRY_OUTPUT_KIND, registerCatacombsProduction, type AssetGenerationRequest } from '../../../src/workbench/asset-forge/index.js';
import { generateCatacombs } from '../../../src/dungeon/generationPipeline.js';
import { config } from '../fixtures/config.js';
import { checksumResult } from '../t1c/replay.js';

function regs(){const generators=new AssetGeneratorRegistry();const generatorImplementations=new GeneratorImplementationRegistry(generators);const validationRules=new ValidationRuleRegistry();const validationImplementations=new ValidationImplementationRegistry(validationRules);const environmentPacks=new AssetEnvironmentPackRegistry();const requirements=new AssetRequirementRegistry();const registration=registerCatacombsProduction({environmentPacks,requirements,generators,generatorImplementations,validationRules,validationImplementations});return{generators,generatorImplementations,validationRules,validationImplementations,environmentPacks,requirements,registration};}
function request(requirementId=CATACOMBS_REQUIREMENTS[0]!.id,seed='seed-a',outputs=[CATACOMBS_GEOMETRY_OUTPUT_KIND]):AssetGenerationRequest{const def=CATACOMBS_ENVIRONMENT_PACK.generatorBindings.find(b=>b.selector.id===requirementId)!;return{requestId:`request.${String(requirementId).split('.').pop()}.${seed}` as never,recipe:{schemaVersion:'1.0.0' as never,recipeId:`recipe.${String(requirementId).split('.').pop()}.${seed}` as never,environmentPackId:CATACOMBS_PACK_ID,environmentPackVersion:CATACOMBS_PACK_VERSION,generatorId:def.generatorId,generatorVersion:def.supportedVersions.min,requirementId,styleProfileId:def.defaultStyleProfileId,materialProfileIds:def.defaultMaterialProfileIds,seed,parameters:{requirementId,variationFamily:'ossuary-a',damage:.25},budgetProfileId:def.budgetProfileId,requestedOutputs:outputs},created:{isoTimestamp:'2026-07-24T00:00:00.000Z',actorRef:'af-d4-test',source:'TRUSTED_INTERNAL'},validationProfileIds:[def.validationProfileId],exportProfileIds:[],outputPurpose:'AUTHORING_PREVIEW',requiredCallerCapabilities:[]};}

test('AF-D4 identities resolve exactly and immutable profile is serializable',()=>{const r=regs();expect(r.environmentPacks.get(CATACOMBS_PACK_ID,CATACOMBS_PACK_VERSION)).toEqual(CATACOMBS_ENVIRONMENT_PACK);expect(ANCIENT_OSSUARY_PROFILE.id).toBe(ANCIENT_OSSUARY_PROFILE_ID);expect(Object.isFrozen(ANCIENT_OSSUARY_PROFILE)).toBe(true);expect(JSON.stringify(ANCIENT_OSSUARY_PROFILE)).toContain('doorwayClearanceMeters');expect(JSON.stringify(ANCIENT_OSSUARY_PROFILE)).not.toContain('function');});
test('bounded traceable inventory cannot weaken global limits',()=>{expect(CATACOMBS_REQUIREMENTS).toHaveLength(12);for(const r of CATACOMBS_REQUIREMENTS){expect(r.id).toMatch(/^catacombs\.req\./);expect(r.description).toContain('derived from');expect(r.packageAcceptanceState).toBe('VALIDATION_PENDING');expect(r.provenanceExpectations.join(' ')).toContain('no final material');}for(const k of Object.keys(CORE_ASSET_BUDGET_CEILINGS) as (keyof typeof CORE_ASSET_BUDGET_CEILINGS)[])expect(CATACOMBS_BUDGET_CEILINGS[k]).toBeLessThanOrEqual(CORE_ASSET_BUDGET_CEILINGS[k]);});
test('production registration has no fixtures and every descriptor has a trusted implementation',()=>{const r=regs();expect(r.registration.diagnostics).toEqual([]);expect(CATACOMBS_GENERATORS.every(g=>!String(g.id).includes('test')&&!String(g.id).includes('fixture'))).toBe(true);for(const g of CATACOMBS_GENERATORS)expect(r.generatorImplementations.resolve(g.id,g.version)).toBeTruthy();for(const v of CATACOMBS_VALIDATION_RULES)expect(r.validationImplementations.resolve(v.id,v.version)).toBeTruthy();});
test('unsupported output kinds fail admission and unsupported requirements fail generation closed',async()=>{const r=regs();expect((await executeGenerationRequest(request(undefined as never,'s',['texture.final' as never]),r.generators,r.generatorImplementations)).status).toBe('ADMISSION_REJECTED');const bad={...request(),recipe:{...request().recipe,requirementId:'catacombs.req.unsupported' as never,parameters:{requirementId:'catacombs.req.unsupported'}}};expect((await executeGenerationRequest(bad,r.generators,r.generatorImplementations)).status).toBe('GENERATION_FAILED');});
test('determinism, controlled seed variation, named substreams, and immutable package candidates',async()=>{const r=regs();const a=await executeGenerationRequest(request(CATACOMBS_REQUIREMENTS[8]!.id,'same'),r.generators,r.generatorImplementations);const b=await executeGenerationRequest(request(CATACOMBS_REQUIREMENTS[8]!.id,'same'),r.generators,r.generatorImplementations);const c=await executeGenerationRequest(request(CATACOMBS_REQUIREMENTS[8]!.id,'different'),r.generators,r.generatorImplementations);expect(a.status).toBe('PACKAGE_CANDIDATE_READY');expect(b.status).toBe('PACKAGE_CANDIDATE_READY');expect(c.status).toBe('PACKAGE_CANDIDATE_READY');if(a.status==='PACKAGE_CANDIDATE_READY'&&b.status==='PACKAGE_CANDIDATE_READY'&&c.status==='PACKAGE_CANDIDATE_READY'){expect(a.packageCandidate.integrity).toEqual(b.packageCandidate.integrity);expect(a.packageCandidate.integrity).not.toEqual(c.packageCandidate.integrity);expect(Object.isFrozen(a.packageCandidate)).toBe(true);expect(a.packageCandidate.provenanceRefs.join(' ')).toContain('primary-shape');expect(a.packageCandidate.provenanceRefs.join(' ')).toContain('variation-selection');}});
test('cancellation cannot produce a package candidate and package-integrity governance cannot promote',async()=>{const r=regs();const cancel=new AssetForgeCancellationContext('cancel.af-d4');cancel.cancel('USER_REQUESTED');expect((await executeGenerationRequest(request(),r.generators,r.generatorImplementations,cancel)).status).toBe('CANCELLED');const ok=await executeGenerationRequest(request(),r.generators,r.generatorImplementations);expect(ok.status).toBe('PACKAGE_CANDIDATE_READY');if(ok.status==='PACKAGE_CANDIDATE_READY'){const val=await executeValidationRules(ok.packageCandidate,r.validationRules,r.validationImplementations);expect(val.summary.status).toBe('PASS');const handoff=createGovernanceHandoff(ok.packageCandidate,val.summary);expect(handoff.canCreatePlaceholderApproval).toBe(false);expect(handoff.canCreateProductionApproval).toBe(false);expect((handoff as any).canPromoteRuntimeAsset).not.toBe(true);}});
test('geometry validation rejects invalid vertices, paths, material generation, and approval claims',()=>{expect(validateGeneratorOutput({outputKind:CATACOMBS_GEOMETRY_OUTPUT_KIND,inventory:['asset.catacombs.req.wall-segment'],geometry:{vertices:[[Infinity,0,0]],indices:[0]},metrics:{vertices:1}}).ok).toBe(false);expect(validateGeneratorOutput({outputKind:CATACOMBS_GEOMETRY_OUTPUT_KIND,inventory:['https://example.invalid/x'],geometry:{},metrics:{}}).ok).toBe(false);expect(validateGeneratorOutput({outputKind:CATACOMBS_GEOMETRY_OUTPUT_KIND,inventory:['asset.catacombs.req.wall-segment'],geometry:{},materials:{finalTexture:true},creationStatus:'PRODUCTION_APPROVED'} as any).ok).toBe(false);});
test('generated descriptors include pivots, bounds, anchors, sockets, collision, LODs, and doorway clearance',async()=>{const r=regs();const doorway=CATACOMBS_REQUIREMENTS.find(x=>x.id==='catacombs.req.arch-doorway')!;expect(doorway.spatial.pivot).toBe('GROUND_CENTER');expect(doorway.requiredAnchors.length).toBeGreaterThan(0);expect(doorway.requiredSockets.length).toBeGreaterThan(0);expect(doorway.collision.navigationIntent).toBe('BLOCKER');expect(doorway.lodPolicy.levels).toHaveLength(3);expect(ANCIENT_OSSUARY_PROFILE.doorwayClearanceMeters.width).toBeGreaterThanOrEqual(2.2);const out=await executeGenerationRequest(request(doorway.id),r.generators,r.generatorImplementations);expect(out.status).toBe('PACKAGE_CANDIDATE_READY');});
test('capability reporting matches genuine registration and AF-D1 routes remain read-only',()=>{const caps=describeAssetForgeRuntimeCapabilities();expect(caps.generationAvailable).toBe(true);expect(caps.trustedGeneratorImplementationCount).toBe(CATACOMBS_GENERATOR_IMPLEMENTATIONS.length);expect(caps.trustedValidationImplementationCount).toBe(CATACOMBS_VALIDATION_IMPLEMENTATIONS.length);expect(caps.materialGenerationStatus).toContain('AF-D5');expect(caps.previewStatus).toContain('AF-D6');expect(caps.exportStatus).toContain('AF-D7');expect(caps.sceneIntegrationStatus).toContain('AF-D8');});
test('registration order does not affect resolution',()=>{const a=regs(),b=regs();expect(JSON.stringify(a.generators.snapshot())).toBe(JSON.stringify(b.generators.snapshot()));expect(JSON.stringify(a.environmentPacks.snapshot())).toBe(JSON.stringify(b.environmentPacks.snapshot()));});
test('Math.random is absent from deterministic generation source and no DOM or Three.js output is produced',async()=>{const fs=await import('node:fs/promises');const src=await fs.readFile('src/workbench/asset-forge/catacombsPack.ts','utf8');expect(src).not.toContain('Math.random');expect(src).not.toMatch(/from ['"]three|document\.|window\./);const r=regs();const out=await executeGenerationRequest(request(),r.generators,r.generatorImplementations);expect(out.status).toBe('PACKAGE_CANDIDATE_READY');if(out.status==='PACKAGE_CANDIDATE_READY')expect(JSON.stringify(out.packageCandidate)).not.toMatch(/Three|HTML|Element|Scene/);});
test('Dungeon Generator RNG and canonical checksum remain isolated',()=>{const before=generateCatacombs({config:config('af-d4-boundary')});regs();const after=generateCatacombs({config:config('af-d4-boundary')});expect(before.ok&&after.ok).toBe(true);if(before.ok&&after.ok)expect(checksumResult(after)).toBe(checksumResult(before));});
