/** @jest-environment jsdom */
import { jest } from '@jest/globals';

class V{constructor(public x=0,public y=0,public z=0){} set(x:number,y:number,z:number){this.x=x;this.y=y;this.z=z;return this;}}
class Obj{children:any[]=[];position=new V();rotation=new V(); add(x:any){this.children.push(x);} lookAt(){}}
class Scene extends Obj{}
class PerspectiveCamera extends Obj{constructor(..._a:any[]){super();}}
class BufferAttribute{constructor(public array:any,public itemSize:number){}}
class BufferGeometry{disposed=false; attrs:any={}; setAttribute(n:string,a:any){this.attrs[n]=a;} setIndex(i:any){this.index=i;} computeVertexNormals(){} dispose(){this.disposed=true;} index:any;}
class Material{disposed=false; needsUpdate=false; wireframe=false; color={value:0,set:(v:number)=>{this.color.value=v;}}; constructor(opts:any={}){Object.assign(this,opts);} dispose(){this.disposed=true;}}
class MeshStandardMaterial extends Material{} class LineBasicMaterial extends Material{} class RawShaderMaterial extends Material{} class HemisphereLight extends Obj{constructor(..._a:any[]){super();}}
class Mesh extends Obj{constructor(public geometry:any,public material:any){super();}} class LineSegments extends Mesh{} class SphereGeometry extends BufferGeometry{constructor(..._a:any[]){super();}}
class WebGLRenderer{domElement=document.createElement('canvas');disposed=false;last:any; constructor(public opts:any){} setPixelRatio(v:number){this.pixelRatio=v;} setSize(w:number,h:number){this.size=[w,h];} render(s:any,c:any){this.last=[s,c];} dispose(){this.disposed=true;} pixelRatio=0; size:any;}
await jest.unstable_mockModule('three',()=>({Scene,PerspectiveCamera,BufferAttribute,BufferGeometry,MeshStandardMaterial,LineBasicMaterial,RawShaderMaterial,HemisphereLight,Mesh,LineSegments,SphereGeometry,WebGLRenderer}));
const mod=await import('../../../src/workbench/asset-forge/index.js');
const {AssetGeneratorRegistry,GeneratorImplementationRegistry,ValidationRuleRegistry,ValidationImplementationRegistry,executeGenerationRequest,CATACOMBS_PACK_ID,CATACOMBS_PACK_VERSION,CATACOMBS_STYLE_PROFILE_ID,CATACOMBS_MATERIAL_INTENT_ID,CATACOMBS_REQUIREMENTS,CATACOMBS_GEOMETRY_OUTPUT_KIND,CATACOMBS_GENERATORS,CATACOMBS_MATERIAL_OUTPUT_KIND,CATACOMBS_MATERIAL_GENERATOR_ID,registerCatacombsProduction,registerCatacombsMaterialProduction,ThreeAssetPreviewAdapter,validateSdfPrimitiveAssembly,createCatacombsBlendShellDemo,simulateProceduralPreviewMotion,validateProceduralRig,SDF_BLEND_SHELL_VERTEX_SHADER,describeAssetPreviewProductionRegistration,createAssetInspectionReport,createAssetReviewDraft,compareAssetPreviewCandidates,buildAssetPreviewProjection}=mod as any;
function request(kind:'geo'|'mat',seed='af-d6r',requirementId=CATACOMBS_REQUIREMENTS[0]!.id){const gen=kind==='geo'?CATACOMBS_GENERATORS[0]!.id:CATACOMBS_MATERIAL_GENERATOR_ID;const out=kind==='geo'?CATACOMBS_GEOMETRY_OUTPUT_KIND:CATACOMBS_MATERIAL_OUTPUT_KIND;return{requestId:`request.afd6r.${kind}.${seed}`,recipe:{schemaVersion:'1.0.0',recipeId:`recipe.afd6r.${kind}.${seed}`,environmentPackId:CATACOMBS_PACK_ID,environmentPackVersion:CATACOMBS_PACK_VERSION,generatorId:gen,generatorVersion:'1.0.0',requirementId,styleProfileId:CATACOMBS_STYLE_PROFILE_ID,materialProfileIds:[CATACOMBS_MATERIAL_INTENT_ID],seed,parameters:{requirementId,resolution:16},budgetProfileId:'catacombs.budget.af-d4',requestedOutputs:[out]},created:{isoTimestamp:'2026-07-24T00:00:00.000Z',actorRef:'af-d6r-test',source:'TRUSTED_INTERNAL'},validationProfileIds:[kind==='geo'?'catacombs.validation.af-d4':'catacombs.validation.af-d5'],exportProfileIds:[],outputPurpose:'AUTHORING_PREVIEW',requiredCallerCapabilities:[]};}
async function candidates(reqId=CATACOMBS_REQUIREMENTS[0]!.id){const r={generators:new AssetGeneratorRegistry(),validationRules:new ValidationRuleRegistry()} as any;r.generatorImplementations=new GeneratorImplementationRegistry(r.generators);r.validationImplementations=new ValidationImplementationRegistry(r.validationRules);registerCatacombsProduction(r);registerCatacombsMaterialProduction(r);const geo=(await executeGenerationRequest(request('geo','x',reqId),r.generators,r.generatorImplementations)).packageCandidate;const mat=(await executeGenerationRequest(request('mat','x',reqId),r.generators,r.generatorImplementations)).packageCandidate;return{geo,mat};}
beforeEach(()=>{HTMLCanvasElement.prototype.getContext=function(){return {}; } as any;(globalThis as any).requestAnimationFrame=(f:FrameRequestCallback)=>setTimeout(()=>f(performance.now()),1) as any;(globalThis as any).cancelAnimationFrame=(h:any)=>clearTimeout(h);});

test('AF-D6R production adapter renders genuine candidate and all live controls mutate state and dispose resources',async()=>{const {geo,mat}=await candidates();const host=document.createElement('section');Object.defineProperty(host,'clientWidth',{value:320});Object.defineProperty(host,'clientHeight',{value:240});const a=new ThreeAssetPreviewAdapter(host,{reducedMotion:true});const res=a.initialize({candidate:geo,materialCandidate:mat,overlays:['pivot','anchors','sockets','collision-intent']});expect(res.ok).toBe(true);expect(host.querySelector('canvas')).toBeTruthy();expect(a.state.webglAvailable).toBe(true);a.setMode('wireframe');expect(a.state.mode).toBe('wireframe');a.setMode('vertexNormals');expect(a.state.overlays.has('vertexNormals')).toBe(false);a.setMaterialChannel('normal');expect(a.state.mode).toBe('normal');for(const p of mod.PREVIEW_CAMERA_PRESETS)a.setCameraPreset(p.id);expect(a.state.cameraPreset).toBe('detail-inspection');for(const p of mod.PREVIEW_LIGHTING_PRESETS)a.setLightingPreset(p.id);expect(a.state.lightingPreset).toBe('unlit-channel');a.setBackground('grid');a.setLod(2);a.startTurntable();a.pauseTurntable();const f=a.state.frames;a.pauseTurntable();expect(a.state.frames).toBe(f);a.startProceduralMotion();a.stepProceduralMotion();a.resetProceduralMotion();expect(a.state.animationPhase).toBe(0);a.dispose();expect(a.state.disposed).toBeGreaterThan(5);expect(host.childElementCount).toBe(0);});

test('admission, projection, webgl absence, context loss and candidate change fail closed',async()=>{const {geo,mat}=await candidates();const host=document.createElement('section');const a=new ThreeAssetPreviewAdapter(host);const bad=a.initialize({candidate:{...geo,creationStatus:'FAILED'},materialCandidate:mat});expect(bad.ok).toBe(false);expect(host.querySelector('canvas')).toBeFalsy();HTMLCanvasElement.prototype.getContext=function(){return null;} as any;const noGl=new ThreeAssetPreviewAdapter(host);expect(noGl.initialize({candidate:geo,materialCandidate:mat}).ok).toBe(false);expect(noGl.state.inspectionText).toContain('READY_FOR_HUMAN_REVIEW');HTMLCanvasElement.prototype.getContext=function(){return {}; } as any;const ctx=new ThreeAssetPreviewAdapter(host);ctx.initialize({candidate:geo,materialCandidate:mat});host.querySelector('canvas')!.dispatchEvent(new Event('webglcontextlost',{cancelable:true}));expect(ctx.diagnostics.join(' ')).toContain('webglcontextlost');expect(ctx.state.inspectionText).toContain(geo.packageId);const before=ctx.state.disposed;ctx.initialize({candidate:geo,materialCandidate:mat});expect(ctx.state.disposed).toBeGreaterThanOrEqual(before);ctx.dispose();});

test('SDF blend-shell validates bounded primitives, shader identity, normals, offset outlines, and security boundary',()=>{const demo=createCatacombsBlendShellDemo();expect(demo.ok).toBe(true);if(demo.ok){expect(demo.projection.drawCalls).toBe(1);expect(demo.projection.usesRaymarching).toBe(false);expect(demo.projection.usesSkeletalSkinning).toBe(false);expect(demo.projection.budget.maxProjectionIterations).toBe(4);expect(demo.projection.primitives.find((p:any)=>p.role==='ear').blendRadius).toBeLessThanOrEqual(.08);}expect(SDF_BLEND_SHELL_VERTEX_SHADER).toContain('sdfGradient');expect(SDF_BLEND_SHELL_VERTEX_SHADER).toContain('SDF_PROJECTION_ITERATIONS 4');expect(SDF_BLEND_SHELL_VERTEX_SHADER).not.toMatch(/raymarch|skinning|boneMatrix/i);expect(validateSdfPrimitiveAssembly({primitives:[{id:'bad.kind',kind:'box',center:[0,0,0],radius:1,blendRadius:.1,color:[1,1,1]}]}).ok).toBe(false);expect(validateSdfPrimitiveAssembly({primitives:[{id:'thin.x',kind:'sphere',center:[0,0,0],radius:.1,blendRadius:.2,color:[1,1,1],role:'thin-part'}]}).ok).toBe(false);expect(validateSdfPrimitiveAssembly({primitives:[{id:'shader.bad',kind:'sphere',center:[0,0,0],radius:.1,blendRadius:.02,color:[1,1,1],shaderSource:'evil'}]}).ok).toBe(false);});

test('procedural motion and review/comparison governance remain deterministic and non-authoritative',async()=>{expect(validateProceduralRig({legs:3}).ok).toBe(false);expect(validateProceduralRig({legs:6,rope:Array.from({length:9},(_,i)=>({id:`r${i}`}))}).ok).toBe(false);expect(simulateProceduralPreviewMotion(7,5,1/60,4)).toEqual(simulateProceduralPreviewMotion(7,5,1/60,4));expect(simulateProceduralPreviewMotion(7,5,1/60,2).dungeonRngConsumed).toBe(false);const {geo,mat}=await candidates();const report=createAssetInspectionReport({candidate:geo,materialCandidate:mat});const draft=createAssetReviewDraft(report,'Reviewer <x>',[{severity:'INFO',category:'GOVERNANCE',note:'no <approval>',suggestedDisposition:'REVIEW_INCOMPLETE'}]);expect(draft.approvalAuthority).toBe(false);expect(JSON.stringify(draft)).not.toContain('<');expect(compareAssetPreviewCandidates(report,{...report,requirementId:'other'}).compatible).toBe(false);const projection=buildAssetPreviewProjection({candidate:geo,materialCandidate:mat});expect(JSON.stringify(projection)).not.toMatch(/WebGL|HTMLCanvas|THREE|function|shaderSource/);expect(describeAssetPreviewProductionRegistration()).toMatchObject({approvalAvailable:false,exportAvailable:false,standardMeshPreview:true,sdfBlendShellPreview:true,proceduralAnimationPreview:true});});
