import { CATACOMBS_REFERENCE_ASSET_REGISTRY, buildAssetInspectorDiagnostics, canonicalAssetRegistryProjection, hashAssetRegistry, resolveAsset, validateCatacombsAssetRegistry, type CatacombsAssetRegistry } from '../../src/dungeon/index.js';
import { canonicalStringify } from '../../src/dungeon/index.js';
import { environmentProfile } from './fixtures/fixtures.js';

describe('Catacombs asset registry',()=>{
 test('schema-like registry validation accepts reference content and required categories',()=>{const issues=validateCatacombsAssetRegistry(CATACOMBS_REFERENCE_ASSET_REGISTRY); expect(issues.filter(i=>i.severity==='error')).toEqual([]); expect(CATACOMBS_REFERENCE_ASSET_REGISTRY.categories).toEqual(expect.arrayContaining(['floor','wall','prop cluster','effect anchor','procedural primitive']));});
 test('duplicate ID rejection and namespace validation are structured',()=>{const bad={...CATACOMBS_REFERENCE_ASSET_REGISTRY,assets:[CATACOMBS_REFERENCE_ASSET_REGISTRY.assets[0]!,{...CATACOMBS_REFERENCE_ASSET_REGISTRY.assets[0]!}]} satisfies CatacombsAssetRegistry; const codes=validateCatacombsAssetRegistry(bad).map(i=>i.code); expect(codes).toContain('ASSET_DUPLICATE_ID'); const badNs={...CATACOMBS_REFERENCE_ASSET_REGISTRY,assets:[{...CATACOMBS_REFERENCE_ASSET_REGISTRY.assets[0]!,id:'bad'},...CATACOMBS_REFERENCE_ASSET_REGISTRY.assets.slice(1)]} satisfies CatacombsAssetRegistry; expect(validateCatacombsAssetRegistry(badNs).map(i=>i.code)).toContain('ASSET_INVALID_NAMESPACE');});
 test('authored and fallback resolution are explicit and loader independent',()=>{const authoredEntry={...CATACOMBS_REFERENCE_ASSET_REGISTRY.assets.find(a=>a.family==='stone_slab')!,authored:{...CATACOMBS_REFERENCE_ASSET_REGISTRY.assets.find(a=>a.family==='stone_slab')!.authored!,available:true}}; const reg={...CATACOMBS_REFERENCE_ASSET_REGISTRY,assets:[authoredEntry,...CATACOMBS_REFERENCE_ASSET_REGISTRY.assets.filter(a=>a.id!==authoredEntry.id)]}; const a=resolveAsset(reg,environmentProfile,{family:'stone_slab',category:'floor',qualityTier:'high',preferAuthored:true,loaderAvailable:false,activeRuntimeLod:2}); const b=resolveAsset(CATACOMBS_REFERENCE_ASSET_REGISTRY,environmentProfile,{family:'stone_slab',category:'floor',qualityTier:'low',loaderAvailable:true,activeRuntimeLod:0}); expect(a.state).toBe('AUTHORED'); expect(b.state).toBe('FALLBACK'); expect(a.resolvedAssetId).toBe(b.resolvedAssetId);});
 test('missing and invalid asset reporting never becomes generic placeholders',()=>{const missing=resolveAsset(CATACOMBS_REFERENCE_ASSET_REGISTRY,environmentProfile,{family:'does_not_exist',category:'floor',qualityTier:'medium'}); const invalidReg={...CATACOMBS_REFERENCE_ASSET_REGISTRY,assets:[{...CATACOMBS_REFERENCE_ASSET_REGISTRY.assets[0]!,materialGroupIds:['missing.group']},...CATACOMBS_REFERENCE_ASSET_REGISTRY.assets.slice(1)]}; const invalid=resolveAsset(invalidReg,environmentProfile,{assetId:CATACOMBS_REFERENCE_ASSET_REGISTRY.assets[0]!.id,qualityTier:'medium'}); expect(missing.state).toBe('MISSING'); expect(invalid.state).toBe('INVALID'); expect(missing.fallback).toBeUndefined();});
 test('deterministic variant selection, serialization, hashes, and object-order independence are stable',()=>{const req={family:'stone_slab',category:'floor' as const,qualityTier:'medium' as const,rootSeed:'seed-a',generatorVersion:'v',rngStream:'construction' as const}; expect(resolveAsset(CATACOMBS_REFERENCE_ASSET_REGISTRY,environmentProfile,req)).toEqual(resolveAsset(CATACOMBS_REFERENCE_ASSET_REGISTRY,environmentProfile,req)); const shuffled={...CATACOMBS_REFERENCE_ASSET_REGISTRY,assets:[...CATACOMBS_REFERENCE_ASSET_REGISTRY.assets].reverse(),materials:[...CATACOMBS_REFERENCE_ASSET_REGISTRY.materials].reverse(),textures:[...CATACOMBS_REFERENCE_ASSET_REGISTRY.textures].reverse(),materialGroups:[...CATACOMBS_REFERENCE_ASSET_REGISTRY.materialGroups].reverse()}; expect(hashAssetRegistry(shuffled)).toBe(hashAssetRegistry(CATACOMBS_REFERENCE_ASSET_REGISTRY)); expect(canonicalStringify(canonicalAssetRegistryProjection(shuffled) as never)).toBe(canonicalStringify(canonicalAssetRegistryProjection(CATACOMBS_REFERENCE_ASSET_REGISTRY) as never));});
 test('material, texture, LOD, fallback equivalence, diagnostics adapter',()=>{const issues=validateCatacombsAssetRegistry(CATACOMBS_REFERENCE_ASSET_REGISTRY); expect(issues.map(i=>i.code)).not.toContain('ASSET_BROKEN_TEXTURE_REF'); expect(issues.map(i=>i.code)).not.toContain('ASSET_INVALID_LOD_ORDERING'); const r=resolveAsset(CATACOMBS_REFERENCE_ASSET_REGISTRY,environmentProfile,{family:'sarcophagus',category:'prop',qualityTier:'medium'}); expect(r.fallback?.collisionEquivalent).toBe(true); expect(r.collision?.footprint).toEqual(r.navigation?.footprint); const diag=buildAssetInspectorDiagnostics([r]); expect(diag.proceduralFallbackUsage).toHaveLength(1); expect(diag.drawCallGroups.length).toBeGreaterThan(0);});
});
