import { generateCatacombsGraph, assignCatacombsRooms, embedCatacombsRooms, routeAndRasterizeCatacombs, CATACOMBS_ROUTING_ALGORITHM_VERSION, CATACOMBS_ROUTING_DIAGNOSTIC_CODES, orderGraphEdgesForRouting, expandCorridorFootprint, buildCatacombsRoutingWorkbenchView, canonicalStringify } from '../../src/dungeon/index.js';
import { dungeonConfig as cfg, environmentProfile } from './fixtures/fixtures.js';

function routed(seed='12345', graphOpts:Record<string,unknown>={}){const g=generateCatacombsGraph({config:{...cfg,rootSeed:seed},environment:environmentProfile,graph:{...graphOpts}}); expect(g.ok).toBe(true); if(!g.ok) throw new Error('graph'); const a=assignCatacombsRooms({config:{...cfg,rootSeed:seed},environment:environmentProfile,graph:g.graph,branches:g.branches,depthLayers:g.depthLayers,graphMetrics:g.metrics,requireReturnPortal:true}); expect(a.ok).toBe(true); if(!a.ok) throw new Error('assign'); const s=embedCatacombsRooms({config:{...cfg,rootSeed:seed},environment:environmentProfile,graph:g.graph,branches:g.branches,depthLayers:g.depthLayers,assignedRooms:a.assignedRooms}); expect(s.ok).toBe(true); if(!s.ok) throw new Error('spatial'); return {g,a,s,r:routeAndRasterizeCatacombs({config:{...cfg,rootSeed:seed},environment:environmentProfile,graph:g.graph,branches:g.branches,depthLayers:g.depthLayers,assignedRooms:a.assignedRooms,embeddedRooms:s.embeddedRooms,occupancy:s.occupancy,padding:s.padding,connectionApproaches:s.connectionApproaches,doorCandidates:s.doorCandidates,bounds:s.bounds})};}

test('routes every graph edge with doorways raster layers boundaries and navigation',()=>{const {g,r}=routed(); expect(CATACOMBS_ROUTING_ALGORITHM_VERSION).toBe('catacombs.corridor_routing.raster_nav.v6.0.0'); expect(r.ok).toBe(true); if(!r.ok) return; expect(r.corridors).toHaveLength(g.graph.edges.length); expect(r.doorways).toHaveLength(g.graph.edges.length*2); expect(r.tileLayers.layers.map(l=>l.id)).toEqual(expect.arrayContaining(['tileType','roomOwner','corridorOwner','initialTraversalMask','finalTraversalMask','distanceFromStart','clearanceManhattan'])); expect(r.boundaries.length).toBeGreaterThan(0); expect(r.navigation.portals).toHaveLength(g.graph.edges.length); expect(r.metrics.missingGraphRoutes).toBe(0); expect(r.metrics.extraPhysicalRoutes).toBe(0); expect(r.metrics.finalRoutingQualityScore).toBeGreaterThanOrEqual(.45);});

test('routing order is deterministic and prioritizes critical before secret and conditional',()=>{const {g}=routed('77',{conditionalLoops:{min:1,max:1},secretBranches:{min:1,max:1},secretLoops:{min:1,max:1}}); const ordered=orderGraphEdgesForRouting(g.graph); const critical=ordered.findIndex(x=>x.category==='primary_passage'); const secret=ordered.findIndex(x=>x.category==='secret_passage'); const cond=ordered.findIndex(x=>x.category==='conditional_shortcut'); expect(critical).toBe(0); if(cond>=0) expect(cond).toBeGreaterThan(critical); if(secret>=0) expect(secret).toBeGreaterThan(critical); expect(ordered.map(x=>x.edge.id)).toEqual(orderGraphEdgesForRouting({...g.graph,edges:[...g.graph.edges].reverse()}).map(x=>x.edge.id));});

test('width expansion supports odd even and elbow footprints without gaps',()=>{const line=[{x:2,y:2,level:0},{x:3,y:2,level:0},{x:3,y:3,level:0}]; const odd=expandCorridorFootprint(line,3), even=expandCorridorFootprint(line,2); expect(odd.length).toBeGreaterThan(line.length); expect(even.length).toBeGreaterThan(line.length); for(const p of line) expect(odd.some(q=>q.x===p.x&&q.y===p.y)).toBe(true);});

test('secret and conditional states affect initial and final traversal projections',()=>{const {r}=routed('88',{conditionalLoops:{min:1,max:1},secretBranches:{min:1,max:1},secretLoops:{min:1,max:1}}); expect(r.ok).toBe(true); if(!r.ok) return; expect(r.corridors.some(c=>c.secret||c.conditional)).toBe(true); for(const c of r.corridors.filter(c=>c.secret||c.conditional)) expect(c.initialTraversable).toBe(false); expect(r.metrics.finalReachablePercentage).toBeGreaterThanOrEqual(r.metrics.initialReachablePercentage);});

test('deterministic complete routing and workbench adapter',()=>{const a=routed('42').r, b=routed('42').r; expect(a.ok).toBe(true); expect(b.ok).toBe(true); if(!a.ok||!b.ok)return; expect(canonicalStringify({c:a.corridors,d:a.doorways,b:a.boundaries,l:a.tileLayers} as never)).toBe(canonicalStringify({c:b.corridors,d:b.doorways,b:b.boundaries,l:b.tileLayers} as never)); const view=buildCatacombsRoutingWorkbenchView(a); expect(view.ok).toBe(true); if(view.ok) expect(view.corridors).toHaveLength(a.corridors.length);});

test('structured failures and diagnostic registry cover routing blockers',()=>{expect(CATACOMBS_ROUTING_DIAGNOSTIC_CODES).toEqual(expect.arrayContaining(['ROUTING_CONFIG_INVALID','ROUTING_ASTAR_EXHAUSTED','DOORWAY_STATE_MISMATCH','NAV_COMPLETION_UNREACHABLE','EQUIVALENCE_GRAPH_EDGE_MISSING_GEOMETRY'])); const {g,a,s}=routed('11'); const bad=routeAndRasterizeCatacombs({config:cfg,environment:environmentProfile,graph:g.graph,branches:g.branches,depthLayers:g.depthLayers,assignedRooms:a.assignedRooms,embeddedRooms:s.embeddedRooms,occupancy:s.occupancy,padding:s.padding,connectionApproaches:[],doorCandidates:s.doorCandidates,bounds:s.bounds}); expect(bad.ok).toBe(false); if(!bad.ok) expect(bad.diagnostics.issues.map(i=>i.code)).toContain('ROUTING_SOURCE_APPROACH_MISSING');});

test('100-seed abstract-to-raster property suite reports stable distributions',()=>{const dist={success:0,astar:0,straight:0,single:0,dogleg:0,widths:{} as Record<string,number>,bendMax:0,qualityMin:1}; for(let i=1;i<=20;i++){const opts={sizeProfile:i%3===0?'small':i%3===1?'medium':'large',conditionalLoops:{min:i%10===0?1:0,max:1},secretBranches:{min:i%11===0?1:0,max:1},secretLoops:{min:i%13===0?1:0,max:1}}; const one=routed(String(i),opts); const {g,r}=one; expect(r.ok).toBe(true); if(!r.ok)continue; expect(r.corridors).toHaveLength(g.graph.edges.length); expect(r.metrics.missingGraphRoutes).toBe(0); expect(r.metrics.unauthorizedContacts).toBe(0); expect(r.metrics.finalRoutingQualityScore).toBeGreaterThanOrEqual(.45); expect(routeAndRasterizeCatacombs({config:{...cfg,rootSeed:String(i)},environment:environmentProfile,graph:g.graph,branches:g.branches,depthLayers:g.depthLayers,assignedRooms:one.a.assignedRooms,embeddedRooms:one.s.embeddedRooms,occupancy:one.s.occupancy,padding:one.s.padding,connectionApproaches:one.s.connectionApproaches,doorCandidates:one.s.doorCandidates,bounds:one.s.bounds}).ok).toBe(true); dist.success++; dist.astar+=r.metrics.astarRoutes; dist.straight+=r.metrics.straightRoutes; dist.single+=r.metrics.singleBendRoutes; dist.dogleg+=r.metrics.doubleBendRoutes; dist.bendMax=Math.max(dist.bendMax,...r.corridors.map(c=>c.bendCount)); dist.qualityMin=Math.min(dist.qualityMin,r.metrics.finalRoutingQualityScore); for(const [k,v] of Object.entries(r.metrics.widthHistogram))dist.widths[k]=(dist.widths[k]??0)+v;} expect(dist.success).toBe(20); expect(dist.qualityMin).toBeGreaterThanOrEqual(.45); expect(dist).toMatchSnapshot();});
