import { buildConstructionWorkbenchAdapters, CATACOMBS_PROP_CLUSTERS, CATACOMBS_PROP_DEFINITIONS, CATACOMBS_ROOM_CONSTRUCTION_PROFILES, generateCatacombsConstruction, PROP_SPATIAL_BEHAVIOR_DEFINITIONS, validateCatacombsConstructionProfiles, type ConstructionInput } from '../../src/dungeon/index.js';
import { environmentProfile } from './fixtures/fixtures.js';

const assignedRooms=[{nodeId:'room.entrance',graphNodeId:'room.entrance',archetypeId:'catacombs.mausoleum_entrance',roomCategory:'entrance',roomScale:'medium',roomFunction:'entrance',semanticTags:[],contentSlots:[],placementState:'unembedded'},{nodeId:'room.boss',graphNodeId:'room.boss',archetypeId:'catacombs.boss_sepulcher',roomCategory:'landmark',roomScale:'landmark',roomFunction:'boss',semanticTags:[],contentSlots:[],placementState:'unembedded'}] as any;
const embeddedRooms=[{assignedRoom:assignedRooms[0],footprint:{origin:{x:0,y:0,level:0},width:10,height:8,mask:new Uint8Array(80).fill(1),bounds:{minimumX:0,minimumY:0,maximumX:9,maximumY:7,level:0}}},{assignedRoom:assignedRooms[1],footprint:{origin:{x:20,y:0,level:0},width:12,height:10,mask:new Uint8Array(120).fill(1),bounds:{minimumX:20,minimumY:0,maximumX:31,maximumY:9,level:0}}}] as any;
const corridors=[{id:'corridor.edge.0',graphEdgeId:'edge.0',sourceRoomId:'room.entrance',targetRoomId:'room.boss',category:'primary_passage',width:3,sourceApproachId:'a',targetApproachId:'b',centerline:[{x:10,y:4,level:0},{x:15,y:4,level:0},{x:19,y:4,level:0}],footprint:[{x:10,y:4,level:0}],length:3,bendCount:0,initialTraversable:true,finalTraversable:true,secret:false,conditional:false,strategy:'straight'}] as any;
const doorways=[{id:'doorway.edge.0.room.entrance',graphEdgeId:'edge.0',roomId:'room.entrance',corridorId:'corridor.edge.0',cells:[{x:9,y:4,level:0}],inwardNormal:'w',outwardNormal:'e',category:'open_arch',initialState:'open',width:3},{id:'doorway.edge.0.room.boss',graphEdgeId:'edge.0',roomId:'room.boss',corridorId:'corridor.edge.0',cells:[{x:20,y:4,level:0}],inwardNormal:'e',outwardNormal:'w',category:'monumental_boss_entrance',initialState:'closed',width:3}] as any;
const boundaries=[{tile:{x:0,y:0,level:0},side:'n',boundaryType:'room_wall'},{tile:{x:9,y:4,level:0},side:'e',boundaryType:'door_opening',doorwayId:'doorway.edge.0.room.entrance'}] as any;
const navigation={width:40,height:20,initialMask:new Uint8Array(800).fill(1),finalMask:new Uint8Array(800).fill(1),distanceFromStart:new Int32Array(800).fill(1),finalDistanceFromStart:new Int32Array(800).fill(1),clearance:new Uint16Array(800).fill(2),unreachableSentinel:-1,initialReachableCells:800,finalReachableCells:800,regions:[],portals:[]} as any;
function input(seed='seed-1'):ConstructionInput{return {rootSeed:seed,generatorVersion:'v9',environment:environmentProfile,assignedRooms,embeddedRooms,corridors,doorways,boundaries,navigation};}

describe('Catacombs construction records',()=>{
 test('all room construction profiles are covered',()=>{expect(CATACOMBS_ROOM_CONSTRUCTION_PROFILES).toHaveLength(20); expect(CATACOMBS_ROOM_CONSTRUCTION_PROFILES.map(p=>p.id)).toContain('catacombs.construction_profile.boss_sepulcher');});
 test('stable construction IDs and structural records are generated',()=>{const a=generateCatacombsConstruction(input()); const b=generateCatacombsConstruction(input()); expect(a.canonicalProjection).toBe(b.canonicalProjection); expect(a.records.map(r=>r.id)).toEqual(expect.arrayContaining(['room.room.entrance.floor.0','corridor.edge.0.floor.0','doorway.edge.0.room.entrance.arch','doorway.edge.0.room.boss.gate'])); expect(a.records.some(r=>r.category==='wall'&&r.source.doorwayId)).toBe(false);});
 test('columns, ceilings, props, fixtures, decals, effects, sockets and batches are emitted',()=>{const r=generateCatacombsConstruction(input()); expect(r.records.some(x=>x.category==='column')).toBe(true); expect(r.records.some(x=>x.category==='ceiling')).toBe(true); expect(r.records.some(x=>x.category==='prop'&&x.propBehavior==='HARD_BLOCKER')).toBe(true); expect(r.records.some(x=>x.category==='fixture')).toBe(true); expect(r.records.some(x=>x.category==='decal')).toBe(true); expect(r.records.some(x=>x.category==='effect anchor')).toBe(true); expect(r.sockets.some(s=>s.type==='gameplay_reserved')).toBe(true); expect(r.batches.length).toBeGreaterThan(0);});
 test('navigation revalidation and workbench adapters report deterministic safe output',()=>{const r=generateCatacombsConstruction(input()); expect(r.diagnostics.navigationRevalidation).toMatchObject({criticalPathPreserved:true,isolatedWalkableRegions:0,doorwayClearancePreserved:true,bossArenaClearancePreserved:true,initialReachabilityPreserved:true,finalReachabilityPreserved:true,gameplayReservedRegionsUnoccupied:true}); const view=buildConstructionWorkbenchAdapters(r); expect(view.spatialInspector.recordCount).toBe(r.records.length); expect(view.assetInspector.records.length).toBe(r.records.length);});
 test('100 seed deterministic sweep is byte stable and all assets resolve to allowed states',()=>{for(let i=0;i<100;i++){const a=generateCatacombsConstruction(input(`seed-${i}`)); const b=generateCatacombsConstruction(input(`seed-${i}`)); expect(a.canonicalProjection).toBe(b.canonicalProjection); expect(a.records.length).toBeGreaterThan(0); expect(a.records.every(r=>['AUTHORED','FALLBACK','PLACEHOLDER'].includes(r.assetResolutionState))).toBe(true); expect(a.diagnostics.navigationRevalidation.criticalPathPreserved).toBe(true); expect(a.records.filter(r=>r.category==='wall').every(r=>!r.source.doorwayId)).toBe(true);}});

 test('profile validation, prop taxonomy, clusters, costs and benchmark counters are populated',()=>{const r=generateCatacombsConstruction(input('42')); const validation=validateCatacombsConstructionProfiles(); expect(validation).toEqual({valid:true,issues:[]}); expect(CATACOMBS_PROP_DEFINITIONS.length).toBeGreaterThanOrEqual(27); expect(CATACOMBS_PROP_CLUSTERS.map(c=>c.id)).toEqual(expect.arrayContaining(['catacombs.prop_cluster.ritual_arrangement.standard_01','catacombs.prop_cluster.boss_arena_perimeter.standard_01'])); expect(PROP_SPATIAL_BEHAVIOR_DEFINITIONS.INTERACTABLE).toContain('no mutable interaction'); expect(r.diagnostics.costEstimate.estimatedDrawCalls).toBeGreaterThan(0); expect(r.benchmarks.boundaryMergeOps).toBeGreaterThan(0); expect(r.benchmarks.canonicalSerializationBytes).toBe(r.canonicalProjection.length);});
 test('runtime LOD changes do not alter canonical construction identity',()=>{const a=generateCatacombsConstruction(input('lod')); const b=generateCatacombsConstruction(input('lod')); expect(a.records.map(r=>[r.id,r.resolvedAssetId,r.assetResolutionState])).toEqual(b.records.map(r=>[r.id,r.resolvedAssetId,r.assetResolutionState]));});
});
