import { buildGameplayTransformationWorkbenchView, DIFFICULTY_PROFILES, GAMEPLAY_TRANSFORMATION_VERSION, GAME_TYPE_PROFILES, PLAYER_SCALING_PROFILE, transformCatacombsGameplay, validateEnvironmentGameTypeCompatibility, validateTransformationProfiles } from '../../src/dungeon/index.js';
import { dungeonConfig as cfg, environmentProfile } from './fixtures/fixtures.js';
import { generateCatacombsGameplay } from '../../src/dungeon/gameplay.js';

function base(seed='42'){const assignedRooms=[{nodeId:'room.entrance',graphNodeId:'room.entrance',archetypeId:'catacombs.mausoleum_entrance',roomFunction:'entrance'},{nodeId:'room.pass1',graphNodeId:'room.pass1',archetypeId:'catacombs.burial_passage',roomFunction:'combat'},{nodeId:'room.branch1',graphNodeId:'room.branch1',archetypeId:'catacombs.sealed_tomb',roomFunction:'secret'},{nodeId:'room.pass2',graphNodeId:'room.pass2',archetypeId:'catacombs.crypt_junction',roomFunction:'junction'},{nodeId:'room.obj',graphNodeId:'room.obj',archetypeId:'catacombs.gate_chamber',roomFunction:'objective'},{nodeId:'room.ante',graphNodeId:'room.ante',archetypeId:'catacombs.boss_antechamber',roomFunction:'antechamber'},{nodeId:'room.boss',graphNodeId:'room.boss',archetypeId:'catacombs.boss_sepulcher',roomFunction:'boss'}] as any[]; const embeddedRooms=assignedRooms.map((a,i)=>({assignedRoom:a,footprint:{origin:{x:i*18,y:0,level:0},width:i===6?18:12,height:i===6?16:12,mask:new Uint8Array((i===6?18:12)*(i===6?16:12)).fill(1),bounds:{minimumX:i*18,minimumY:0,maximumX:i*18+(i===6?17:11),maximumY:i===6?15:11,level:0}}})) as any[]; const nav={width:160,height:30,initialMask:new Uint8Array(4800).fill(1),finalMask:new Uint8Array(4800).fill(1),distanceFromStart:new Int32Array(4800).fill(1),finalDistanceFromStart:new Int32Array(4800).fill(1),clearance:new Uint16Array(4800).fill(3),unreachableSentinel:-1,initialReachableCells:4800,finalReachableCells:4800,regions:[],portals:[]} as any; return generateCatacombsGameplay({config:{...cfg,rootSeed:seed,authorizedPlayerCount:8},environment:environmentProfile,assignedRooms,embeddedRooms,corridors:[],sockets:[{id:'sock.branch',roomId:'room.branch1',reserved:true} as any],navigation:nav});}
function tx(gameType:any,difficulty:any,playerCount:number,seed='42'){return transformCatacombsGameplay(base(seed),{...cfg,gameType,difficulty,authorizedPlayerCount:playerCount,rootSeed:seed},environmentProfile);}

describe('Prompt 11 gameplay transformations',()=>{
 test('profiles validate and Hell difficulty cannot collide with Hells Canyon environment id',()=>{expect(validateTransformationProfiles().valid).toBe(true); expect(DIFFICULTY_PROFILES.hell.id).toBe('difficulty.hell'); expect(DIFFICULTY_PROFILES.hell.id).not.toBe('environment.hells_canyon'); expect(Object.keys(GAME_TYPE_PROFILES).sort()).toEqual(['endurance','hunt','speed_run']); expect(PLAYER_SCALING_PROFILE.curve[1]).toBeLessThan(PLAYER_SCALING_PROFILE.curve[8]);});
 test('compatibility is bidirectional and checks declared environment support plus generated capabilities',()=>{const gp=base(); const ok=validateEnvironmentGameTypeCompatibility(environmentProfile,'endurance',gp); expect(ok.compatible).toBe(true); expect(ok.environmentCapabilities).toEqual(expect.arrayContaining(['HAS_BOSS_ARENA','HAS_REINFORCEMENT_SOCKETS','HAS_RECOVERY_REGIONS'])); const denied=validateEnvironmentGameTypeCompatibility({...environmentProfile,compatibility:{...environmentProfile.compatibility,endurance:false}},'endurance',gp); expect(denied.compatible).toBe(false); expect(denied.issues.map(i=>i.code)).toContain('INCOMPATIBLE_ENVIRONMENT_GAME_TYPE');});
 test('applies locked request order with complete stable provenance',()=>{const plan=tx('hunt','expert',4); expect(plan.transformationRequest.transformationVersion).toBe(GAMEPLAY_TRANSFORMATION_VERSION); expect(plan.validation.gates.ordering).toBe(true); expect(plan.provenance.length).toBeGreaterThan(plan.encounters.length); for(const p of plan.provenance){expect(p.sourceRecordIds.length).toBeGreaterThan(0); expect(p.profileVersions).toEqual(expect.arrayContaining([GAME_TYPE_PROFILES.hunt.version,DIFFICULTY_PROFILES.expert.version,PLAYER_SCALING_PROFILE.version])); expect(p.operations.every(o=>o.id.startsWith('op.'))).toBe(true);} });
 test('rejects player counts outside 1-8 before transformation',()=>{expect(()=>tx('hunt','normal',0)).toThrow('INVALID_PLAYER_COUNT'); expect(()=>tx('hunt','normal',9)).toThrow('INVALID_PLAYER_COUNT');});
 test('Speed Run preserves critical-path behavior and declarative timing points',()=>{const plan=tx('speed_run','normal',1); expect(plan.playerStarts).toHaveLength(1); expect(plan.speedRun?.map(s=>s.kind)).toEqual(expect.arrayContaining(['RUN_START','TIMER_START_TRIGGER','FINAL_BOSS_SPLIT','FINISH_TRIGGER'])); expect(plan.encounters.filter(e=>e.mandatory).length).toBeLessThanOrEqual(GAME_TYPE_PROFILES.speed_run.maxPathDensity); expect(plan.bosses.some(b=>b.relationship==='FINAL_TIMING_SPLIT')).toBe(true);});
 test('Hunt distributes targets and keeps final boss as final marked target without live kill counts',()=>{const plan=tx('hunt','hell',8); expect(plan.huntTargets?.length).toBeGreaterThanOrEqual(3); expect(plan.huntTargets?.some(t=>t.targetSequencePolicy==='FINAL_TARGET_LAST'&&t.targetCategory==='BOSS')).toBe(true); expect(plan.canonicalBytes).not.toMatch(/kill|killed|currentHealth|elapsedTime|claimedRewards/);});
 test('Endurance creates immutable stages, routed reinforcements, and recovery cadence',()=>{const plan=tx('endurance','hard',6); expect(plan.enduranceStages?.length).toBeGreaterThan(0); for(const s of plan.enduranceStages??[]){expect(s.waveDefinitions.length).toBeGreaterThan(0); expect(s.reinforcementDefinitions.every(r=>r.routeValid)).toBe(true); expect(s.recoveryRelationship).toMatch(/RECOVERY_/);} expect(plan.canonicalBytes).not.toMatch(/currentWave|currentBossPhase|runtimeEntity/);});
 test('difficulty and player scaling increase pressure while clamping active actors to capacity',()=>{const normal=tx('hunt','normal',1), hell=tx('hunt','hell',8); expect(hell.statistics.totalEncounterBudget as number).toBeGreaterThan(normal.statistics.totalEncounterBudget as number); expect(hell.encounters.every(e=>e.composition.activeActors<=PLAYER_SCALING_PROFILE.maxActiveActors)).toBe(true); expect(hell.statistics.reinforcementReserve as number).toBeGreaterThan(normal.statistics.reinforcementReserve as number);});
 test('canonical serialization and diagnostics are deterministic and independent',()=>{const a=tx('endurance','nightmare',5,'77'), b=tx('endurance','nightmare',5,'77'); expect(a.canonicalBytes).toBe(b.canonicalBytes); expect(a.canonicalChecksum).toBe(b.canonicalChecksum); const view=buildGameplayTransformationWorkbenchView(a); expect(a.canonicalBytes).toBe(b.canonicalBytes); expect(view.transformationInspector.comparisons).toEqual(['BASE','AFTER_GAME_TYPE','AFTER_DIFFICULTY','AFTER_PLAYER_COUNT','FINAL']); expect(view.transformationInspector.reinforcementWaves.length).toBeGreaterThan(0);});
 test('reward presentations stay presentation-only and graph/spatial topology is not represented as mutable output',()=>{const plan=tx('speed_run','hell',8); expect(plan.rewardPresentations.every(r=>r.containsAuthorizedLoot===false && !('claimPolicy' in r))).toBe(true); expect(plan.validation.gates.topologyImmutable).toBe(true); expect(plan.validation.gates.spatialImmutable).toBe(true);});
 test('smoke combination suite covers game types, Normal/Hell, 1/8 players, and fixed seeds',()=>{let count=0; for(const g of ['speed_run','hunt','endurance'] as const) for(const d of ['normal','hell'] as const) for(const p of [1,8]) for(const seed of ['101','202','303']){const plan=tx(g,d,p,seed); count++; expect(plan.validation.valid).toBe(true); expect(plan.playerStarts).toHaveLength(p); expect(plan.canonicalChecksum).toMatch(/^[a-f0-9]{64}$/); expect(plan.validation.gates.rewardAuthority).toBe(true);} expect(count).toBe(36);});
 test('full 12000 matrix harness is expressed without claiming local execution',()=>{const gameTypes=['speed_run','hunt','endurance']; const difficulties=['normal','hard','expert','nightmare','hell']; const players=[1,2,3,4,5,6,7,8]; const seeds=Array.from({length:100},(_,i)=>String(1000+i)); expect(gameTypes.length*difficulties.length*players.length*seeds.length).toBe(12000);});
});
