import { dungeonConfig, environmentProfile } from './fixtures/fixtures.js';
import { buildAdjacency, buildCatacombsGraphWorkbenchView, CATACOMBS_GRAPH_ALGORITHM_VERSION, CATACOMBS_GRAPH_DIAGNOSTIC_CODES, connectedComponents, cycleRank, generateCatacombsGraph, resolveCatacombsGraphConfig, shortestPath, validateCatacombsGraph, articulationAndBridges, canonicalStringify, createRngStream } from '../../src/dungeon/index.js';
const cfg={...dungeonConfig,rootSeed:'12345',generatorVersion:'catacombs-gen-1'};
function must(overrides={}){const r=generateCatacombsGraph({config:cfg,environment:environmentProfile,graph:overrides}); expect(r.ok).toBe(true); return r as Extract<typeof r,{ok:true}>;}
describe('Catacombs layered braided graph generator',()=>{
 test('primary trunk anchors boss sequence and depth',()=>{const r=must(); expect(CATACOMBS_GRAPH_ALGORITHM_VERSION).toContain('layered_braided'); const starts=r.graph.nodes.filter(n=>n.tags.includes('semantic:start')); const finishes=r.graph.nodes.filter(n=>n.tags.includes('semantic:finish')); expect(starts).toHaveLength(1); expect(finishes).toHaveLength(1); expect(r.graph.criticalPathNodeIds[0]).toBe(starts[0]!.id); expect(r.graph.criticalPathNodeIds.at(-1)).toBe(finishes[0]!.id); const ante=r.graph.nodes.find(n=>n.tags.includes('semantic:boss-approach'))!; expect(r.graph.edges.some(e=>e.fromNodeId===ante.id&&e.toNodeId===finishes[0]!.id)).toBe(true); expect(r.criticalPaths.initial.length).toBeGreaterThanOrEqual(6); expect(r.metrics.primaryTrunkNodes).toBeLessThan(r.metrics.nodeCount); expect(r.metrics.depthLayerOccupancy['0']).toBe(1); expect(r.metrics.criticalPathLength).toBe(r.criticalPaths.initial.length);});
 test('secondary trunks are real forward reconverging alternate routes',()=>{const r=must({secondaryTrunks:{min:2,max:2}}); const branches=r.graph.branches.filter(b=>b.kind==='secondary_trunk'); expect(branches).toHaveLength(2); for(const b of branches){expect(b.nodeIds.length).toBeGreaterThanOrEqual(3); const div=r.graph.nodes.find(n=>n.id===b.divergenceNodeId)!; const rec=r.graph.nodes.find(n=>n.id===b.reconvergenceNodeId)!; expect(rec.depthLayer).toBeGreaterThan(div.depthLayer); expect(b.nodeIds.slice(1,-1).length).toBeGreaterThan(0);} expect(r.metrics.maximumDegree).toBeLessThanOrEqual(4);});
 test('immediate conditional secret loops and dead ends have metadata',()=>{const r=must({conditionalLoops:{min:1,max:1},secretBranches:{min:1,max:1},secretLoops:{min:1,max:1}}); expect(r.metrics.immediateLoopCount).toBeGreaterThanOrEqual(1); expect(r.metrics.cycleRank).toBe(cycleRank(r.graph,e=>e.initialState==='open'&&e.category!=='secret'&&e.criticality!=='secret')); expect(r.graph.edges.filter(e=>e.initialState==='locked')).toEqual(expect.arrayContaining([expect.objectContaining({dependencyId:expect.stringContaining('unlock.condition'),criticality:'return'})])); expect(r.graph.edges.some(e=>e.initialState==='secret')).toBe(true); const secrets=r.graph.branches.filter(b=>b.kind==='secret_loop'||b.purpose==='secret_reward'); expect(secrets.length).toBeGreaterThan(0); const dead=r.graph.branches.filter(b=>b.kind==='dead_end'&&b.purpose!=='secret_reward'); expect(dead).toHaveLength(r.metrics.deadEndCount); expect(dead.every(b=>b.purpose)).toBe(true);});
 test('graph analysis utilities are deterministic on generated graph',()=>{const r=must(); expect(connectedComponents(r.graph)).toHaveLength(1); const start=r.graph.criticalPathNodeIds[0]!, finish=r.graph.criticalPathNodeIds.at(-1)!; expect(shortestPath(r.graph,start,finish)?.nodeIds).toEqual(r.criticalPaths.initial.nodeIds); expect([...buildAdjacency(r.graph).keys()].sort()).toEqual(r.graph.nodes.map(n=>n.id).sort()); const ab=articulationAndBridges(r.graph); expect(ab.articulationPointIds).toEqual([...ab.articulationPointIds].sort()); expect(r.metrics.articulationPointCount).toBe(ab.articulationPointIds.length);});
 test('hard validation returns stable diagnostic codes',()=>{const r=must(); const noStart={...r.graph,nodes:r.graph.nodes.map(n=>n.tags.includes('semantic:start')?{...n,tags:[]}:n)}; expect(validateCatacombsGraph(noStart,resolveCatacombsGraphConfig(cfg).config!,r.loops).map(i=>i.code)).toContain('GRAPH_PRIMARY_START_INVALID'); const badEdge={...r.graph,edges:[...r.graph.edges,{...r.graph.edges[0]!,id:'edge.bad.999',toNodeId:'missing'}]}; expect(validateCatacombsGraph(badEdge,resolveCatacombsGraphConfig(cfg).config!,r.loops).map(i=>i.code)).toContain('GRAPH_EDGE_ENDPOINT_MISSING'); expect(CATACOMBS_GRAPH_DIAGNOSTIC_CODES).toContain('GRAPH_BOSS_BYPASS');});
 test('candidate selection and determinism are stable and isolated',()=>{const a=must(), b=must(); expect(canonicalStringify(a.graph as never)).toBe(canonicalStringify(b.graph as never)); expect(a.metrics.acceptedCandidateIndex).toBe(b.metrics.acceptedCandidateIndex); expect(createRngStream('12345','catacombs-gen-1','props').nextUint32()).toBe(createRngStream('12345','catacombs-gen-1','props').nextUint32()); const impossible=generateCatacombsGraph({config:cfg,environment:environmentProfile,graph:{targetNodeCount:9,minNodeCount:9,maxNodeCount:9,secondaryTrunks:{min:9,max:9}}}); expect(impossible.ok).toBe(false); if(!impossible.ok) expect(impossible.diagnostics.issues.map(i=>i.code)).toContain('GRAPH_CONFIG_INVALID');});
 test('100-seed pull request suite succeeds across profiles',()=>{const qualities:number[]=[], retries:number[]=[], loops:number[]=[], deads:number[]=[], arts:number[]=[]; for(let i=1;i<=100;i++){const r=generateCatacombsGraph({config:{...cfg,rootSeed:String(i)},environment:environmentProfile,graph:{sizeProfile:i%3===0?'small':i%3===1?'medium':'large',conditionalLoops:{min:i%10===0?1:0,max:1},secretBranches:{min:i%11===0?1:0,max:1},secretLoops:{min:i%13===0?1:0,max:1}}}); expect(r.ok).toBe(true); if(r.ok){expect(r.metrics.connectedComponents).toBe(1); expect(r.metrics.immediateLoopCount).toBeGreaterThanOrEqual(1); expect(r.metrics.finalQualityScore).toBeGreaterThanOrEqual(.55); expect(r.metrics.nodeCount).toBe(r.graph.nodes.length); expect(generateCatacombsGraph({config:{...cfg,rootSeed:String(i)},environment:environmentProfile,graph:{sizeProfile:i%3===0?'small':i%3===1?'medium':'large',conditionalLoops:{min:i%10===0?1:0,max:1},secretBranches:{min:i%11===0?1:0,max:1},secretLoops:{min:i%13===0?1:0,max:1}}})).toEqual(r); qualities.push(r.metrics.finalQualityScore); retries.push(r.diagnostics.metrics.retryCount); loops.push(r.metrics.immediateLoopCount); deads.push(r.metrics.deadEndCount); arts.push(r.metrics.articulationPointCount);}} expect({successRate:1,retryMax:Math.max(...retries),qualityMin:Math.min(...qualities),loopMin:Math.min(...loops),deadEndMin:Math.min(...deads),articulationMax:Math.max(...arts)}).toMatchSnapshot();});
 test('workbench adapter consumes production analysis',()=>{const r=must(); const view=buildCatacombsGraphWorkbenchView(r); expect(view.primaryTrunk).toEqual(r.graph.criticalPathNodeIds); expect(view.secondaryTrunks.length).toBe(r.metrics.secondaryTrunkCount); expect(view.metrics.finalQualityScore).toBe(r.metrics.finalQualityScore);});
});
