import { assignCatacombsRooms, buildCatacombsSpatialWorkbenchView, canonicalStringify, CATACOMBS_SHAPE_MASK_VERSION, CATACOMBS_SPATIAL_ALGORITHM_VERSION, CATACOMBS_SPATIAL_DIAGNOSTIC_CODES, detectRoomOverlaps, embedCatacombsRooms, generateCatacombsGraph, realizeRoomShape, analyzeRoomMask } from '../../src/dungeon/index.js';
import { dungeonConfig, environmentProfile } from './fixtures/fixtures.js';
const cfg={...dungeonConfig,generatorVersion:'catacombs-gen-1'};
function spatial(seed='12345', graphOverrides={}){const g=generateCatacombsGraph({config:{...cfg,rootSeed:seed},environment:environmentProfile,graph:graphOverrides}); expect(g.ok).toBe(true); const gg=g as Extract<typeof g,{ok:true}>; const a=assignCatacombsRooms({config:{...cfg,rootSeed:seed},environment:environmentProfile,graph:gg.graph,branches:gg.branches,depthLayers:gg.depthLayers,graphMetrics:gg.metrics}); expect(a.ok).toBe(true); const aa=a as Extract<typeof a,{ok:true}>; const s=embedCatacombsRooms({config:{...cfg,rootSeed:seed},environment:environmentProfile,graph:gg.graph,branches:gg.branches,depthLayers:gg.depthLayers,assignedRooms:aa.assignedRooms}); expect(s.ok).toBe(true); return {g:gg,a:aa,s:s as Extract<typeof s,{ok:true}>};}
describe('Catacombs spatial embedding and room footprint realization',()=>{
 test('supported shape masks are connected row-major Uint8 masks',()=>{expect(CATACOMBS_SHAPE_MASK_VERSION).toContain('row_major_u8'); for(const shape of ['rectangle','square','ellipse','circle','octagon','cross','l-shape','t-shape','ring','gallery','irregular','prefab'] as const){const r=realizeRoomShape(shape,14,14); expect(r.mask).toBeInstanceOf(Uint8Array); expect(r.mask).toHaveLength(196); expect(r.mask.reduce((a,b)=>a+(b===1?1:0),0)).toBeGreaterThan(0); const c=analyzeRoomMask(r.mask,14,14); expect(c.contiguousInteriorRegionSizes[0]).toBeGreaterThan(0); expect(c.validApproachSides.length).toBeGreaterThan(0);}});
 test('embeds graph anchors, lanes, dimensions, padding and approaches',()=>{const {g,s}=spatial('12345',{secondaryTrunks:{min:2,max:2},conditionalLoops:{min:1,max:1},secretBranches:{min:1,max:1}}); expect(CATACOMBS_SPATIAL_ALGORITHM_VERSION).toContain('spatial_embedding'); expect(s.embeddedRooms).toHaveLength(g.graph.nodes.length); expect(s.embeddedRooms.find(r=>r.assignedRoom.function==='entrance')!.graphAnchor.y).toBe(0); expect(s.embeddedRooms.find(r=>r.assignedRoom.function==='boss')!.graphAnchor.y).toBeGreaterThan(0); expect(new Set(s.embeddedRooms.map(r=>r.branchLane)).size).toBeGreaterThan(1); expect(s.metrics.directOverlaps).toBe(0); expect(s.metrics.paddingViolations).toBe(0); expect(s.metrics.boundaryViolations).toBe(0); expect(s.metrics.unauthorizedContacts).toBe(0); expect(s.metrics.doorCandidateCount).toBeGreaterThan(g.graph.edges.length); expect(s.metrics.edgesWithNoFeasibleApproaches).toBe(0); expect(s.connectionApproaches.length).toBe(g.graph.edges.length*2); expect(s.padding.paddedCells.length).toBeGreaterThan(0);});
 test('landmark dimensions preserve entrance staging and boss clearance',()=>{const {s}=spatial(); const entrance=s.embeddedRooms.find(r=>r.assignedRoom.archetypeId.endsWith('mausoleum-entrance'))!; const boss=s.embeddedRooms.find(r=>r.assignedRoom.archetypeId.endsWith('boss-sepulcher'))!; expect(entrance.footprint.width).toBeGreaterThanOrEqual(16); expect(entrance.clearanceSummary.entranceStagingFeasible).toBe(true); expect(entrance.clearanceSummary.entranceStagingCapacityEstimate).toBeGreaterThanOrEqual(8); expect(boss.footprint.width).toBeGreaterThanOrEqual(18); expect(boss.clearanceSummary.bossClearanceFeasible).toBe(true);});
 test('exact overlap detector uses masks, not only AABBs',()=>{const {s}=spatial(); expect(detectRoomOverlaps(s.embeddedRooms)).toHaveLength(0); const a=s.embeddedRooms[0]!, b={...s.embeddedRooms[1]!,footprint:{...s.embeddedRooms[1]!.footprint,origin:s.embeddedRooms[0]!.footprint.origin,bounds:s.embeddedRooms[0]!.footprint.bounds}}; expect(detectRoomOverlaps([a,b])).not.toHaveLength(0);});
 test('structured failures reject invalid config and exhausted lanes',()=>{const {g,a}=spatial(); const bad=embedCatacombsRooms({config:cfg,environment:environmentProfile,graph:g.graph,branches:g.branches,depthLayers:g.depthLayers,assignedRooms:a.assignedRooms,spatial:{roomPadding:4,landmarkPadding:1}}); expect(bad.ok).toBe(false); if(!bad.ok) expect(bad.diagnostics.issues.map(i=>i.code)).toContain('SPATIAL_CONFIG_INVALID'); const lanes=embedCatacombsRooms({config:cfg,environment:environmentProfile,graph:g.graph,branches:g.branches,depthLayers:g.depthLayers,assignedRooms:a.assignedRooms,spatial:{maximumLaneCount:1}}); expect(lanes.ok).toBe(false);});
 test('deterministic canonical spatial data and workbench adapter summaries',()=>{const a=spatial('42').s, b=spatial('42').s; const project=(x:typeof a)=>x.embeddedRooms.map(r=>({id:r.assignedRoom.nodeId,anchor:r.graphAnchor,lane:r.branchLane,origin:r.footprint.origin,w:r.footprint.width,h:r.footprint.height,shape:r.footprint.shape,mask:Array.from(r.footprint.mask)})); expect(canonicalStringify(project(a) as never)).toBe(canonicalStringify(project(b) as never)); const view=buildCatacombsSpatialWorkbenchView(a); expect(view.roomFootprints).toHaveLength(a.embeddedRooms.length); expect(view.occupancy.cellCount).toBe(a.metrics.totalOccupiedRoomCells);});
 test('100-seed graph-room-spatial suite reports stable distributions',()=>{const qualities:number[]=[], areas:number[]=[], lanes:number[]=[], lengths:number[]=[], attempts:number[]=[]; for(let i=1;i<=100;i++){const {s,g}=spatial(String(i),{sizeProfile:i%3===0?'small':i%3===1?'medium':'large',conditionalLoops:{min:i%10===0?1:0,max:1},secretBranches:{min:i%11===0?1:0,max:1},secretLoops:{min:i%13===0?1:0,max:1}}); expect(s.embeddedRooms).toHaveLength(g.graph.nodes.length); expect(s.metrics.directOverlaps).toBe(0); expect(s.metrics.boundaryViolations).toBe(0); expect(s.metrics.finalSpatialQualityScore).toBeGreaterThanOrEqual(.45); expect(s.embeddedRooms.find(r=>r.assignedRoom.function==='antechamber')!.graphAnchor.y).toBeLessThan(s.embeddedRooms.find(r=>r.assignedRoom.function==='boss')!.graphAnchor.y); qualities.push(s.metrics.finalSpatialQualityScore); areas.push(s.metrics.boundingArea); lanes.push(s.metrics.laneCount); lengths.push(s.metrics.predictedCorridorLength); attempts.push(s.metrics.acceptedCandidateIndex);} expect({successRate:1,qualityMin:Math.min(...qualities),qualityMax:Math.max(...qualities),areaMin:Math.min(...areas),areaMax:Math.max(...areas),laneMax:Math.max(...lanes),predictedLengthMax:Math.max(...lengths),acceptedCandidates:[...new Set(attempts)]}).toMatchSnapshot();});
 test('stable diagnostic code registry includes Phase 5 blockers',()=>{expect(CATACOMBS_SPATIAL_DIAGNOSTIC_CODES).toEqual(expect.arrayContaining(['SPATIAL_ROOM_OVERLAP','SPATIAL_PADDING_VIOLATION','SPATIAL_CONNECTION_APPROACH_MISSING','SPATIAL_CANDIDATES_EXHAUSTED']));});
});
