import type { PackedRoom, RoomFootprint, SpatialCandidateEdge } from '../../../src/dungeon/spatialEmbedding.js';
export function occupiedCells(fp:RoomFootprint){const out:string[]=[]; for(let y=0;y<fp.height;y++)for(let x=0;x<fp.width;x++)if(fp.mask[y*fp.width+x])out.push(`${fp.origin.x+x},${fp.origin.y+y}`); return out;}
export function exactFootprintOverlap(a:RoomFootprint,b:RoomFootprint){const s=new Set(occupiedCells(a)); return occupiedCells(b).filter(c=>s.has(c));}
export function paddingConflictCells(a:PackedRoom,b:PackedRoom){const p=Math.max(a.padding,b.padding), out:string[]=[]; const ac=new Set(occupiedCells(a.footprint)), bc=new Set(occupiedCells(b.footprint)); for(const c of ac){const [x,y]=c.split(',').map(Number); for(let yy=y-p;yy<=y+p;yy++)for(let xx=x-p;xx<=x+p;xx++)if(!ac.has(`${xx},${yy}`)&&bc.has(`${xx},${yy}`))out.push(`${xx},${yy}`);} for(const c of bc){const [x,y]=c.split(',').map(Number); for(let yy=y-p;yy<=y+p;yy++)for(let xx=x-p;xx<=x+p;xx++)if(!bc.has(`${xx},${yy}`)&&ac.has(`${xx},${yy}`))out.push(`${xx},${yy}`);} return [...new Set(out)].sort();}
export function connected(nodes:readonly string[],edges:readonly Pick<SpatialCandidateEdge,'a'|'b'>[]){if(nodes.length===0)return true; const adj=new Map(nodes.map(n=>[n,[] as string[]])); for(const e of edges){adj.get(e.a)?.push(e.b); adj.get(e.b)?.push(e.a);} const seen=new Set<string>(), stack=[nodes[0]!]; while(stack.length){const n=stack.pop()!; if(seen.has(n))continue; seen.add(n); for(const m of adj.get(n)??[])stack.push(m);} return seen.size===nodes.length;}
export function hasCycle(nodes:readonly string[],edges:readonly Pick<SpatialCandidateEdge,'a'|'b'>[]){const parent=new Map(nodes.map(n=>[n,n])); const find=(x:string):string=>{const p=parent.get(x)!; if(p===x)return x; const r=find(p); parent.set(x,r); return r;}; for(const e of edges){const a=find(e.a),b=find(e.b); if(a===b)return true; parent.set(a,b);} return false;}
export function validateMst(nodes:readonly string[],edges:readonly Pick<SpatialCandidateEdge,'a'|'b'>[]){return edges.length===Math.max(0,nodes.length-1)&&connected(nodes,edges)&&!hasCycle(nodes,edges);}
export function stableCore(o:unknown){return JSON.stringify(o,(_,v)=>v instanceof Uint8Array?Array.from(v):v);}
export function assertNoRoomOverlap(rooms:readonly PackedRoom[]){for(let i=0;i<rooms.length;i++)for(let j=i+1;j<rooms.length;j++)if(exactFootprintOverlap(rooms[i]!.footprint,rooms[j]!.footprint).length)throw new Error(`overlap ${rooms[i]!.candidateId} ${rooms[j]!.candidateId}`);}
export function floodFill(start:string, passable:Set<string>){const seen=new Set<string>(), stack=[start]; while(stack.length){const c=stack.pop()!; if(seen.has(c)||!passable.has(c))continue; seen.add(c); const [x,y]=c.split(',').map(Number); stack.push(`${x+1},${y}`,`${x-1},${y}`,`${x},${y+1}`,`${x},${y-1}`);} return seen;}
export function sampleStats(xs:number[]){const s=[...xs].sort((a,b)=>a-b); const q=(p:number)=>s[Math.min(s.length-1,Math.floor((s.length-1)*p))]??0; return {median:q(.5),p95:q(.95),p99:q(.99),max:s.at(-1)??0};}
