import type { CanonicalTypedArrayData } from '../contracts/index.js';
type Supported=Uint8Array|Int8Array|Uint16Array|Int16Array|Uint32Array|Int32Array|Float32Array|Float64Array;
const types=['Uint8Array','Int8Array','Uint16Array','Int16Array','Uint32Array','Int32Array','Float32Array','Float64Array'] as const;
export function isSupportedTypedArray(v:unknown):v is Supported{return types.some(t=>Object.prototype.toString.call(v)===`[object ${t}]`);}
function b64(bytes:Uint8Array){if(typeof Buffer!=='undefined')return Buffer.from(bytes).toString('base64'); let binary=''; for(const b of bytes)binary+=String.fromCharCode(b); return btoa(binary);}
function fromB64(s:string){if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(s)) throw new TypeError('noncanonical base64'); if(typeof Buffer!=='undefined')return new Uint8Array(Buffer.from(s,'base64')); return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
export function encodeTypedArrayCanonical(view:Supported):CanonicalTypedArrayData{if(!isSupportedTypedArray(view)) throw new TypeError('unsupported typed array'); const type=view.constructor.name as CanonicalTypedArrayData['type']; const bytes=new Uint8Array(view.byteLength); const dv=new DataView(bytes.buffer); for(let i=0;i<view.length;i++){const n=view[i]!; if((type==='Float32Array'||type==='Float64Array')&&(!Number.isFinite(n)||Object.is(n,-0))) throw new TypeError('noncanonical float'); const off=i*view.BYTES_PER_ELEMENT; if(type==='Uint8Array')dv.setUint8(off,n); else if(type==='Int8Array')dv.setInt8(off,n); else if(type==='Uint16Array')dv.setUint16(off,n,true); else if(type==='Int16Array')dv.setInt16(off,n,true); else if(type==='Uint32Array')dv.setUint32(off,n,true); else if(type==='Int32Array')dv.setInt32(off,n,true); else if(type==='Float32Array')dv.setFloat32(off,n,true); else dv.setFloat64(off,n,true);} return {typedArray:true,type,endian:'little',length:view.length,byteLength:bytes.byteLength,base64:b64(bytes)};}
export function decodeTypedArrayCanonical(w:CanonicalTypedArrayData):Supported{if(w.typedArray!==true||w.endian!=='little'||!types.includes(w.type)) throw new TypeError('malformed typed-array wrapper'); const bytes=fromB64(w.base64); if(bytes.byteLength!==w.byteLength) throw new TypeError('byteLength mismatch'); const bytesPer={Uint8Array:1,Int8Array:1,Uint16Array:2,Int16Array:2,Uint32Array:4,Int32Array:4,Float32Array:4,Float64Array:8}[w.type]; if(w.length*bytesPer!==w.byteLength) throw new TypeError('length mismatch'); const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength); const arr:{[K in CanonicalTypedArrayData['type']]:new(n:number)=>Supported}={Uint8Array,Int8Array,Uint16Array,Int16Array,Uint32Array,Int32Array,Float32Array,Float64Array}; const out=new arr[w.type](w.length); for(let i=0;i<w.length;i++){const off=i*bytesPer; let n:number; if(w.type==='Uint8Array')n=dv.getUint8(off); else if(w.type==='Int8Array')n=dv.getInt8(off); else if(w.type==='Uint16Array')n=dv.getUint16(off,true); else if(w.type==='Int16Array')n=dv.getInt16(off,true); else if(w.type==='Uint32Array')n=dv.getUint32(off,true); else if(w.type==='Int32Array')n=dv.getInt32(off,true); else if(w.type==='Float32Array')n=dv.getFloat32(off,true); else n=dv.getFloat64(off,true); if(!Number.isFinite(n)||Object.is(n,-0)) throw new TypeError('noncanonical float'); out[i]=n;} return out;}
export function summarizeTypedArray(view:Supported,max=8){return {type:view.constructor.name,length:view.length,byteLength:view.byteLength,preview:Array.from(view.slice(0,max) as Uint8Array)}}
