import { id, normalizeSafeJson, AssetGeneratorRegistry, AssetEnvironmentPackRegistry, AssetRequirementRegistry, validateBudgetCeilings, CORE_ASSET_BUDGET_CEILINGS, validateVec3, validateBounds, validateLodPolicy, buildGeneratedPackageEnvelope } from '../../../../src/workbench/asset-forge/index.js';
import { parseVersion, AF_GENERATED_PACKAGE_SCHEMA_VERSION } from '../../../../src/workbench/asset-forge/core/versions.js';

const must=<T>(r:{ok:true;value:T}|{ok:false;error:unknown})=>{if(!r.ok)throw new Error(JSON.stringify(r.error));return r.value;};
const v=must(parseVersion<'GeneratorVersion'>('1.0.0','generator'));
const pv=must(parseVersion<'EnvironmentPackVersion'>('1.0.0','pack'));
const prof=must(parseVersion<'ProfileVersion'>('1.0.0','profile'));
const reqv=must(parseVersion<'AssetRequirementVersion'>('1.0.0','requirement'));
const budgetv=must(parseVersion<'BudgetProfileVersion'>('1.0.0','budget'));
const gen=must(id.generator('gen.core')); const fam=must(id.family('gen')); const cat=must(id.category('cat.wall')); const out=must(id.output('mesh.glb')); const cap=must(id.capability('cap.core')); const budget=must(id.budget('budget.core')); const pack=must(id.pack('pack.core')); const style=must(id.style('style.core')); const mat=must(id.material('mat.core')); const val=must(id.validation('validation.core'));
const descriptor={id:gen,version:v,familyId:fam,displayName:'Generator',supportedCategories:[cat],parameterSchema:{type:'object' as const,properties:{},required:[],additionalProperties:false as const},supportedOutputKinds:[out],requiredCapabilities:[cap],defaultBudgetProfileId:budget,determinism:{seedAffectsOutput:true,deterministicAcrossPlatforms:true,consumesDungeonRng:false as const,canonicalSerialization:'asset-forge-canonical-json-v1'},compatibility:{contractCompatibility:'EXACT' as const,supportedRecipeSchemaVersions:['1.0.0']},availability:'AVAILABLE' as const};

test('identifier validation rejects invalid and traversal-like input',()=>{expect(id.generator('../bad').ok).toBe(false);expect(id.generator('BadCase').ok).toBe(false);expect(id.generator('good.id-1').ok).toBe(true);});
test('duplicate generator registration is rejected and snapshots are immutable',()=>{const r=new AssetGeneratorRegistry();expect(r.register(descriptor).ok).toBe(true);expect(r.register(descriptor).ok).toBe(false);const snap=r.snapshot();expect(()=>((snap.descriptors as unknown as unknown[]).push(descriptor))).toThrow();expect(r.snapshot().descriptors).toHaveLength(1);});
test('environment-pack listing and binding resolution are registration-order independent',()=>{const b1={environmentPackId:pack,environmentPackVersion:pv,selector:{kind:'CATEGORY' as const,id:cat},generatorId:gen,supportedVersions:{min:v,max:v},defaultStyleProfileId:style,defaultMaterialProfileIds:[mat],allowlistedOverrideIds:[],budgetProfileId:budget,validationProfileId:val,priority:1,availability:'AVAILABLE' as const};const b2={...b1,priority:3};const pA={id:pack,version:pv,displayName:'Pack',status:'PARTIAL' as const,styleProfileIds:[style],materialProfileIds:[mat],requirementIds:[],generatorBindings:[b2,b1],validationProfileIds:[val],budgetProfileIds:[budget],exportProfileIds:[]};const pB={...pA,generatorBindings:[b1,b2]};const a=new AssetEnvironmentPackRegistry();const b=new AssetEnvironmentPackRegistry();expect(a.register(pA).ok).toBe(true);expect(b.register(pB).ok).toBe(true);const avail=new Map([[gen,[v] as const]]);expect(must(a.resolveBinding(pack,pv,cat,avail)).binding.priority).toBe(1);expect(JSON.stringify(a.snapshot())).toBe(JSON.stringify(b.snapshot()));});
test('missing requirement dependencies and cycles are reported',()=>{const rr=new AssetRequirementRegistry();const base:any={id:must(id.requirement('req.a')),version:reqv,environmentPackId:pack,environmentPackVersion:pv,categoryId:cat,displayName:'A',description:'A',required:true,spatial:{},requiredAnchors:[],requiredSockets:[],collision:{},lodPolicy:{levels:[]},budgetProfileId:budget,styleHintIds:[],materialHintIds:[],runtimePurpose:'PRESENTATION',gameplayReadability:'LOW',dependencyIds:[must(id.requirement('req.missing'))],acceptanceThresholdRef:'none',provenanceExpectations:[],requirementState:'REQUIRED',packageAcceptanceState:'NOT_SUBMITTED'};expect(rr.register(base).ok).toBe(true);expect(rr.reconcile().ok).toBe(false);const rr2=new AssetRequirementRegistry();const a={...base,dependencyIds:[must(id.requirement('req.b'))]};const b={...base,id:must(id.requirement('req.b')),dependencyIds:[must(id.requirement('req.a'))]};rr2.register(a);rr2.register(b);expect(rr2.reconcile().ok).toBe(false);});
test('requirement fallback cycles are rejected',()=>{const rr=new AssetRequirementRegistry();const a:any={id:must(id.requirement('req.fa')),version:reqv,environmentPackId:pack,environmentPackVersion:pv,categoryId:cat,displayName:'A',description:'A',required:true,spatial:{},requiredAnchors:[],requiredSockets:[],collision:{},lodPolicy:{levels:[]},budgetProfileId:budget,styleHintIds:[],materialHintIds:[],runtimePurpose:'PRESENTATION',gameplayReadability:'LOW',fallbackRequirementId:must(id.requirement('req.fb')),dependencyIds:[],acceptanceThresholdRef:'none',provenanceExpectations:[],requirementState:'REQUIRED',packageAcceptanceState:'NOT_SUBMITTED'};rr.register(a);rr.register({...a,id:must(id.requirement('req.fb')),fallbackRequirementId:must(id.requirement('req.fa'))});expect(rr.detectFallbackCycles().ok).toBe(false);});
test('pack budgets cannot weaken core ceilings',()=>{expect(validateBudgetCeilings({...CORE_ASSET_BUDGET_CEILINGS,vertices:CORE_ASSET_BUDGET_CEILINGS.vertices+1}).ok).toBe(false);});
test('non-finite vectors and bounds are rejected',()=>{expect(validateVec3([0,Infinity,0]).ok).toBe(false);expect(validateBounds({kind:'AABB',min:[1,0,0],max:[0,1,1]}).ok).toBe(false);});
test('invalid LOD thresholds are rejected',()=>{const l0=must(id.lod('lod.0'));const l1=must(id.lod('lod.1'));expect(validateLodPolicy({levels:[{id:l0,level:0,threshold:{kind:'DISTANCE_METERS',value:10},vertexTarget:1,triangleTarget:1,materialSimplification:'NONE',textureDownscale:1,collisionRelationship:'LOD0',shadowPolicy:'NONE',retainedAnchors:[],preserveSilhouette:true},{id:l1,level:1,threshold:{kind:'DISTANCE_METERS',value:5},vertexTarget:1,triangleTarget:1,materialSimplification:'NONE',textureDownscale:1,collisionRelationship:'LOD0',shadowPolicy:'NONE',retainedAnchors:[],preserveSilhouette:true}],fallback:'LOD0'}).ok).toBe(false);});
test('prototype-polluting and cyclic serialization input is rejected',()=>{expect(normalizeSafeJson(JSON.parse('{"__proto__":1}')).ok).toBe(false);const a:any={};a.self=a;expect(normalizeSafeJson(a).ok).toBe(false);});
test('generated-package builders cannot claim generated output without required evidence',()=>{const common:any={packageId:must(id.package('pkg.core')),schemaVersion:AF_GENERATED_PACKAGE_SCHEMA_VERSION,generator:{id:gen,version:v},environmentPack:{id:pack,version:pv},resolvedProfiles:{styleProfileId:style,materialProfileIds:[mat]},variantId:must(id.variant('variant.core')),seed:{value:'s',namespace:'n'},outputInventory:[],spatial:{},anchors:[],sockets:[],collision:{},lodPolicy:{levels:[]},metrics:{},budgetAssessment:'NOT_ASSESSED',validationRefs:[],provenanceRefs:[],licenseRefs:[],dependencies:[],integrity:[],creationStatus:'GENERATED_PENDING_VALIDATION',warnings:[],failures:[]};expect(buildGeneratedPackageEnvelope(common).ok).toBe(false);});

test('Asset Forge records do not alter canonical dungeon serialization',async()=>{const {generateCatacombs}=await import('../../../../src/dungeon/generationPipeline.js');const {config}=await import('../../fixtures/config.js');const {checksumResult}=await import('../../t1c/replay.js');const before=generateCatacombs({config:config('af-d2a-boundary')});const after=generateCatacombs({config:config('af-d2a-boundary')});expect(before.ok).toBe(true);expect(after.ok).toBe(true);if(before.ok&&after.ok)expect(checksumResult(after)).toBe(checksumResult(before));});
test('registry resolution consumes no Dungeon Generator RNG',async()=>{const {createRngStream}=await import('../../../../src/dungeon/determinism/rng.js');const rng=createRngStream('42','t1-test','construction');const before=rng.snapshot();const reg=new AssetEnvironmentPackRegistry();reg.resolveBinding(pack,pv,cat,new Map());expect(rng.snapshot()).toEqual(before);});
