import { normalizeSafeRelativePath,summarizeValidation,createHumanReviewRecord,applyAcceptanceTransition,RuntimeAssetRegistry,detectSupersessionCycle } from '../../../../src/workbench/asset-forge/index.js';
import type { IntegrityDigest } from '../../../../src/workbench/asset-forge/core/identifiers.js';
const d='sha256-1111111111111111111111111111111111111111111111111111111111111111' as IntegrityDigest;const d2='sha256-2222222222222222222222222222222222222222222222222222222222222222' as IntegrityDigest;const pol={policyVersion:'p',warningsBlockApproval:false};
const pass=summarizeValidation({runId:'r',subjectId:'s',subjectDigest:d,createdAt:'t',ruleVersions:['r@1'],findings:[],status:'PASS'},pol);const crit=summarizeValidation({runId:'r',subjectId:'s',subjectDigest:d,createdAt:'t',ruleVersions:['r@1'],findings:[{findingId:'f',ruleId:'r',ruleVersion:'1',status:'FAIL',severity:'CRITICAL',message:'x'}],status:'FAIL'},pol);const review=createHumanReviewRecord({reviewId:'rev',subjectId:'s',subjectDigest:d,reviewerIdentityRef:'human:1',reviewAuthority:'HUMAN_PLACEHOLDER_REVIEWER',reviewType:'PLACEHOLDER_ACCEPTANCE',decision:'APPROVE_PLACEHOLDER',findingsReviewed:[],createdAt:'t',policyVersion:'p',supersessionStatus:'CURRENT'});
test('missing validation is not a pass and critical findings block approval',()=>{expect(summarizeValidation(undefined,pol).approvalEligible).toBe(false);expect(crit.approvalEligible).toBe(false);});
test('unsafe export paths are rejected',()=>{for(const p of ['/abs.glb','../x.glb','a//b.glb','C:/x.glb','scripts/x.js','.'])expect(normalizeSafeRelativePath(p).ok).toBe(false);expect(normalizeSafeRelativePath('models/wall.glb').ok).toBe(true);});
test('review records are immutable and digest-bound',()=>{expect(Object.isFrozen(review)).toBe(true);const r:any=review;expect(()=>{r.decision='REJECT';}).toThrow();expect(review.subjectDigest).not.toBe(d2);});
test('direct approval, production approval, and approval without matching review are rejected',()=>{const rec={subjectId:'s',subjectDigest:d,state:'DRAFT' as const,transitions:[]};expect(applyAcceptanceTransition(rec,{commandId:'c1',subjectId:'s',subjectDigest:d,from:'DRAFT',to:'PLACEHOLDER_APPROVED',actorRef:'a',authority:'HUMAN_REVIEWER',policyVersion:'p',createdAt:'t'},pass,review).ok).toBe(false);const rp={...rec,state:'REVIEW_PENDING' as const};expect(applyAcceptanceTransition(rp,{commandId:'c2',subjectId:'s',subjectDigest:d,from:'REVIEW_PENDING',to:'PRODUCTION_APPROVED',actorRef:'a',authority:'PRODUCTION_REVIEWER',policyVersion:'p',createdAt:'t'},pass,review).ok).toBe(false);expect(applyAcceptanceTransition(rp,{commandId:'c3',subjectId:'s',subjectDigest:d,from:'REVIEW_PENDING',to:'PLACEHOLDER_APPROVED',actorRef:'a',authority:'HUMAN_REVIEWER',policyVersion:'p',createdAt:'t'},pass,undefined).ok).toBe(false);expect(applyAcceptanceTransition(rp,{commandId:'c4',subjectId:'s',subjectDigest:d,from:'REVIEW_PENDING',to:'PLACEHOLDER_APPROVED',actorRef:'a',authority:'HUMAN_REVIEWER',policyVersion:'p',createdAt:'t'},pass,review).ok).toBe(true);});
test('transition replay is idempotent and conflicting replay fails safely',()=>{const rec={subjectId:'s',subjectDigest:d,state:'VALIDATION_PENDING' as const,transitions:[]};const cmd={commandId:'same',subjectId:'s',subjectDigest:d,from:'VALIDATION_PENDING' as const,to:'VALIDATED' as const,actorRef:'v',authority:'VALIDATION_SERVICE' as const,policyVersion:'p',createdAt:'t'};const a=applyAcceptanceTransition(rec,cmd,pass);expect(a.ok).toBe(true);if(a.ok){expect(applyAcceptanceTransition(a.value,cmd,pass).ok).toBe(true);expect(applyAcceptanceTransition(a.value,{...cmd,to:'VALIDATION_FAILED'},crit).ok).toBe(false);}});
function entry(over:any={}){return{registryId:over.registryId??'a',registryVersion:'1.0.0',requirementId:over.requirementId??'req.a',environmentPackId:'pack.a',environmentPackVersion:'1.0.0',assetCategoryId:'cat.a',acceptanceState:over.acceptanceState??'PLACEHOLDER_APPROVED',runtimeKind:over.runtimeKind??'ASSET',runtimeModelRef:{path:'models/a.glb',mediaType:'model/gltf-binary'},anchors:[],sockets:[],integrityDigest:d,dependencyDigests:[],deprecated:false,license:{licenseRecordId:'l',licenseId:'MIT',classification:'SPDX',requiresAttribution:'NO',redistribution:'ALLOWED',modification:'ALLOWED',commercialUse:'ALLOWED',sourceDisclosure:'NOT_REQUIRED',reviewStatus:over.licenseStatus??'APPROVED'},validationSummaryRef:over.validationSummaryRef??'v',humanReviewRef:over.humanReviewRef??'h',compatibleRuntimeVersions:['1.0.0'],...over};}
test('runtime registry excludes revoked, unapproved, unresolved-license, and incompatible assets',()=>{const reg=new RuntimeAssetRegistry();for(const e of [entry({registryId:'rev',acceptanceState:'REVOKED'}),entry({registryId:'gen',acceptanceState:'GENERATED'}),entry({registryId:'lic',licenseStatus:'UNRESOLVED'}),entry({registryId:'inc',compatibleRuntimeVersions:['9.0.0']})])expect(reg.registerTrustedEntry(e).ok).toBe(true);expect(reg.resolve({requirementId:'req.a',environmentPackId:'pack.a',environmentPackVersion:'1.0.0',assetCategoryId:'cat.a',runtimeVersion:'1.0.0'}).selected).toBeUndefined();});
test('resolution is deterministic and snapshots cannot mutate registry state',()=>{const a=new RuntimeAssetRegistry();const b=new RuntimeAssetRegistry();const e1=entry({registryId:'b'}),e2=entry({registryId:'a'});a.registerTrustedEntry(e1);a.registerTrustedEntry(e2);b.registerTrustedEntry(e2);b.registerTrustedEntry(e1);const req={requirementId:'req.a',environmentPackId:'pack.a',environmentPackVersion:'1.0.0',assetCategoryId:'cat.a',runtimeVersion:'1.0.0'};expect(a.resolve(req).selected?.registryId).toBe(b.resolve(req).selected?.registryId);const snap=a.snapshot();expect(()=>((snap.entries as any).push(e1))).toThrow();expect(a.snapshot().entries).toHaveLength(2);});
test('supersession and runtime fallback cycles are rejected',()=>{expect(detectSupersessionCycle(new Map([['a','b'],['b','a']])).ok).toBe(false);const reg=new RuntimeAssetRegistry();expect(reg.registerTrustedEntry(entry({registryId:'fa',fallbackRegistryId:'fb'})).ok).toBe(true);expect(reg.registerTrustedEntry(entry({registryId:'fb',fallbackRegistryId:'fa'})).ok).toBe(false);});
test('runtime resolution and Asset Forge records do not mutate canonical dungeon placements or RNG',async()=>{const {generateCatacombs}=await import('../../../../src/dungeon/generationPipeline.js');const {config}=await import('../../fixtures/config.js');const {checksumResult}=await import('../../t1c/replay.js');const before=generateCatacombs({config:config('af-d2b-boundary')});const reg=new RuntimeAssetRegistry();reg.resolve({requirementId:'req.a',environmentPackId:'pack.a',environmentPackVersion:'1.0.0',assetCategoryId:'cat.a',runtimeVersion:'1.0.0'});const after=generateCatacombs({config:config('af-d2b-boundary')});expect(before.ok&&after.ok).toBe(true);if(before.ok&&after.ok)expect(checksumResult(after)).toBe(checksumResult(before));});
