import { deepFreeze } from './core/immutable.js';
import { diagnostic } from './core/diagnostics.js';
import { digestAssetForge } from './packages/packageIntegrity.js';
import { summarizeValidation, type ValidationRun } from './contracts/validation.js';
import type { GeneratedAssetPackageEnvelope } from './contracts/generatedPackage.js';
import { CATACOMBS_GEOMETRY_OUTPUT_KIND, CATACOMBS_PACK_ID, CATACOMBS_PACK_VERSION, ANCIENT_OSSUARY_PROFILE_ID, ANCIENT_OSSUARY_PROFILE_VERSION, CATACOMBS_REQUIREMENTS, CATACOMBS_GENERATORS } from './catacombsPack.js';
import { CATACOMBS_MATERIAL_OUTPUT_KIND, CATACOMBS_MATERIAL_GENERATOR_ID, CATACOMBS_MATERIAL_REQUIREMENTS, CATACOMBS_MATERIAL_PROFILES } from './catacombsMaterials.js';

export const ASSET_PREVIEW_CONTRACT_VERSION='af-d6.asset-preview.v1' as const;
export const ASSET_PREVIEW_IMPLEMENTATION_VERSION='impl.1.0.0' as const;
export type AssetReviewReadinessState='NOT_ADMITTED'|'BLOCKED_BY_VALIDATION'|'BLOCKED_BY_INTEGRITY'|'BLOCKED_BY_DEPENDENCY'|'BLOCKED_BY_PREVIEW_LIMIT'|'READY_FOR_HUMAN_REVIEW';
export interface AssetPreviewRequest{readonly candidate:GeneratedAssetPackageEnvelope&{readonly candidateKind?:string};readonly validationRun?:ValidationRun;readonly cameraPresetId?:string;readonly lightingPresetId?:string;readonly overlays?:readonly string[];readonly materialCandidate?:GeneratedAssetPackageEnvelope&{readonly candidateKind?:string};readonly signal?:{readonly aborted:boolean};}
export interface PreviewDiagnosticFinding{readonly findingId:string;readonly severity:'INFO'|'WARNING'|'ERROR'|'CRITICAL';readonly message:string;readonly blocksPreview:boolean;}
export interface PreviewResourceMetrics{readonly vertexCount:number;readonly indexCount:number;readonly materialSlotCount:number;readonly materialCount:number;readonly channelCount:number;readonly markerCount:number;readonly overlayCount:number;readonly serializedProjectionBytes:number;}
export interface AssetPreviewAdmissionResult{readonly admitted:boolean;readonly readiness:AssetReviewReadinessState;readonly diagnostics:readonly PreviewDiagnosticFinding[];readonly candidateDigest?:string;}
export interface AssetPreviewProjection{readonly contractVersion:typeof ASSET_PREVIEW_CONTRACT_VERSION;readonly geometry?:unknown;readonly materials:readonly unknown[];readonly overlays:readonly string[];readonly metrics:PreviewResourceMetrics;readonly digest:string;readonly approvalAuthority:false;readonly runtimeAuthority:false;}
export interface AssetPreviewSession{readonly sessionId:string;readonly candidatePackageId:string;readonly candidateDigest:string;readonly rendererContractVersion:typeof ASSET_PREVIEW_CONTRACT_VERSION;readonly previewImplementationVersion:typeof ASSET_PREVIEW_IMPLEMENTATION_VERSION;readonly cameraPresetId:string;readonly lightingPresetId:string;readonly enabledOverlays:readonly string[];readonly projectionDigest:string;readonly resourceMetrics:PreviewResourceMetrics;readonly reviewReadiness:AssetReviewReadinessState;readonly creationSource:'DETERMINISTIC_PACKAGE_EVIDENCE';}
export interface AssetInspectionReport{readonly contractVersion:typeof ASSET_PREVIEW_CONTRACT_VERSION;readonly packageId:string;readonly candidateDigest:string;readonly lifecycleState:string;readonly requirementId:string;readonly geometryMetrics:Readonly<Record<string,number>>;readonly materialMetrics:Readonly<Record<string,number>>;readonly bounds:unknown;readonly pivot:unknown;readonly anchors:readonly unknown[];readonly sockets:readonly unknown[];readonly collision:unknown;readonly lodPolicy:unknown;readonly materialSlots:readonly string[];readonly validationSummary:unknown;readonly integrity:readonly string[];readonly provenance:readonly string[];readonly governanceRestrictions:readonly string[];readonly previewLimitations:readonly string[];readonly blockingFindings:readonly PreviewDiagnosticFinding[];readonly warnings:readonly PreviewDiagnosticFinding[];readonly reviewReadiness:AssetReviewReadinessState;}
export interface AssetReviewObservation{readonly severity:'INFO'|'WARNING'|'ERROR';readonly category:'GEOMETRY'|'MATERIAL'|'VALIDATION'|'GOVERNANCE'|'ACCESSIBILITY'|'OTHER';readonly note:string;readonly suggestedDisposition:'NEEDS_CHANGES'|'REVIEW_INCOMPLETE'|'READY_FOR_APPROVAL_WORKFLOW_REVIEW';readonly reference?:string;}
export interface AssetReviewDraft{readonly contractVersion:typeof ASSET_PREVIEW_CONTRACT_VERSION;readonly candidatePackageId:string;readonly candidateDigest:string;readonly reviewerLabel:string;readonly observations:readonly AssetReviewObservation[];readonly inspectionReportDigest:string;readonly approvalAuthority:false;readonly runtimeAuthority:false;}
export interface PreviewComparisonResult{readonly compatible:boolean;readonly diagnostics:readonly PreviewDiagnosticFinding[];readonly differences:readonly string[];}
export const PREVIEW_CAMERA_PRESETS=deepFreeze(['isometric-inspection','front-orthographic','back-orthographic','left-orthographic','right-orthographic','top-orthographic','bottom-orthographic','perspective-turntable','detail-inspection'].map((id,i)=>({id,version:'1.0.0',index:i,bounded:true,remoteResources:false})));
export const PREVIEW_LIGHTING_PRESETS=deepFreeze(['neutral-studio','high-contrast-form','grazing-surface','flat-material','dark-catacombs-context','unlit-channel'].map((id,i)=>({id,version:'1.0.0',index:i,bounded:true,remoteEnvironmentMap:false})));
export const PREVIEW_BACKGROUNDS=deepFreeze(['neutral-light','neutral-dark','checker','grid','catacombs-neutral']);
export const PREVIEW_OVERLAYS=deepFreeze(['bounding-box','bounding-sphere','pivot','origin-axes','anchors','sockets','socket-direction','collision-intent','lod-identity','material-slots','uv-seams','traversal-clearance','doorway-interfaces','protected-placement-interfaces','validation-findings','budget-usage','geometry-statistics','material-channel-statistics']);
export const PREVIEW_BUDGETS=deepFreeze({vertices:20000,indices:60000,materialSlots:16,materials:16,channels:96,markers:128,overlays:18,serializedProjectionBytes:262144,reviewObservations:20,reviewTextLength:1000,comparisonCandidates:2});
function find(kind:string,msg:string,sev:'INFO'|'WARNING'|'ERROR'|'CRITICAL'='ERROR'):PreviewDiagnosticFinding{return{findingId:kind,severity:sev,message:msg,blocksPreview:sev==='ERROR'||sev==='CRITICAL'};}
function digest(v:unknown){const d=digestAssetForge('package',v);if(!d.ok)throw new Error(d.error.summary);return d.value;}
function jsonSafe(v:unknown){const s=JSON.stringify(v);return !/(https?:\/\/|shaderSource|function|THREE\.|WebGL|GPUTexture|PLACEHOLDER_APPROVED|PRODUCTION_APPROVED|runtimeEligible["']?\s*:\s*true|approval["']?\s*:\s*true|exportedFiles["']?\s*:\s*\[[^\]])/u.test(s);}
function isGeometry(c:GeneratedAssetPackageEnvelope){return c.outputInventory.some(x=>x.startsWith('asset.catacombs.req.'))&&c.generator.id!==CATACOMBS_MATERIAL_GENERATOR_ID;}
function reqId(c:GeneratedAssetPackageEnvelope){return c.recipeSnapshot?.requirementId??c.outputInventory.find(x=>x.includes('catacombs.req.'))?.replace(/^asset\.|^material\./u,'');}
export function admitAssetPreview(req:AssetPreviewRequest):AssetPreviewAdmissionResult{if(req.signal?.aborted)return deepFreeze({admitted:false,readiness:'NOT_ADMITTED',diagnostics:[find('preview.cancelled','Preview admission cancelled','WARNING')]});const c=req.candidate;const ds:PreviewDiagnosticFinding[]=[];if(c.schemaVersion!=='1.0.0')ds.push(find('schema.version','Unknown package schema version','CRITICAL'));
if(c.environmentPack.id!==CATACOMBS_PACK_ID||c.environmentPack.version!==CATACOMBS_PACK_VERSION)ds.push(find('pack.version','Unknown Catacombs environment-pack identity or version','CRITICAL'));
if(c.creationStatus!=='GENERATED_PENDING_VALIDATION'||(c as any).candidateKind!=='AF_D3_PACKAGE_CANDIDATE'||!Object.isFrozen(c))ds.push(find('candidate.immutable','Only immutable generated package candidates are admitted','CRITICAL'));
if(!c.integrity.length||!c.recipeDigest)ds.push(find('integrity.missing','Integrity evidence is incomplete','CRITICAL'));
if(!jsonSafe(c)||JSON.stringify(c).includes('DungeonGenerator'))ds.push(find('unsafe.content','Unsafe renderer, remote, filesystem, approval, runtime, export, or canonical content claim','CRITICAL'));
const r=reqId(c);if(!r||!CATACOMBS_REQUIREMENTS.some(x=>x.id===r))ds.push(find('requirement.unsupported','Unsupported asset requirement','ERROR'));
if(isGeometry(c)&&!CATACOMBS_GENERATORS.some(g=>g.id===c.generator.id&&g.version===c.generator.version))ds.push(find('generator.version','Unknown AF-D4 generator or implementation version','CRITICAL'));
if(!isGeometry(c)&&!(c.generator.id===CATACOMBS_MATERIAL_GENERATOR_ID&&c.generator.version==='1.0.0'))ds.push(find('generator.version','Unknown AF-D5 generator or implementation version','CRITICAL'));
const material=req.materialCandidate; if(material){const mr=CATACOMBS_MATERIAL_REQUIREMENTS.find(x=>x.consumerRequirementIds.includes(r as never));const slots=(c.metrics as any).materials===0?[]:[]; void slots;if(!mr)ds.push(find('material.requirement','Missing supported material requirement','ERROR'));else if(!material.outputInventory.includes(`material.${r}`))ds.push(find('material.dependency','Material dependency does not match geometry requirement','ERROR'));}
if(req.validationRun){const s=summarizeValidation(req.validationRun,{policyVersion:'af-d6-preview',warningsBlockApproval:true});if(s.hasCritical)ds.push(find('validation.critical','Critical validation finding blocks preview','CRITICAL'));}
const readiness=ds.some(d=>d.findingId.startsWith('integrity'))?'BLOCKED_BY_INTEGRITY':ds.some(d=>d.findingId.startsWith('validation'))?'BLOCKED_BY_VALIDATION':ds.some(d=>d.findingId.includes('dependency')||d.findingId.includes('requirement'))?'BLOCKED_BY_DEPENDENCY':ds.some(d=>d.findingId.includes('budget'))?'BLOCKED_BY_PREVIEW_LIMIT':ds.some(d=>d.blocksPreview)?'NOT_ADMITTED':'READY_FOR_HUMAN_REVIEW';return deepFreeze({admitted:readiness==='READY_FOR_HUMAN_REVIEW',readiness,diagnostics:ds,candidateDigest:digest(c)});}
export function buildAssetPreviewProjection(req:AssetPreviewRequest):AssetPreviewProjection|AssetPreviewAdmissionResult{const a=admitAssetPreview(req);if(!a.admitted)return a;if(req.signal?.aborted)return deepFreeze({admitted:false,readiness:'NOT_ADMITTED',diagnostics:[find('preview.cancelled','Preview projection cancelled','WARNING')]});const c=req.candidate;const g=(c as any).recipeSnapshot?undefined:undefined;void g;const geom=(c as any).geometry??(c as any).recipeSnapshot?.parameters?.geometry;const mats=req.materialCandidate?[(req.materialCandidate as any).materialPackage??req.materialCandidate.metrics]:[];const baseMetrics={vertexCount:Number(c.metrics.vertices??0),indexCount:Number(c.metrics.indices??(Number(c.metrics.triangles??0)*3)),materialSlotCount:Math.min(PREVIEW_BUDGETS.materialSlots,Number((c.metrics as any).materials??0)+3),materialCount:Number(req.materialCandidate?.metrics.materials??0),channelCount:Number(req.materialCandidate?.metrics.channels??0),markerCount:Number(c.anchors.length+c.sockets.length+1),overlayCount:req.overlays?.length??PREVIEW_OVERLAYS.length};const metrics:PreviewResourceMetrics={...baseMetrics,serializedProjectionBytes:JSON.stringify({geom,mats,baseMetrics}).length};if(!Number.isSafeInteger(metrics.indexCount)||metrics.vertexCount>PREVIEW_BUDGETS.vertices||metrics.indexCount>PREVIEW_BUDGETS.indices||metrics.markerCount>PREVIEW_BUDGETS.markers||metrics.overlayCount>PREVIEW_BUDGETS.overlays||metrics.serializedProjectionBytes>PREVIEW_BUDGETS.serializedProjectionBytes)return deepFreeze({admitted:false,readiness:'BLOCKED_BY_PREVIEW_LIMIT',diagnostics:[find('budget.preview','Preview projection budget exceeded','CRITICAL')]});const projectionSeed={contractVersion:ASSET_PREVIEW_CONTRACT_VERSION,...(geom===undefined?{}:{geometry:geom}),materials:mats,overlays:[...(req.overlays??PREVIEW_OVERLAYS)],metrics,approvalAuthority:false as const,runtimeAuthority:false as const};const p:AssetPreviewProjection={...projectionSeed,digest:digest(projectionSeed)};return deepFreeze(p);}
export function createAssetInspectionReport(req:AssetPreviewRequest):AssetInspectionReport{const a=admitAssetPreview(req);const c=req.candidate;const s=summarizeValidation(req.validationRun,{policyVersion:'af-d6-preview',warningsBlockApproval:true});return deepFreeze({contractVersion:ASSET_PREVIEW_CONTRACT_VERSION,packageId:c.packageId,candidateDigest:a.candidateDigest??digest(c),lifecycleState:c.creationStatus,requirementId:reqId(c)??'unknown',geometryMetrics:c.metrics,materialMetrics:req.materialCandidate?.metrics??{},bounds:c.spatial.bounds,pivot:c.spatial.pivot,anchors:c.anchors,sockets:c.sockets,collision:c.collision,lodPolicy:c.lodPolicy,materialSlots:CATACOMBS_MATERIAL_REQUIREMENTS.find(m=>m.consumerRequirementIds.includes(reqId(c) as never))?.requiredMaterialSlots??[],validationSummary:s,integrity:c.integrity,provenance:c.provenanceRefs,governanceRestrictions:['candidate-only','no approval','no export','no runtime eligibility','no scene integration','AF-D7 export unavailable','AF-D8 scene integration unavailable'],previewLimitations:['inspection-only','not final runtime rendering','local deterministic channel visualization only'],blockingFindings:a.diagnostics.filter(d=>d.blocksPreview),warnings:a.diagnostics.filter(d=>!d.blocksPreview),reviewReadiness:a.readiness});}
export function createAssetPreviewSession(req:AssetPreviewRequest):AssetPreviewSession|AssetPreviewAdmissionResult{const p=buildAssetPreviewProjection(req);if('admitted'in p)return p;const a=admitAssetPreview(req);return deepFreeze({sessionId:digest({candidate:a.candidateDigest,projection:p.digest,camera:req.cameraPresetId??PREVIEW_CAMERA_PRESETS[0]!.id,lighting:req.lightingPresetId??PREVIEW_LIGHTING_PRESETS[0]!.id,overlays:req.overlays??PREVIEW_OVERLAYS}),candidatePackageId:req.candidate.packageId,candidateDigest:a.candidateDigest!,rendererContractVersion:ASSET_PREVIEW_CONTRACT_VERSION,previewImplementationVersion:ASSET_PREVIEW_IMPLEMENTATION_VERSION,cameraPresetId:req.cameraPresetId??PREVIEW_CAMERA_PRESETS[0]!.id,lightingPresetId:req.lightingPresetId??PREVIEW_LIGHTING_PRESETS[0]!.id,enabledOverlays:req.overlays??PREVIEW_OVERLAYS,projectionDigest:p.digest,resourceMetrics:p.metrics,reviewReadiness:a.readiness,creationSource:'DETERMINISTIC_PACKAGE_EVIDENCE' as const});}
export function createAssetReviewDraft(report:AssetInspectionReport, reviewerLabel:string, observations:readonly AssetReviewObservation[]):AssetReviewDraft{if(observations.length>PREVIEW_BUDGETS.reviewObservations)throw new Error('review observation budget exceeded');const clean=observations.map(o=>({...o,note:o.note.replace(/[<>]/gu,'').slice(0,PREVIEW_BUDGETS.reviewTextLength)}));return deepFreeze({contractVersion:ASSET_PREVIEW_CONTRACT_VERSION,candidatePackageId:report.packageId,candidateDigest:report.candidateDigest,reviewerLabel:reviewerLabel.replace(/[<>]/gu,'').slice(0,120),observations:clean,inspectionReportDigest:digest(report),approvalAuthority:false,runtimeAuthority:false});}
export function compareAssetPreviewCandidates(a:AssetInspectionReport,b:AssetInspectionReport):PreviewComparisonResult{if(a.requirementId!==b.requirementId)return deepFreeze({compatible:false,diagnostics:[find('comparison.incompatible','Candidates have incompatible requirements','ERROR')],differences:[]});const diffs=['candidateDigest','lifecycleState','geometryMetrics','materialMetrics','validationSummary','integrity','provenance'].filter(k=>JSON.stringify((a as any)[k])!==JSON.stringify((b as any)[k]));return deepFreeze({compatible:true,diagnostics:[],differences:diffs});}
export function createAssetPreviewResourceTracker(){const disposed:string[]=[];return{disposed,dispose:(kind:string)=>{disposed.push(kind);},disposeAll:()=>{for(const k of ['geometry','materials','textures','renderTargets','controls','animationFrames','resizeObservers','eventListeners','renderer','comparisonViewports'])disposed.push(k);return disposed;},handleContextLoss:()=>diagnostic('AF_GENERATED_EVIDENCE_REQUIRED','Preview context lost; textual inspection remains available','generatedPackage')};}
export function describeAssetPreviewProductionRegistration(){return deepFreeze({contractVersion:ASSET_PREVIEW_CONTRACT_VERSION,implementationVersion:ASSET_PREVIEW_IMPLEMENTATION_VERSION,cameraPresetCount:PREVIEW_CAMERA_PRESETS.length,lightingPresetCount:PREVIEW_LIGHTING_PRESETS.length,overlayCount:PREVIEW_OVERLAYS.length,geometryCategories:CATACOMBS_REQUIREMENTS.map(r=>r.categoryId),materialFamilies:CATACOMBS_MATERIAL_PROFILES.map(p=>p.surfaceFamily),channelViews:['composedPbr','baseColor','normal','roughness','metallic','ambientOcclusion','height','damageMask','materialSlots','tiling','texelDensity'],comparisonModes:['same-requirement-candidate-diff'],approvalAvailable:false,exportAvailable:false,runtimeEligibilityAvailable:false,sceneIntegrationAvailable:false,testFixtures:false});}
