import { deepFreeze } from './core/immutable.js';

export const SDF_BLEND_SHELL_SHADER_ID='af-d6r.sdf-blend-shell.vertex.v1' as const;
export const SDF_BLEND_SHELL_VERTEX_SHADER=`// ${SDF_BLEND_SHELL_SHADER_ID}\n#define SDF_MAX_PRIMITIVES 12\n#define SDF_PROJECTION_ITERATIONS 4\nattribute vec3 position;\nattribute vec3 normal;\nuniform mat4 modelViewMatrix;\nuniform mat4 projectionMatrix;\nuniform int primitiveCount;\nuniform vec4 primitiveData0[SDF_MAX_PRIMITIVES];\nuniform vec4 primitiveData1[SDF_MAX_PRIMITIVES];\nvarying vec3 vSdfNormal;\nvarying vec3 vSdfColor;\nfloat sphereSdf(vec3 p, vec3 c, float r){return length(p-c)-r;}\nfloat capsuleSdf(vec3 p, vec3 a, vec3 b, float r){vec3 pa=p-a, ba=b-a; float h=clamp(dot(pa,ba)/max(dot(ba,ba),0.0001),0.0,1.0); return length(pa-ba*h)-r;}\nfloat coneSdf(vec3 p, vec3 c, float h, float r){vec2 q=vec2(length(p.xz-c.xz), p.y-c.y); vec2 k=vec2(r,h); return max(dot(q,k)/max(length(k),0.0001)-r, abs(q.y)-h);}\nfloat smoothMin(float a,float b,float k){float h=clamp(0.5+0.5*(b-a)/k,0.0,1.0);return mix(b,a,h)-k*h*(1.0-h);}\nfloat sceneSdf(vec3 p){float d=999.0; for(int i=0;i<SDF_MAX_PRIMITIVES;i++){ if(i>=primitiveCount) break; vec4 a=primitiveData0[i]; vec4 b=primitiveData1[i]; float pd=a.w<0.5?sphereSdf(p,a.xyz,b.x):(a.w<1.5?capsuleSdf(p,a.xyz,b.xyz,b.w):coneSdf(p,a.xyz,b.y,b.x)); d=smoothMin(d,pd,clamp(b.z,0.01,0.35)); } return d;}\nvec3 sdfGradient(vec3 p){float e=0.002; return normalize(vec3(sceneSdf(p+vec3(e,0,0))-sceneSdf(p-vec3(e,0,0)),sceneSdf(p+vec3(0,e,0))-sceneSdf(p-vec3(0,e,0)),sceneSdf(p+vec3(0,0,e))-sceneSdf(p-vec3(0,0,e))));}\nvoid main(){vec3 p=position; for(int i=0;i<SDF_PROJECTION_ITERATIONS;i++){float d=sceneSdf(p); vec3 g=sdfGradient(p); p-=g*d;} vSdfNormal=sdfGradient(p); vSdfColor=abs(vSdfNormal); gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}` as const;
export const SDF_BLEND_SHELL_FRAGMENT_SHADER=`precision mediump float; varying vec3 vSdfNormal; varying vec3 vSdfColor; void main(){ float l=max(dot(normalize(vSdfNormal),normalize(vec3(0.4,0.8,0.2))),0.2); gl_FragColor=vec4(vSdfColor*l,1.0);}` as const;
export type SdfPrimitiveKind='sphere'|'capsule'|'cone';
export interface SdfPrimitiveDescriptor{readonly id:string;readonly kind:SdfPrimitiveKind;readonly center:readonly[number,number,number];readonly end?:readonly[number,number,number];readonly radius:number;readonly height?:number;readonly blendRadius:number;readonly color:readonly[number,number,number];readonly role?:'body'|'limb'|'thin-part'|'rope'|'ear'|'tail';readonly parentId?:string;readonly shaderSource?:never;}
export interface SdfBlendShellProjection{readonly schema:'af-d6r.sdf-blend-shell.v1';readonly shaderId:typeof SDF_BLEND_SHELL_SHADER_ID;readonly primitiveKinds:readonly SdfPrimitiveKind[];readonly primitives:readonly SdfPrimitiveDescriptor[];readonly budget:typeof SDF_BLEND_SHELL_BUDGET;readonly usesRaymarching:false;readonly usesSkeletalSkinning:false;readonly drawCalls:1;}
export const SDF_BLEND_SHELL_BUDGET=deepFreeze({maxPrimitives:12,maxProjectionIterations:4,maxDistanceEvaluationsPerVertex:48,maxBlendRadius:.35,maxThinPartBlendRadius:.08,maxRopeSegments:8,maxIkLegs:6,maxIkIterations:3,maxVertices:4096,maxIndices:12288,maxShaderUniformVectors:32});
const kinds=['sphere','capsule','cone'] as const;
function finite(xs:readonly number[]){return xs.every(Number.isFinite);}
export function validateSdfPrimitiveAssembly(input:{primitives:readonly SdfPrimitiveDescriptor[]}):{ok:true;projection:SdfBlendShellProjection}|{ok:false;error:string}{if(input.primitives.length<1||input.primitives.length>SDF_BLEND_SHELL_BUDGET.maxPrimitives)return{ok:false,error:'primitive count budget exceeded'};const seen=new Set<string>();for(const p of input.primitives){if(!/^[a-z0-9_.-]{3,64}$/u.test(p.id)||seen.has(p.id))return{ok:false,error:'invalid stable primitive id'};seen.add(p.id);if(!(kinds as readonly string[]).includes(p.kind))return{ok:false,error:'unknown primitive kind'};if(!finite(p.center)||!finite(p.color)||p.color.some(c=>c<0||c>1))return{ok:false,error:'non-finite transform or color'};if(!Number.isFinite(p.radius)||p.radius<=0||p.radius>4)return{ok:false,error:'invalid dimensions'};if(p.end&&(!finite(p.end)||p.kind!=='capsule'))return{ok:false,error:'invalid capsule end'};if(p.height!==undefined&&(!Number.isFinite(p.height)||p.height<=0||p.height>8))return{ok:false,error:'invalid height'};const cap=p.role==='thin-part'||p.role==='rope'||p.role==='ear'||p.role==='tail'?SDF_BLEND_SHELL_BUDGET.maxThinPartBlendRadius:SDF_BLEND_SHELL_BUDGET.maxBlendRadius;if(!Number.isFinite(p.blendRadius)||p.blendRadius<0||p.blendRadius>cap)return{ok:false,error:'blend radius budget exceeded'};if('shaderSource'in p)return{ok:false,error:'candidate shader source rejected'};}for(const p of input.primitives){let n=p.parentId;let guard=0;while(n){if(++guard>SDF_BLEND_SHELL_BUDGET.maxRopeSegments)return{ok:false,error:'cyclic or excessive rope relationship'};if(n===p.id)return{ok:false,error:'cyclic rig relationship'};n=input.primitives.find(x=>x.id===n)?.parentId;}}return{ok:true,projection:deepFreeze({schema:'af-d6r.sdf-blend-shell.v1',shaderId:SDF_BLEND_SHELL_SHADER_ID,primitiveKinds:kinds,primitives:input.primitives,budget:SDF_BLEND_SHELL_BUDGET,usesRaymarching:false,usesSkeletalSkinning:false,drawCalls:1})};}
export function createCatacombsBlendShellDemo(){return validateSdfPrimitiveAssembly({primitives:[{id:'body.core',kind:'sphere',center:[0,1,0],radius:.65,blendRadius:.18,color:[.55,.48,.42],role:'body'},{id:'head.core',kind:'sphere',center:[0,1.82,0],radius:.38,blendRadius:.16,color:[.62,.57,.5],role:'body'},{id:'tail.rope.0',kind:'capsule',center:[0,.95,.55],end:[0,.9,1.25],radius:.12,blendRadius:.06,color:[.5,.45,.4],role:'tail',parentId:'body.core'},{id:'ear.thin.0',kind:'cone',center:[-.25,2.18,0],radius:.12,height:.35,blendRadius:.05,color:[.6,.54,.48],role:'ear',parentId:'head.core'}]});}
export function simulateProceduralPreviewMotion(seed:number,steps:number,dt:number,legs:2|4|6=4){let s=seed>>>0,phase=0;const out:number[]=[];for(let i=0;i<Math.min(steps,240);i++){s=(1664525*s+1013904223)>>>0;phase=(phase+Math.min(dt,1/30)*(legs/2))%1;out.push(Number((Math.sin((phase+(s%97)/97)*Math.PI*2)*.1).toFixed(6)));}return deepFreeze({seed:seed>>>0,steps:out.length,dt:Math.min(dt,1/30),legs,values:out,dungeonRngConsumed:false,pausable:true,resettable:true});}
export function validateProceduralRig(r:{legs?:number;rope?:readonly {id:string;parentId?:string}[]}){if(r.legs!==undefined&&![2,4,6].includes(r.legs))return{ok:false,error:'procedural IK supports only two, four, or six legs'};if((r.rope?.length??0)>SDF_BLEND_SHELL_BUDGET.maxRopeSegments)return{ok:false,error:'rope segment budget exceeded'};return{ok:true};}
