import { id } from './core/identifiers.js';
import { parseVersion } from './core/versions.js';
import { deepFreeze } from './core/immutable.js';
import { diagnostic } from './core/diagnostics.js';
import type { AssetGeneratorDescriptor } from './contracts/generator.js';
import type { ValidationFinding, ValidationRuleDescriptor } from './contracts/validation.js';
import { CORE_ASSET_BUDGET_CEILINGS, composeStricterBudgets, type AssetBudgetCeilings } from './contracts/budget.js';
import type { TrustedAssetGeneratorImplementation } from './runtime/generatorImplementation.js';
import type { TrustedValidationRuleImplementation } from './runtime/validationImplementation.js';
import type { AssetGeneratorRegistry } from './registries/generatorRegistry.js';
import type { GeneratorImplementationRegistry } from './runtime/generatorImplementationRegistry.js';
import type { ValidationRuleRegistry } from './registries/validationRuleRegistry.js';
import type { ValidationImplementationRegistry } from './runtime/validationImplementationRegistry.js';
import { ANCIENT_OSSUARY_PROFILE_ID, ANCIENT_OSSUARY_PROFILE_VERSION, CATACOMBS_BUDGET_PROFILE_ID, CATACOMBS_MATERIAL_INTENT_ID, CATACOMBS_PACK_ID, CATACOMBS_PACK_VERSION, CATACOMBS_REQUIREMENTS, CATACOMBS_STYLE_PROFILE_ID } from './catacombsPack.js';
function must<T>(r:{ok:true;value:T}|{ok:false;error:unknown}):T{if(!r.ok)throw new Error('invalid AF-D5 identity');return r.value;}
const GV=must(parseVersion<'GeneratorVersion'>('1.0.0','generator'));
export const CATACOMBS_MATERIAL_OUTPUT_KIND=must(id.output('material.package-descriptor'));
export const CATACOMBS_MATERIAL_GENERATOR_ID=must(id.generator('catacombs.generator.material-surfaces'));
export const CATACOMBS_MATERIAL_CAPABILITY=must(id.capability('af-d5.catacombs.materials'));
export const CATACOMBS_MATERIAL_VALIDATION_PROFILE_ID=must(id.validation('catacombs.validation.af-d5'));
export const CATACOMBS_MATERIAL_BUDGET_CEILINGS:AssetBudgetCeilings=composeStricterBudgets(CORE_ASSET_BUDGET_CEILINGS,{...CORE_ASSET_BUDGET_CEILINGS,generationIterations:9000,materials:12,textures:72,textureMemoryBytes:393216,packageBytes:1048576,metadataBytes:65536});
const channels=['baseColor','normal','roughness','metallic','ambientOcclusion','height','opacity','emissive','damageMask'] as const;
const families=[['worn-limestone','WORN_STONE',['stone.intent']],['dark-aged-masonry','CUT_MASONRY',['stone.intent','mortar.intent']],['mortar-recessed-joints','MORTAR',['mortar.intent']],['carved-funerary-stone','CARVED_STONE',['stone.intent']],['aged-bone','BONE',['bone.intent']],['oxidized-iron','CORRODED_METAL',['metal.intent']],['decayed-wood','DECAYED_WOOD',['wood.intent']],['dust-grime-overlay','DUST_GRIME',['dust.intent']]] as const;
export const CATACOMBS_MATERIAL_PROFILES=deepFreeze(families.map(([slug,family,slots],i)=>({id:must(id.material(`catacombs.material.${slug}`)),version:'1.0.0',surfaceFamily:family,pbrWorkflow:'METALLIC_ROUGHNESS',requiredChannels:['baseColor','normal','roughness','ambientOcclusion'],optionalChannels:channels.filter(c=>!['emissive','opacity'].includes(c)),resolutionClasses:[16,32,64],colorRange:[0.08+i*.015,0.82],roughnessRange:family==='CORRODED_METAL'?[0.55,0.96]:[0.68,1],metallicRange:family==='CORRODED_METAL'?[0.35,0.85]:[0,0],normalIntensity:[0,0.65],heightIntent:[0,0.18],opacity:'OPAQUE_ONLY',emissive:'FORBIDDEN',uvConvention:'UV0_NON_OVERLAPPING_OR_TILING',tilingRange:[0.5,8],texelDensity:[16,256],slots,edgeWear:[0,0.55],cracks:[0,0.5],chips:[0,0.45],erosion:[0.05,0.65],stain:[0,0.45],dust:[0,0.7],dampness:[0,0.38],layers:['substrate','macro-variation','structure','damage','edge-wear','dust','dampness','normalize'],blendSemantics:'DATA_MASKS_ONLY',variationPolicy:{maxVariants:3,seeded:true},damageStatePolicy:['intact','worn','damaged'],mipIntent:'AF-D7_EXPORT_ONLY',compressionIntent:'AF-D7_BC_OR_KTX_DECISION_ONLY',budgetProfileId:CATACOMBS_BUDGET_PROFILE_ID,validationProfileId:CATACOMBS_MATERIAL_VALIDATION_PROFILE_ID,provenance:['procedural trusted generation','no remote references','no protected source copying']})));
function slotsFor(req:string){if(req.includes('bone-pile'))return ['bone.intent','dust.intent']; if(req.includes('sarcophagus')||req.includes('ossuary')||req.includes('crypt'))return ['stone.intent','bone.intent','dust.intent']; if(req.includes('rubble')||req.includes('broken'))return ['stone.intent','mortar.intent','dust.intent']; return ['stone.intent','mortar.intent','dust.intent'];}
export const CATACOMBS_MATERIAL_REQUIREMENTS=deepFreeze(CATACOMBS_REQUIREMENTS.map(r=>({id:`mat.${r.id}`,version:'1.0.0',consumerRequirementIds:[r.id],compatibleGeometryCategories:[r.categoryId],requiredMaterialSlots:slotsFor(r.id),requiredOutputKinds:[CATACOMBS_MATERIAL_OUTPUT_KIND],requiredSurfaceFamilies:['WORN_STONE','MORTAR','BONE','DUST_GRIME'].filter((_,i)=>i<slotsFor(r.id).length),requiredTextureChannels:['baseColor','normal','roughness','ambientOcclusion','damageMask'],optionalTextureChannels:['height','metallic'],resolution:{min:16,max:64},texelDensity:[16,256],uv:'UV0 required; tiling 0.5..8; seams preserve anchors/sockets/doorway traversal edges',maskSemantics:['edgeWear','cracks','chips','dust','grime','dampness','mineralStaining','damageMask'],variationLimit:3,damageVariants:['intact','worn','damaged'],alpha:'FORBIDDEN',emissive:'FORBIDDEN',budgetCeilings:CATACOMBS_MATERIAL_BUDGET_CEILINGS,placeholderSuitability:'CANDIDATE_ONLY',runtimeEligibility:'NOT_RUNTIME_ELIGIBLE',provenance:['AF-D4 consumer traceability',r.id]})));
export const ANCIENT_OSSUARY_SURFACE_RULES=deepFreeze({id:'catacombs.surface-rules.ancient-ossuary',version:'1.0.0',packId:CATACOMBS_PACK_ID,profileId:ANCIENT_OSSUARY_PROFILE_ID,layerOrder:['base-substrate','macro-color-roughness','masonry-grain-bone-structure','cracks-pores-chips-erosion','edge-wear-contact-polish','dust-sediment','damp-mineral-staining','localized-age-damage','normalize-pack-intent'],protectedInterfaces:['doorway-threshold','cardinal-wall','floor-prop','arch-adjacent','anchors','sockets','pivots'],noShaderCode:true,noRendererObjects:true});
function genDesc():AssetGeneratorDescriptor{return deepFreeze({id:CATACOMBS_MATERIAL_GENERATOR_ID,version:GV,familyId:must(id.family('catacombs.materials')),displayName:'Catacombs Ancient Ossuary Material Surface Generator',supportedCategories:[...new Set(CATACOMBS_REQUIREMENTS.map(r=>r.categoryId))],parameterSchema:{type:'object',properties:{requirementId:{type:'string'},resolution:{type:'number'},channels:{type:'array'},variant:{type:'number'}},required:['requirementId'],additionalProperties:false},supportedOutputKinds:[CATACOMBS_MATERIAL_OUTPUT_KIND],requiredCapabilities:[CATACOMBS_MATERIAL_CAPABILITY],defaultBudgetProfileId:CATACOMBS_BUDGET_PROFILE_ID,determinism:{seedAffectsOutput:true,deterministicAcrossPlatforms:true,consumesDungeonRng:false,canonicalSerialization:'asset-forge-canonical-json-v1'},compatibility:{contractCompatibility:'EXACT',supportedRecipeSchemaVersions:['1.0.0']},availability:'AVAILABLE'});}
export const CATACOMBS_MATERIAL_GENERATORS=deepFreeze([genDesc()]);
const streams=['base-color','substrate-pattern','macro-variation','micro-variation','roughness','normal-detail','height-detail','edge-wear','cracks','chips','erosion','dust','grime','dampness','mineral-staining','bone-aging','metal-corrosion','wood-decay','damage-mask','channel-packing','variation-selection'] as const;
function pixels(req:string,size:number,rng:Record<string,()=>number>){const slots=slotsFor(req);return slots.map((slot,si)=>({slot,pbrWorkflow:'METALLIC_ROUGHNESS',uvSet:'UV0',tiling:[1+si,1+si],texelDensity:64,channels:channels.filter(c=>['baseColor','normal','roughness','ambientOcclusion','damageMask'].includes(c)).map((ch,ci)=>{const samples:number[]=[];for(let i=0;i<8;i++){const v=(rng[streams[(ci+si)%streams.length] as string]!()+rng['macro-variation']!()*.25+si*.07)%1;samples.push(Number(v.toFixed(6)));}return{kind:ch,width:size,height:size,components:ch==='normal'?3:1,semantic:ch,normalized:true,samples,sampleCount:samples.length,declaredPixelCount:size*size};}),layers:['substrate','macro-variation','structure','damage','edge-wear','dust','dampness','normalize'],masks:['edgeWear','cracks','chips','dust','grime','dampness','damageMask']}));}
export const CATACOMBS_MATERIAL_GENERATOR_IMPLEMENTATIONS:readonly TrustedAssetGeneratorImplementation[]=deepFreeze([{generatorId:CATACOMBS_MATERIAL_GENERATOR_ID,generatorVersion:GV,implementationVersion:'impl.1.0.0',contractSchemaVersion:'1.0.0',supportedOutputKinds:[CATACOMBS_MATERIAL_OUTPUT_KIND],execute:async(ctx,recipe)=>{ctx.checkCancellation();const req=String(recipe.requirementId??recipe.parameters.requirementId??'');const mr=CATACOMBS_MATERIAL_REQUIREMENTS.find(m=>m.consumerRequirementIds.includes(req as never));if(!mr)return{status:'FAILED',diagnostics:[diagnostic('AF_INCOMPATIBLE_GENERATOR','unsupported AF-D5 material requirement','registry',req)]};const requested=(recipe.parameters.channels as unknown as string[]|undefined)??mr.requiredTextureChannels;for(const c of requested)if(![...mr.requiredTextureChannels,...mr.optionalTextureChannels].includes(c))return{status:'FAILED',diagnostics:[diagnostic('AF_INCOMPATIBLE_GENERATOR','unsupported material channel','generatedPackage',c)]};const size=Number(recipe.parameters.resolution??32);if(!Number.isInteger(size)||size<16||size>64)return{status:'FAILED',diagnostics:[diagnostic('AF_INVALID_BUDGET','invalid or over-budget material resolution','budget',String(size))]};const work=ctx.recordWork(size*slotsFor(req).length);if(!work.ok)return{status:'FAILED',diagnostics:[work.error]};const rng=Object.fromEntries(streams.map(s=>[s,ctx.rng(s)])) as Record<string,()=>number>;ctx.checkCancellation();const materials=pixels(req,size,rng);const channelCount=materials.reduce((n,m)=>n+m.channels.length,0);const bytes=size*size*channelCount*4;if(!Number.isSafeInteger(bytes)||bytes>CATACOMBS_MATERIAL_BUDGET_CEILINGS.textureMemoryBytes)return{status:'FAILED',diagnostics:[diagnostic('AF_INVALID_BUDGET','material byte budget exceeded','budget',String(bytes))]};const out=ctx.recordOutput({materials:materials.length,textures:channelCount,textureMemoryBytes:bytes,metadataBytes:8192});if(!out.ok)return{status:'FAILED',diagnostics:[out.error]};return{status:'SUCCEEDED',output:{outputKind:CATACOMBS_MATERIAL_OUTPUT_KIND,inventory:[`material.${req}`,'pbr.METALLIC_ROUGHNESS','uv.UV0','mask.damageMask'],materialPackage:{schema:'af-d5.material-package.v1',packId:CATACOMBS_PACK_ID,packVersion:CATACOMBS_PACK_VERSION,profileId:ANCIENT_OSSUARY_PROFILE_ID,profileVersion:ANCIENT_OSSUARY_PROFILE_VERSION,materialProfileVersions:CATACOMBS_MATERIAL_PROFILES.map(p=>`${p.id}@${p.version}`),requirementId:req,slots:materials,surfaceRules:ANCIENT_OSSUARY_SURFACE_RULES.id,approval:false,runtimeEligible:false,exportedFiles:[]},metrics:{materials:materials.length,textures:channelCount,textureMemoryBytes:bytes,channels:channelCount,resolution:size,layerCount:ANCIENT_OSSUARY_SURFACE_RULES.layerOrder.length,namedSubstreams:streams.length}}};}}]);
export const CATACOMBS_MATERIAL_VALIDATION_RULES:readonly ValidationRuleDescriptor[]=deepFreeze([{id:'catacombs.validation.materials.af-d5',version:'1.0.0',profileId:CATACOMBS_MATERIAL_VALIDATION_PROFILE_ID,title:'AF-D5 Catacombs material package validation',description:'Validates PBR descriptors, channels, budgets, safety boundaries, traceability, and candidate-only governance.',execution:'AF_D3_RUNTIME_REQUIRED',blocksApprovalOnWarning:true}]);
function vf(id:string,status:ValidationFinding['status'],severity:ValidationFinding['severity'],message:string):ValidationFinding{return{findingId:id,ruleId:'catacombs.validation.materials.af-d5',ruleVersion:'1.0.0',status,severity,message};}
export const CATACOMBS_MATERIAL_VALIDATION_IMPLEMENTATIONS:readonly TrustedValidationRuleImplementation[]=deepFreeze([{ruleId:'catacombs.validation.materials.af-d5',ruleVersion:'1.0.0',implementationVersion:'impl.1.0.0',execute:async(ctx,subject)=>{ctx.checkCancellation();const f:ValidationFinding[]=[];const s=JSON.stringify(subject);for(const bad of ['shaderSource','THREE.','WebGL','GPUTexture','http://','https://','PLACEHOLDER_APPROVED','PRODUCTION_APPROVED'])if(s.includes(bad))f.push(vf(`forbidden.${bad}`,'FAIL','CRITICAL',`Forbidden material output content: ${bad}`));if(subject.creationStatus!=='GENERATED_PENDING_VALIDATION')f.push(vf('status','FAIL','CRITICAL','Package candidate status required.'));if(subject.resolvedProfiles.materialProfileIds.some(x=>x!==CATACOMBS_MATERIAL_INTENT_ID&&!CATACOMBS_MATERIAL_PROFILES.some(p=>p.id===x)))f.push(vf('profile','FAIL','ERROR','Unknown material profile.'));const metrics=(subject as any).metrics??{};if((metrics.textureMemoryBytes??0)>CATACOMBS_MATERIAL_BUDGET_CEILINGS.textureMemoryBytes)f.push(vf('budget.bytes','FAIL','CRITICAL','Texture byte budget exceeded.'));if(!subject.provenanceRefs.some(x=>x.includes('base-color'))||!subject.provenanceRefs.some(x=>x.includes('variation-selection')))f.push(vf('seed','FAIL','ERROR','Named material seed evidence incomplete.'));return{status:f.length?'FAIL':'PASS',findings:f};}}]);
export function registerCatacombsMaterialProduction(r:{generators:AssetGeneratorRegistry;generatorImplementations:GeneratorImplementationRegistry;validationRules:ValidationRuleRegistry;validationImplementations:ValidationImplementationRegistry}){const diagnostics:string[]=[];for(const g of CATACOMBS_MATERIAL_GENERATORS){const x=r.generators.register(g);if(!x.ok)diagnostics.push(x.error.summary);}for(const i of CATACOMBS_MATERIAL_GENERATOR_IMPLEMENTATIONS){const x=r.generatorImplementations.register(i);if(!x.ok)diagnostics.push(x.error.summary);}for(const v of CATACOMBS_MATERIAL_VALIDATION_RULES){const x=r.validationRules.registerTrustedDescriptor(v);if(!x.ok)diagnostics.push(x.error.summary);}for(const i of CATACOMBS_MATERIAL_VALIDATION_IMPLEMENTATIONS){const x=r.validationImplementations.register(i);if(!x.ok)diagnostics.push(x.error.summary);}return deepFreeze({profileCount:CATACOMBS_MATERIAL_PROFILES.length,requirementCount:CATACOMBS_MATERIAL_REQUIREMENTS.length,generatorCount:CATACOMBS_MATERIAL_GENERATORS.length,validationCount:CATACOMBS_MATERIAL_VALIDATION_RULES.length,surfaceRulesId:ANCIENT_OSSUARY_SURFACE_RULES.id,diagnostics});}
