import { id } from './core/identifiers.js';
import { parseVersion } from './core/versions.js';
import { deepFreeze } from './core/immutable.js';
import { diagnostic } from './core/diagnostics.js';
import type { AssetEnvironmentPackDescriptor } from './contracts/environmentPack.js';
import type { AssetRequirement } from './contracts/requirement.js';
import type { AssetGeneratorDescriptor } from './contracts/generator.js';
import type { AssetBudgetProfile, AssetBudgetCeilings } from './contracts/budget.js';
import { CORE_ASSET_BUDGET_CEILINGS, composeStricterBudgets } from './contracts/budget.js';
import type { ValidationRuleDescriptor, ValidationFinding } from './contracts/validation.js';
import type { TrustedAssetGeneratorImplementation } from './runtime/generatorImplementation.js';
import type { TrustedValidationRuleImplementation } from './runtime/validationImplementation.js';
import type { AssetGeneratorRegistry } from './registries/generatorRegistry.js';
import type { GeneratorImplementationRegistry } from './runtime/generatorImplementationRegistry.js';
import type { ValidationRuleRegistry } from './registries/validationRuleRegistry.js';
import type { ValidationImplementationRegistry } from './runtime/validationImplementationRegistry.js';
import type { AssetEnvironmentPackRegistry } from './registries/environmentPackRegistry.js';
import type { AssetRequirementRegistry } from './registries/requirementRegistry.js';

type ReqDef={id:string;category:string;display:string;consumer:string;dims:readonly [number,number,number];anchors:readonly string[];sockets:readonly string[];kind:'construction'|'feature'|'funerary'|'prop'};
function must<T>(r:{ok:true;value:T}|{ok:false;error:unknown}):T{if(!r.ok)throw new Error('invalid AF-D4 identity');return r.value;}
export const CATACOMBS_PACK_ID=must(id.pack('catacombs.environment-pack'));
export const CATACOMBS_PACK_VERSION=must(parseVersion<'EnvironmentPackVersion'>('1.0.0','pack'));
export const ANCIENT_OSSUARY_PROFILE_ID='catacombs.profile.ancient-ossuary';
export const ANCIENT_OSSUARY_PROFILE_VERSION='1.0.0';
export const CATACOMBS_STYLE_PROFILE_ID=must(id.style('catacombs.style.ancient-ossuary'));
export const CATACOMBS_MATERIAL_INTENT_ID=must(id.material('catacombs.material-intent.af-d4'));
export const CATACOMBS_BUDGET_PROFILE_ID=must(id.budget('catacombs.budget.af-d4'));
export const CATACOMBS_VALIDATION_PROFILE_ID=must(id.validation('catacombs.validation.af-d4'));
export const CATACOMBS_GEOMETRY_OUTPUT_KIND=must(id.output('geometry.descriptor'));
export const CATACOMBS_GENERATOR_CAPABILITY=must(id.capability('af-d4.catacombs.geometry'));
const V=must(parseVersion<'GeneratorVersion'>('1.0.0','generator'));
export const CATACOMBS_BUDGET_CEILINGS:AssetBudgetCeilings=composeStricterBudgets(CORE_ASSET_BUDGET_CEILINGS,{...CORE_ASSET_BUDGET_CEILINGS,generationIterations:2500,vertices:12000,triangles:7000,indices:21000,meshes:24,materials:0,textures:0,textureMemoryBytes:0,geometryMemoryBytes:4194304,anchors:32,sockets:32,collisionPrimitives:16,lodCount:3,packageBytes:1048576,metadataBytes:32768});
export const CATACOMBS_BUDGET_PROFILE:AssetBudgetProfile=deepFreeze({id:CATACOMBS_BUDGET_PROFILE_ID,version:'1.0.0' as never,authoring:CATACOMBS_BUDGET_CEILINGS,runtime:CATACOMBS_BUDGET_CEILINGS});
export const ANCIENT_OSSUARY_PROFILE=deepFreeze({id:ANCIENT_OSSUARY_PROFILE_ID,version:ANCIENT_OSSUARY_PROFILE_VERSION,gridMeters:2,wallHeightMeters:3.5,wallThicknessMeters:.45,doorwayClearanceMeters:{width:2.2,height:2.8},arch:{rise:[.7,1.2],springLine:[2,2.4]},pillar:{spacing:[4,8],radius:[.35,.65]},floor:{tile:[2,2],stairRise:.25,stairRun:.5},crypt:{alcoveDepth:[.8,1.4],facadeDepth:[.35,.8]},sarcophagus:{width:[.9,1.2],length:[2.1,2.6],height:[.75,1.1]},boneDensity:[.15,.65],rubbleDensity:[.05,.35],asymmetry:[0,.28],damage:[.08,.55],erosion:[.1,.6],silhouetteVariation:[0,.22],anchors:['floor-center','wall-left','wall-right','doorway-threshold'],sockets:['cardinal-wall','floor-prop','arch-adjacent'],collisionDefault:'SIMPLE_AABB',lodDefault:['lod0','lod1','lod2'],validationProfileId:CATACOMBS_VALIDATION_PROFILE_ID});
const REQS=([
 ['wall-segment','environment.structural.wall','Wall Segment','construction.boundary.wall',[2,.45,3.5],['wall-left','wall-right'],['trim-top'],'construction'],['floor-tile','environment.structural.floor','Floor Tile','construction.floor.tile',[2,2,.18],['floor-center'],['floor-prop'],'construction'],['pillar','environment.structural.pillar','Pillar','construction.room.pillar',[1,1,3.4],['floor-center'],['arch-adjacent'],'construction'],['arch-doorway','environment.structural.doorway','Arch Doorway','construction.doorway',[2.8,.7,3.4],['doorway-threshold'],['cardinal-wall'],'feature'],['alcove','environment.structural.alcove','Alcove','construction.wall.feature',[2,1,2.4],['wall-left','wall-right'],['floor-prop'],'feature'],['crypt-facade','environment.funerary.crypt','Crypt Facade','construction.room.feature',[3,.8,2.7],['floor-center'],['floor-prop'],'funerary'],['sarcophagus','environment.funerary.sarcophagus','Sarcophagus','environmental.floor.prop',[1.1,2.4,1],['floor-center'],[],'funerary'],['ossuary-shelf','environment.funerary.ossuary-shelf','Ossuary Shelf','environmental.wall.prop',[2,.55,2.2],['wall-left','wall-right'],[],'funerary'],['bone-pile','environment.prop.bone-pile','Bone Pile','environmental.floor.prop',[1.4,1.4,.45],['floor-center'],[],'prop'],['rubble-pile','environment.prop.rubble','Rubble Pile','environmental.floor.prop',[1.5,1.5,.5],['floor-center'],[],'prop'],['broken-masonry','environment.prop.broken-masonry','Broken Masonry','environmental.edge.prop',[1.8,.7,.8],['floor-center'],[],'prop'],['stairs-transition','environment.structural.stairs','Stairs Transition','construction.elevation.transition',[2,3,1],['floor-center'],['cardinal-wall'],'construction']
] as const).map(([id,category,display,consumer,dims,anchors,sockets,kind])=>({id,category,display,consumer,dims,anchors,sockets,kind} as ReqDef));
function anchor(a:string){return{id:must(id.anchor(`catacombs.anchor.${a}`)),version:'1.0.0' as never,semanticType:a.includes('doorway')?'DOORWAY_BOUNDARY':a.includes('floor')?'FLOOR_CONTACT':'WALL_CONNECTION',localTransform:{translation:[0,0,0],rotation:[0,0,0,1],scale:[1,1,1]},direction:[0,1,0],compatibilityClass:a,required:true,multiplicity:{min:1,max:4},snapPolicy:'EXACT',classification:'PRESENTATION',metadata:{}} as const;}
function socket(s:string){return{...anchor(s),id:must(id.socket(`catacombs.socket.${s}`))};}
function req(d:ReqDef):AssetRequirement{return deepFreeze({id:must(id.requirement(`catacombs.req.${d.id}`)),version:'1.0.0' as never,environmentPackId:CATACOMBS_PACK_ID,environmentPackVersion:CATACOMBS_PACK_VERSION,categoryId:must(id.category(d.category)),displayName:d.display,description:`AF-D4 ${d.display} derived from ${d.consumer}; finite modular dimensions ${d.dims.join('x')}m; material intent only.`,required:true,spatial:{coordinateSystem:{unitScaleMeters:1,handedness:'RIGHT',upAxis:'Y',forwardAxis:'-Z'},bounds:{kind:'AABB',min:[-d.dims[0]/2,0,-d.dims[1]/2],max:[d.dims[0]/2,d.dims[2],d.dims[1]/2]},pivot:'GROUND_CENTER',groundContact:true,placementSurface:d.consumer.includes('doorway')?'DOORWAY':d.consumer.includes('wall')?'WALL':'FLOOR',snapIncrementMeters:.5,allowedRotation:'CARDINAL_YAW',scalePolicy:'LOCKED'},requiredAnchors:d.anchors.map(anchor),requiredSockets:d.sockets.map(socket),collision:{id:must(id.collision(`catacombs.collision.${d.id}`)),type:d.id.includes('floor')?'WALKABLE_SURFACE':'NAVIGATION_BLOCKER',renderBounds:{kind:'AABB',min:[-d.dims[0]/2,0,-d.dims[1]/2],max:[d.dims[0]/2,d.dims[2],d.dims[1]/2]},primitiveCount:1,scaling:'LOCKED',navigationIntent:d.id.includes('floor')?'WALKABLE':'BLOCKER'},lodPolicy:{levels:[0,1,2].map(n=>({id:must(id.lod(`catacombs.lod.${d.id}.${n}`)),level:n,threshold:{kind:'DISTANCE_METERS',value:n*12},vertexTarget:900/(n+1),triangleTarget:500/(n+1),materialSimplification:'NONE',textureDownscale:1,collisionRelationship:n?'SIMPLIFIED':'MATCHES_RENDER',shadowPolicy:n===2?'NONE':'CAST_AND_RECEIVE',retainedAnchors:d.anchors.map(a=>must(id.anchor(`catacombs.anchor.${a}`))),preserveSilhouette:n<2})),fallback:'LOD0'},budgetProfileId:CATACOMBS_BUDGET_PROFILE_ID,styleHintIds:[CATACOMBS_STYLE_PROFILE_ID],materialHintIds:[CATACOMBS_MATERIAL_INTENT_ID],runtimePurpose:'PRESENTATION',gameplayReadability:d.id.includes('doorway')||d.id.includes('floor')?'HIGH':'MEDIUM',dependencyIds:[],acceptanceThresholdRef:'af-d4.validation.required',provenanceExpectations:['generated by trusted AF-D4 implementation','no protected source asset copying','no final material generation'],requirementState:'GENERATED',packageAcceptanceState:'VALIDATION_PENDING'} as AssetRequirement);}
export const CATACOMBS_REQUIREMENTS=deepFreeze(REQS.map(req));
const genMap={construction:['wall-segment','floor-tile','pillar','stairs-transition'],feature:['arch-doorway','alcove'],funerary:['crypt-facade','sarcophagus','ossuary-shelf'],prop:['bone-pile','rubble-pile','broken-masonry']} as const;
function gen(name:keyof typeof genMap,display:string):AssetGeneratorDescriptor{return deepFreeze({id:must(id.generator(`catacombs.generator.${name}`)),version:V,familyId:must(id.family(`catacombs.${name}`)),displayName:display,supportedCategories:REQS.filter(r=>(genMap[name] as readonly string[]).includes(r.id)).map(r=>must(id.category(r.category))),parameterSchema:{type:'object',properties:{variationFamily:{type:'string'},damage:{type:'number'},requirementId:{type:'string'}},required:['requirementId'],additionalProperties:false},supportedOutputKinds:[CATACOMBS_GEOMETRY_OUTPUT_KIND],requiredCapabilities:[CATACOMBS_GENERATOR_CAPABILITY],defaultBudgetProfileId:CATACOMBS_BUDGET_PROFILE_ID,determinism:{seedAffectsOutput:true,deterministicAcrossPlatforms:true,consumesDungeonRng:false,canonicalSerialization:'asset-forge-canonical-json-v1'},compatibility:{contractCompatibility:'EXACT',supportedRecipeSchemaVersions:['1.0.0']},availability:'AVAILABLE'});}
export const CATACOMBS_GENERATORS=deepFreeze([gen('construction','Catacombs Modular Stone Construction Generator'),gen('feature','Catacombs Architectural Feature Generator'),gen('funerary','Catacombs Funerary Structure Generator'),gen('prop','Catacombs Ossuary Prop Geometry Generator')]);
export const CATACOMBS_VALIDATION_RULES:readonly ValidationRuleDescriptor[]=deepFreeze([{id:'catacombs.validation.geometry.af-d4',version:'1.0.0',profileId:CATACOMBS_VALIDATION_PROFILE_ID,title:'AF-D4 Catacombs geometry and boundary validation',description:'Validates geometry descriptors, bounds, anchors, sockets, LODs, material intent boundary, deterministic evidence, and no approval/promotion claims.',execution:'AF_D3_RUNTIME_REQUIRED',blocksApprovalOnWarning:true}]);
export const CATACOMBS_ENVIRONMENT_PACK:AssetEnvironmentPackDescriptor=deepFreeze({id:CATACOMBS_PACK_ID,version:CATACOMBS_PACK_VERSION,displayName:'Catacombs Environment Pack',status:'PARTIAL',styleProfileIds:[CATACOMBS_STYLE_PROFILE_ID],materialProfileIds:[CATACOMBS_MATERIAL_INTENT_ID],requirementIds:CATACOMBS_REQUIREMENTS.map(r=>r.id),generatorBindings:CATACOMBS_REQUIREMENTS.map((r,i)=>{const def=REQS[i]!;const g=CATACOMBS_GENERATORS.find(x=>x.id===must(id.generator(`catacombs.generator.${def.kind}`)))!;return{environmentPackId:CATACOMBS_PACK_ID,environmentPackVersion:CATACOMBS_PACK_VERSION,selector:{kind:'REQUIREMENT' as const,id:r.id},generatorId:g.id,supportedVersions:{min:V,max:V},defaultStyleProfileId:CATACOMBS_STYLE_PROFILE_ID,defaultMaterialProfileIds:[CATACOMBS_MATERIAL_INTENT_ID],allowlistedOverrideIds:[],budgetProfileId:CATACOMBS_BUDGET_PROFILE_ID,validationProfileId:CATACOMBS_VALIDATION_PROFILE_ID,priority:10+i,availability:'AVAILABLE' as const};}),validationProfileIds:[CATACOMBS_VALIDATION_PROFILE_ID],budgetProfileIds:[CATACOMBS_BUDGET_PROFILE_ID],exportProfileIds:[]});
function makeMesh(requirementId:string,rand:()=>number,damage:()=>number){const r=CATACOMBS_REQUIREMENTS.find(x=>x.id===requirementId);if(!r)throw new Error('unsupported requirement');const b=r.spatial.bounds;const dx=(damage()-.5)*.08,dy=damage()*.12;const vertices=[[b.min[0]+dx,b.min[1],b.min[2]],[b.max[0],b.min[1],b.min[2]+dx],[b.max[0],b.max[1]-dy,b.max[2]],[b.min[0],b.max[1],b.max[2]],[0,b.max[1]*(.45+.1*rand()),0]];return{schema:'af-d4.geometry-descriptor.v1',profile:ANCIENT_OSSUARY_PROFILE_ID,requirementId,bounds:b,pivot:r.spatial.pivot,anchors:r.requiredAnchors.map(a=>({id:a.id,semanticType:a.semanticType,direction:a.direction})),sockets:r.requiredSockets.map(s=>({id:s.id,semanticType:s.semanticType,direction:s.direction})),meshes:[{id:`mesh.${requirementId}`,vertices,indices:[0,1,4,1,2,4,2,3,4,3,0,4,0,3,2,0,2,1],materialSlots:['stone.intent','mortar.intent','bone.intent','dust.intent'].filter((_,i)=>i<2+Math.floor(rand()*2)),collisionIntent:r.collision,lods:r.lodPolicy.levels.map(l=>({id:l.id,level:l.level,vertexTarget:l.vertexTarget,triangleTarget:l.triangleTarget}))}],variation:{damage:damage(),family:'ancient-ossuary-controlled'},authority:{noDungeonTransforms:true,noRuntimePromotion:true,noApproval:true,materialGeneration:false}};}
function impl(g:AssetGeneratorDescriptor):TrustedAssetGeneratorImplementation{return{generatorId:g.id,generatorVersion:g.version,implementationVersion:'impl.1.0.0',contractSchemaVersion:'1.0.0',supportedOutputKinds:[CATACOMBS_GEOMETRY_OUTPUT_KIND],execute:async(ctx,recipe)=>{ctx.checkCancellation();const req=String(recipe.requirementId??recipe.parameters.requirementId??'');if(!CATACOMBS_REQUIREMENTS.some(r=>r.id===req))return{status:'FAILED',diagnostics:[diagnostic('AF_INCOMPATIBLE_GENERATOR','unsupported AF-D4 requirement','registry',req)]};const streams=['primary-shape','proportions','surface-deformation','damage','fragment-selection','bone-layout','rubble-layout','anchor-layout','lod-layout','variation-selection'];const rngs=Object.fromEntries(streams.map(s=>[s,ctx.rng(s)])) as Record<string,()=>number>;const work=ctx.recordWork(50);if(!work.ok)return{status:'FAILED',diagnostics:[work.error]};ctx.checkCancellation();const geometry=makeMesh(req,rngs['primary-shape']!,rngs.damage!);const vertices=(geometry.meshes[0]?.vertices.length??0),triangles=(geometry.meshes[0]?.indices.length??0)/3;const budget=ctx.recordOutput({vertices,triangles,indices:triangles*3,meshes:1,materials:0,textures:0,anchors:geometry.anchors.length,sockets:geometry.sockets.length,collisionPrimitives:1,lodCount:3,geometryMemoryBytes:vertices*24+triangles*12,metadataBytes:1024});if(!budget.ok)return{status:'FAILED',diagnostics:[budget.error]};return{status:'SUCCEEDED',output:{outputKind:CATACOMBS_GEOMETRY_OUTPUT_KIND,inventory:[`asset.${req}`],geometry,materials:{intentOnly:true,slots:geometry.meshes[0]!.materialSlots,afD5Required:true},metrics:{vertices,triangles,meshes:1,anchors:geometry.anchors.length,sockets:geometry.sockets.length}}};}};}
export const CATACOMBS_GENERATOR_IMPLEMENTATIONS=deepFreeze(CATACOMBS_GENERATORS.map(impl));
function finding(idf:string,status:ValidationFinding['status'],severity:ValidationFinding['severity'],message:string):ValidationFinding{return{findingId:idf,ruleId:'catacombs.validation.geometry.af-d4',ruleVersion:'1.0.0',status,severity,message};}
export const CATACOMBS_VALIDATION_IMPLEMENTATIONS:readonly TrustedValidationRuleImplementation[]=deepFreeze([{ruleId:'catacombs.validation.geometry.af-d4',ruleVersion:'1.0.0',implementationVersion:'impl.1.0.0',execute:async(ctx,subject)=>{ctx.checkCancellation();const findings:ValidationFinding[]=[];const g=(subject as any).metrics;if((g.vertices??0)>CATACOMBS_BUDGET_CEILINGS.vertices)findings.push(finding('vertices.budget','FAIL','CRITICAL','Vertex budget exceeded.'));if(subject.creationStatus!=='GENERATED_PENDING_VALIDATION')findings.push(finding('status.invalid','FAIL','CRITICAL','Only generated pending validation candidates are accepted.'));for(const bad of ['PLACEHOLDER_APPROVED','PRODUCTION_APPROVED'])if(JSON.stringify(subject).includes(bad))findings.push(finding(`approval.${bad}`,'FAIL','CRITICAL','Approval claims are forbidden in AF-D4 output.'));if(!subject.outputInventory.every(x=>x.startsWith('asset.catacombs.req.')))findings.push(finding('inventory.traceability','FAIL','ERROR','Output inventory must be traceable Catacombs requirement assets.'));if(subject.resolvedProfiles.materialProfileIds.length!==1||subject.resolvedProfiles.materialProfileIds[0]!==CATACOMBS_MATERIAL_INTENT_ID)findings.push(finding('material.intent','FAIL','ERROR','Only AF-D4 material intent is allowed.'));if(!subject.provenanceRefs.some(x=>x.includes('primary-shape'))||!subject.provenanceRefs.some(x=>x.includes('variation-selection')))findings.push(finding('seed.evidence','FAIL','ERROR','Named seed stream evidence is incomplete.'));return{status:findings.length?'FAIL':'PASS',findings};}}]);
export function registerCatacombsProduction(r:{environmentPacks?:AssetEnvironmentPackRegistry;requirements?:AssetRequirementRegistry;generators:AssetGeneratorRegistry;generatorImplementations:GeneratorImplementationRegistry;validationRules:ValidationRuleRegistry;validationImplementations:ValidationImplementationRegistry}){const diagnostics:string[]=[];r.environmentPacks?.register(CATACOMBS_ENVIRONMENT_PACK,CATACOMBS_BUDGET_CEILINGS);for(const q of CATACOMBS_REQUIREMENTS)r.requirements?.register(q);for(const g of CATACOMBS_GENERATORS){const x=r.generators.register(g);if(!x.ok)diagnostics.push(x.error.summary);}for(const i of CATACOMBS_GENERATOR_IMPLEMENTATIONS){const x=r.generatorImplementations.register(i);if(!x.ok)diagnostics.push(x.error.summary);}for(const v of CATACOMBS_VALIDATION_RULES){const x=r.validationRules.registerTrustedDescriptor(v);if(!x.ok)diagnostics.push(x.error.summary);}for(const i of CATACOMBS_VALIDATION_IMPLEMENTATIONS){const x=r.validationImplementations.register(i);if(!x.ok)diagnostics.push(x.error.summary);}return deepFreeze({packId:CATACOMBS_PACK_ID,packVersion:CATACOMBS_PACK_VERSION,profileId:ANCIENT_OSSUARY_PROFILE_ID,profileVersion:ANCIENT_OSSUARY_PROFILE_VERSION,requirementCount:CATACOMBS_REQUIREMENTS.length,generatorCount:CATACOMBS_GENERATORS.length,validationCount:CATACOMBS_VALIDATION_RULES.length,diagnostics});}
