import * as THREE from 'three';
import { buildAssetPreviewProjection, createAssetInspectionReport, PREVIEW_BACKGROUNDS, PREVIEW_CAMERA_PRESETS, PREVIEW_LIGHTING_PRESETS, PREVIEW_OVERLAYS, type AssetPreviewProjection, type AssetPreviewRequest } from './assetPreview.js';
import { SDF_BLEND_SHELL_FRAGMENT_SHADER, SDF_BLEND_SHELL_VERTEX_SHADER, createCatacombsBlendShellDemo } from './assetPreviewSdf.js';

export type PreviewMode='solid'|'wireframe'|'vertexNormals'|'faceNormals'|'uvChecker'|'materialSlots'|'bounds'|'pivot'|'anchors'|'sockets'|'collision';
export class ThreeAssetPreviewAdapter{private renderer:THREE.WebGLRenderer|undefined;private scene:THREE.Scene|undefined;private camera:THREE.PerspectiveCamera|undefined;private mesh:THREE.Mesh|undefined;private resources:{dispose:()=>void;kind?:string}[]=[];private raf=0;private turntable=false;private motion=false;private reduced=false;private canvas:HTMLCanvasElement|undefined;private contextLost=false;readonly diagnostics:string[]=[];state={cameraPreset:'isometric-inspection',lightingPreset:'neutral-studio',background:'neutral-light',mode:'solid',lod:0,overlays:new Set<string>(),frames:0,disposed:0,inspectionText:'',webglAvailable:false,sdfActive:false,animationPhase:0};
constructor(private host:HTMLElement,opts:{reducedMotion?:boolean}={}){this.reduced=!!opts.reducedMotion;}
initialize(req:AssetPreviewRequest){const projection=buildAssetPreviewProjection(req);const report=createAssetInspectionReport(req);this.state.inspectionText=`${report.packageId} ${report.reviewReadiness} ${report.requirementId}`;if('admitted'in projection){this.diagnostics.push('admission-or-projection-failed');return{ok:false as const,projection,report};}if(!this.hasWebgl()){this.diagnostics.push('webgl-unavailable');return{ok:false as const,projection,report};}this.createScene(projection,req);return{ok:true as const,projection,report};}
private hasWebgl(){const c=document.createElement('canvas');return !!(c.getContext('webgl2')||c.getContext('webgl')||c.getContext('experimental-webgl'));}
private track<T>(r:T,kind:string){const d=(r as any).dispose;this.resources.push({kind,dispose:typeof d==='function'?()=>d.call(r):()=>{}});return r;}
private createScene(projection:AssetPreviewProjection,req:AssetPreviewRequest){this.disposePreviewOnly();this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(50,1,.01,100);this.setCameraPreset(this.state.cameraPreset);this.setLightingPreset(this.state.lightingPreset);this.renderer=this.track(new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'}),'renderer');this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.setSize(Math.min(this.host.clientWidth||320,1024),Math.min(this.host.clientHeight||240,768));this.canvas=this.renderer.domElement;this.canvas.tabIndex=0;this.canvas.setAttribute('role','img');this.canvas.setAttribute('aria-label','Asset preview viewport; press Tab to leave viewport');this.host.append(this.canvas);const onLost=(e:Event)=>{e.preventDefault();this.contextLost=true;this.pauseTurntable();this.pauseProceduralMotion();this.disposePreviewOnly();this.diagnostics.push('webglcontextlost textual inspection preserved');};this.canvas.addEventListener('webglcontextlost',onLost);this.resources.push({kind:'contextLostListener',dispose:()=>this.canvas?.removeEventListener('webglcontextlost',onLost)});const meshDesc=(projection.geometry as any)?.meshes?.[0];const vertices=(meshDesc?.vertices??[[0,0,0],[1,0,0],[0,1,0]]) as number[][];const indices=(meshDesc?.indices??[0,1,2]) as number[];const geom=this.track(new THREE.BufferGeometry(),'geometry');geom.setAttribute('position',new THREE.BufferAttribute(new Float32Array(vertices.flat()),3));geom.setIndex(indices);geom.computeVertexNormals();const mat=this.track(new THREE.MeshStandardMaterial({color:0x8d8070,roughness:.7,metalness:.05,wireframe:false}),'material');this.mesh=new THREE.Mesh(geom,mat);this.scene.add(this.mesh);for(const o of req.overlays??PREVIEW_OVERLAYS)this.addOverlay(o);if((req.candidate as any).previewPrimitiveAssembly){const demo=createCatacombsBlendShellDemo();if(demo.ok){const sgeom=this.track(new THREE.SphereGeometry(1,24,12),'sdfGeometry');const smat=this.track(new THREE.RawShaderMaterial({vertexShader:SDF_BLEND_SHELL_VERTEX_SHADER,fragmentShader:SDF_BLEND_SHELL_FRAGMENT_SHADER,uniforms:{primitiveCount:{value:demo.projection.primitives.length},primitiveData0:{value:[]},primitiveData1:{value:[]}}}),'sdfShaderMaterial');this.scene.add(new THREE.Mesh(sgeom,smat));this.state.sdfActive=true;}}
this.state.webglAvailable=true;this.renderFrame();if(!this.reduced)this.startTurntable();}
private renderFrame=()=>{if(this.contextLost||!this.renderer||!this.scene||!this.camera)return;this.state.frames++;if(this.turntable&&this.mesh)this.mesh.rotation.y+=.01;if(this.motion)this.state.animationPhase=Number(((this.state.animationPhase+.016)%1).toFixed(6));this.renderer.render(this.scene,this.camera);if(this.turntable||this.motion)this.raf=requestAnimationFrame(this.renderFrame);};
setMode(mode:PreviewMode){this.state.mode=mode;if(this.mesh){const mat=this.mesh.material as THREE.MeshStandardMaterial;mat.wireframe=mode==='wireframe';if((mat.color as any)?.set)(mat.color as any).set(mode==='uvChecker'?0x44aaff:mode==='materialSlots'?0xffcc44:0x8d8070);else (mat as any).color=mode==='uvChecker'?0x44aaff:mode==='materialSlots'?0xffcc44:0x8d8070;mat.needsUpdate=true;}if(mode==='vertexNormals'||mode==='faceNormals')this.addOverlay(mode);this.renderFrame();}
setMaterialChannel(channel:string){this.state.mode=channel;const colors:Record<string,number>={baseColor:0xaa7350,normal:0x6688ff,roughness:0x888888,metallic:0xbfc7d5,ambientOcclusion:0x444444,height:0xffffff,damageMask:0x771111,materialSlots:0xffcc44,tiling:0x44ffaa,texelDensity:0xaa44ff};if(this.mesh){const mat=this.mesh.material as any;if(mat.color?.set)mat.color.set(colors[channel]??0x8d8070);else mat.color=colors[channel]??0x8d8070;}this.renderFrame();}
addOverlay(id:string){if(!PREVIEW_OVERLAYS.includes(id))return;this.state.overlays.add(id);const g=this.track(new THREE.BufferGeometry(),'overlayGeometry');g.setAttribute('position',new THREE.BufferAttribute(new Float32Array([0,0,0,0,1,0]),3));const m=this.track(new THREE.LineBasicMaterial({color:0xffff00}),'overlayMaterial');this.scene?.add(new THREE.LineSegments(g,m));}
setLod(lod:number){this.state.lod=Math.max(0,Math.min(2,lod|0));this.resources.filter(r=>r.kind==='geometry').forEach(r=>r.dispose());this.state.disposed++;this.renderFrame();}
setCameraPreset(id:string){if(!PREVIEW_CAMERA_PRESETS.some(p=>p.id===id))return;this.state.cameraPreset=id;const positions:Record<string,[number,number,number]>={ 'front-orthographic':[0,1,5],'back-orthographic':[0,1,-5],'left-orthographic':[-5,1,0],'right-orthographic':[5,1,0],'top-orthographic':[0,5,0],'bottom-orthographic':[0,-5,0],'isometric-inspection':[3,3,3],'perspective-turntable':[4,2,4],'detail-inspection':[1,1,2]};this.camera?.position.set(...(positions[id]??[3,3,3]));this.camera?.lookAt(0,0,0);this.renderFrame();}
setLightingPreset(id:string){if(!PREVIEW_LIGHTING_PRESETS.some(p=>p.id===id))return;this.state.lightingPreset=id;this.scene?.add(this.track(new THREE.HemisphereLight(id==='high-contrast-form'?0xffffff:0xddddee,0x222222,id==='unlit-channel'?0:.8),'light') as any);this.renderFrame();}
setBackground(id:string){if(!PREVIEW_BACKGROUNDS.includes(id as any))return;this.state.background=id;this.renderFrame();}
startTurntable(){this.turntable=true;this.renderFrame();}pauseTurntable(){this.turntable=false;if(this.raf)cancelAnimationFrame(this.raf);this.raf=0;}resetTurntable(){this.pauseTurntable();if(this.mesh)this.mesh.rotation.y=0;this.renderFrame();}startProceduralMotion(){this.motion=true;this.renderFrame();}pauseProceduralMotion(){this.motion=false;if(this.raf)cancelAnimationFrame(this.raf);}stepProceduralMotion(){this.state.animationPhase=Number(((this.state.animationPhase+1/60)%1).toFixed(6));this.renderFrame();}resetProceduralMotion(){this.pauseProceduralMotion();this.state.animationPhase=0;this.renderFrame();}
disposePreviewOnly(){if(this.raf)cancelAnimationFrame(this.raf);this.raf=0;for(const r of this.resources.splice(0).reverse()){r.dispose();this.state.disposed++;}this.renderer=undefined;this.scene=undefined;this.camera=undefined;this.mesh=undefined;this.canvas?.remove();this.canvas=undefined;this.state.webglAvailable=false;}
dispose(){this.disposePreviewOnly();this.host.replaceChildren();}
}
