import type { AssetBudget, AssetForgeRecipe, AssetRuntimeCapabilities, GeneratedAssetDefinition, JsonObject, JsonValue } from './contracts/authoritative.js';
import type { AssetForgeDiagnostic } from './core/diagnostics.js';
import { DEFAULT_ASSET_BUDGET } from './budgets/budget.js';
import { parseSafeJson } from './core/serialization.js';
import { diagnostic } from './core/diagnostics.js';
import { sha256Digest } from './integrity/canonical.js';
import { normalizeAssetForgeRecipe, ASSET_FORGE_RECIPE_SCHEMA_VERSION, admitJsonObject } from './recipes/normalize.js';
import { AssetGeneratorRegistry } from './generators/registry.js';
import { generateAsset } from './generators/runtime.js';
import { registerAfDev2GeneratorPacks } from './generator-packs/index.js';
import { ThreeAssetPreviewAdapter, type PreviewMode } from './threeAssetPreviewAdapter.js';
import { CATACOMBS_REFERENCE_ASSET_REGISTRY } from '../../dungeon/assetRegistry.js';

export const AssetForgeWorkbenchProjectVersion = 'asset-forge.workbench.project.v1' as const;
export type AssetForgeWorkbenchProjectVersion = typeof AssetForgeWorkbenchProjectVersion;
export type AssetWorkbenchStatus = 'IDLE'|'DIRTY'|'QUEUED'|'ADMITTING'|'MIGRATING'|'NORMALIZING'|'RESOLVING'|'CHECKING_CAPABILITIES'|'GENERATING'|'VALIDATING'|'FINALIZING'|'SUCCEEDED'|'FAILED'|'CANCELLED'|'STALE';
export type AssetReadinessStatus = 'DRAFT'|'DIRTY'|'GENERATION_FAILED'|'GENERATED_UNVALIDATED'|'VALIDATION_FAILED'|'VALID_WITH_WARNINGS'|'VALID'|'CANDIDATE_READY';
export type AssetPreviewMode = PreviewMode|'neutral-clay'|'normal'|'uv-checker'|'vertex-color'|'metallic-roughness'|'emissive-intent'|'transparency'|'bounds-only';
export type AssetPreviewOverlay = 'grid'|'axes'|'origin'|'pivot'|'bounds'|'wireframe'|'normals'|'sockets'|'interactions'|'colliders'|'lod';

export interface AssetForgeWorkbenchProject { readonly projectVersion: AssetForgeWorkbenchProjectVersion; readonly projectId: string; readonly title: string; readonly recipeDraft: AssetForgeRecipe; readonly recipeRevision: number; readonly generationRequest: { readonly recipe: AssetForgeRecipe; readonly targetSchemaVersion?: string; readonly capabilities?: Partial<AssetRuntimeCapabilities>; readonly budget?: Partial<AssetBudget> }; readonly lastSuccessfulIdentity?: string; readonly authoringMetadata?: JsonObject; }
export interface AssetForgeWorkbenchUiState { readonly activePanel: string; readonly selectedComponentId?: string; readonly selectedGeometryId?: string; readonly selectedMaterialId?: string; readonly selectedSocketId?: string; readonly selectedLodId?: string; readonly previewMode: string; readonly cameraPreset: string; readonly overlays: readonly string[]; }
export interface AssetSelectionState { readonly componentIds: readonly string[]; readonly geometryIds: readonly string[]; readonly materialIds: readonly string[]; readonly socketIds: readonly string[]; readonly lodIds: readonly string[]; }
export interface AssetPreviewState { readonly mode: AssetPreviewMode; readonly overlays: readonly AssetPreviewOverlay[]; readonly cameraPreset: string; readonly selectedLod?: string; readonly adapterOwned: true; readonly disposedResources: number; readonly contextLost: boolean; }
export interface AssetDiagnosticView { readonly severity: 'INFO'|'WARNING'|'ERROR'; readonly stage: string; readonly code: string; readonly summary: string; readonly componentId?: string; readonly operationId?: string; readonly recipePath?: string; readonly retryable: boolean; readonly boundedDetails?: JsonObject; }
export interface AssetBudgetSummary { readonly current: Partial<AssetBudget>; readonly limit: AssetBudget; readonly remaining: Partial<AssetBudget>; readonly exceeded: readonly string[]; readonly utilization: Readonly<Record<string, number>>; }
export interface AssetHierarchyNode { readonly id: string; readonly kind: 'component'|'geometry'|'material'|'socket'|'interaction'|'lod'|'physics'|'dependency'; readonly label: string; readonly parentId?: string; readonly children: readonly string[]; readonly diagnosticCount: number; }
export interface AssetInspectorSection { readonly id: string; readonly title: string; readonly rows: readonly { readonly label: string; readonly value: string }[]; }
export interface AssetRevision { readonly revision: number; readonly name?: string; readonly recipe: AssetForgeRecipe; readonly canonicalDigest: string; }
export interface AssetRevisionDiff { readonly fromRevision: number; readonly toRevision: number; readonly changes: readonly { readonly path: string; readonly classification: 'Recipe identity change'|'Generated geometry change'|'Material-binding change'|'Interaction change'|'Capability change'|'Presentation-only change'|'Validation-only change'; readonly before?: string; readonly after?: string }[]; readonly truncated: boolean; }
export interface AssetDeterminismCheckResult { readonly status: 'MATCH'|'MISMATCH'|'CANCELLED'|'FAILED'; readonly digestMatch: boolean; readonly canonicalOutputMatch: boolean; readonly geometryBufferMatch: boolean; readonly provenanceMatch: boolean; readonly diagnosticCodeMatch: boolean; readonly firstDifference?: string; readonly diagnostics: readonly AssetDiagnosticView[]; }
export interface AssetCapabilityProfile { readonly id: string; readonly label: string; readonly capabilities: Partial<AssetRuntimeCapabilities>; }
export interface CatacombsAssetCompatibilityView { readonly assetId: string; readonly generatorBinding: string; readonly registryFamily: string; readonly placementCategories: readonly string[]; readonly authoredCandidate: boolean; readonly proceduralFallback: boolean; readonly connectionMetadata: JsonObject; readonly status: 'SUPPORTED'|'DEGRADED'|'REJECTED'; readonly blockingDiagnostics: readonly AssetDiagnosticView[]; }
export interface AssetWorkbenchPreset { readonly presetId: string; readonly version: string; readonly generator: { readonly id:string; readonly version:string }; readonly family: string; readonly subtype: string; readonly configuration: JsonObject; readonly compatibleRecipeVersion: string; readonly description: string; readonly tags: readonly string[]; readonly budgetClassification: string; readonly capabilityRequirements: Partial<AssetRuntimeCapabilities>; }
export interface AssetWorkbenchPresetRegistry { readonly list: () => readonly AssetWorkbenchPreset[]; readonly get: (id:string, version?:string) => AssetWorkbenchPreset|undefined; }
export type AssetAuthoringField = { readonly kind:'boolean'|'number'|'enum'|'color'|'vector'|'seed'|'text'; readonly path:string; readonly label:string; readonly description:string; readonly defaultValue:JsonValue; readonly value:JsonValue; readonly min?:number; readonly max?:number; readonly step?:number; readonly units?:string; readonly values?:readonly string[]; readonly valid:boolean; readonly diagnostic?:string };
export interface AssetAuthoringFieldGroup { readonly id:string; readonly label:string; readonly fields: readonly AssetAuthoringField[]; }
export interface AssetAuthoringSchema { readonly schemaVersion:'asset-forge.authoring.v1'; readonly generatorId:string; readonly generatorVersion:string; readonly groups: readonly AssetAuthoringFieldGroup[]; }
export interface AssetRecipeEditorState { readonly structured: AssetAuthoringSchema; readonly jsonText:string; readonly lastAdmittedDraft:AssetForgeRecipe; readonly parseDiagnostics:readonly AssetDiagnosticView[]; readonly admissionDiagnostics:readonly AssetDiagnosticView[]; }
export type AssetWorkbenchImportResult = { readonly status:'IMPORTED'; readonly project:AssetForgeWorkbenchProject; readonly diagnostics:readonly AssetDiagnosticView[] } | { readonly status:'REJECTED'; readonly diagnostics:readonly AssetDiagnosticView[]; readonly preservedProject:AssetForgeWorkbenchProject };
export interface AssetWorkbenchExportRequest { readonly kind:'canonical-recipe'|'workbench-project'|'inspection-summary'|'validation-report'|'provenance-report'|'integrity-record'|'diagnostic-report'|'geometry-metrics-report'; readonly includeUiState?:boolean; }
export type AssetWorkbenchAction = { readonly type:'SET_FIELD'; readonly path:string; readonly value:JsonValue }|{ readonly type:'SET_UI'; readonly ui:Partial<AssetForgeWorkbenchUiState> }|{ readonly type:'GENERATE' }|{ readonly type:'CANCEL' }|{ readonly type:'UNDO' }|{ readonly type:'REDO' };
export type AssetWorkbenchCommand = 'generate'|'cancel'|'save'|'undo'|'redo'|'focusSearch'|'frameSelection'|'toggleGrid'|'toggleWireframe'|'toggleBounds'|'toggleSockets'|'switchLod'|'resetCamera'|'copySeed'|'openDiagnostics';
export interface AssetForgeWorkbenchState { readonly project:AssetForgeWorkbenchProject; readonly ui:AssetForgeWorkbenchUiState; readonly status:AssetWorkbenchStatus; readonly readiness:AssetReadinessStatus; readonly dirty:boolean; readonly generating:boolean; readonly result?:GeneratedAssetDefinition; readonly lastSuccessfulResult?:GeneratedAssetDefinition; readonly diagnostics:readonly AssetDiagnosticView[]; readonly revisions:readonly AssetRevision[]; readonly redo:readonly AssetRevision[]; }

const limits = { maxProjectBytes: 512_000, maxDiagnostics: 200, maxDiffs: 200 } as const;
const closedProjectKeys = new Set(['projectVersion','projectId','title','recipeDraft','recipeRevision','generationRequest','lastSuccessfulIdentity','authoringMetadata']);
const urlish = /(?:https?:|file:|data:|javascript:|\.\.|^\/|^[A-Za-z]:[\\/]|import\s*\(|function\s*\(|=>)/i;
const stableStringify = (v:unknown) => JSON.stringify(v, Object.keys(flatKeys(v)).sort());
function flatKeys(v:unknown, out:Record<string,1>={}):Record<string,1>{ if(v&&typeof v==='object') for(const k of Object.keys(v as any)){ out[k]=1; flatKeys((v as any)[k],out); } return out; }
function clone<T>(v:T):T{ return JSON.parse(JSON.stringify(v)) as T; }
function diag(d:AssetForgeDiagnostic):AssetDiagnosticView{const out:Record<string,unknown>={severity:d.severity??(d.code.includes('WARNING')?'WARNING':'ERROR'),stage:d.stage??d.subsystem,code:d.code,summary:d.summary??d.message??d.code,retryable:d.retryable};if(d.componentId)out.componentId=d.componentId;if(d.operationId)out.operationId=d.operationId;if(d.path??d.affectedId)out.recipePath=d.path??d.affectedId;if(d.details)out.boundedDetails=d.details as JsonObject;return out as unknown as AssetDiagnosticView;}
function mkRecipe(packId='af.generator.catacombs', family='floor', subtype='slab', seed='seed.default'):AssetForgeRecipe{return{schemaVersion:ASSET_FORGE_RECIPE_SCHEMA_VERSION,recipeId:`recipe.${packId}.${family}.${subtype}.${seed}`,origin:'PROCEDURAL',generator:{id:packId,version:'1.0.0',familyId:family,profileId:'default'},seed,parameters:{family,subtype,tier:1,rank:'common',size:1,environment:'catacombs',damage:0,corruption:0,styleVariant:'default'},components:[],materials:[],sockets:[],interactions:[],lods:[],metadata:{name:`${family} ${subtype}`,authoringTool:'Asset Forge Workbench'}};}
function digestRecipe(r:AssetForgeRecipe){const d=sha256Digest({schemaVersion:r.schemaVersion,recipeId:r.recipeId,generator:r.generator,seed:r.seed,parameters:r.parameters});return d.ok?d.value:'digest.unavailable';}
export function createDefaultAssetForgeWorkbenchProject(recipe:AssetForgeRecipe=mkRecipe()):AssetForgeWorkbenchProject{const id=`project.${digestRecipe(recipe).slice(0,16)}`;return Object.freeze({projectVersion:AssetForgeWorkbenchProjectVersion,projectId:id,title:recipe.metadata.name??'Asset Forge Project',recipeDraft:clone(recipe),recipeRevision:0,generationRequest:{recipe:clone(recipe),targetSchemaVersion:ASSET_FORGE_RECIPE_SCHEMA_VERSION},authoringMetadata:{createdBy:'asset-forge-workbench'}});}
export function createDefaultAssetForgeWorkbenchUiState():AssetForgeWorkbenchUiState{return Object.freeze({activePanel:'recipe',previewMode:'neutral-clay',cameraPreset:'isometric-inspection',overlays:['grid','axes','bounds','sockets']});}
export function createAssetGeneratorCatalog(registry=createRegisteredAssetGeneratorRegistry()){return registry.list().map(p=>({id:p.descriptor.id,version:p.descriptor.version,displayName:p.descriptor.id.replaceAll('.',' '),description:`${p.descriptor.familyIds.length} supported families`,supportedFamilies:[...p.descriptor.familyIds].sort(),recipeOrigins:p.descriptor.supportedOrigins,profiles:['default'],capabilities:p.descriptor.capabilities,runtimeRequirements:p.descriptor.runtimeRequirements,budgetLimits:p.descriptor.budgetLimits,migrationCompatibility:p.descriptor.migrationCompatibility,trustedOperationRequirements:p.descriptor.requiredTrustedOperations,availability:'AVAILABLE' as const,deprecated:false,packGroup:p.descriptor.id.split('.')[2]??p.descriptor.id})).sort((a,b)=>`${a.id}@${a.version}`.localeCompare(`${b.id}@${b.version}`));}
export function createRegisteredAssetGeneratorRegistry(){const r=new AssetGeneratorRegistry();registerAfDev2GeneratorPacks(r);return r;}
export function resolveExactGenerator(registry:AssetGeneratorRegistry,id:string,version:string){const p=registry.get(id,version);return p?{ok:true as const,pack:p}:{ok:false as const,diagnostic:diag(diagnostic('AF_MISSING_DEPENDENCY',`unknown generator ${id}@${version}`,'registry',`${id}@${version}`))};}
export function buildAuthoringSchema(recipe:AssetForgeRecipe, registry=createRegisteredAssetGeneratorRegistry()):AssetAuthoringSchema{const pack=registry.get(recipe.generator.id,recipe.generator.version);const families=pack?[...pack.descriptor.familyIds].sort():[recipe.generator.familyId];const p=recipe.parameters as any;const f=(field:AssetAuthoringField)=>field;return{schemaVersion:'asset-forge.authoring.v1',generatorId:recipe.generator.id,generatorVersion:recipe.generator.version,groups:[{id:'identity',label:'Identity',fields:[f({kind:'enum',path:'/generator/familyId',label:'Family',description:'Generator family binding',defaultValue:families[0]??'catacombs',value:recipe.generator.familyId,values:families,valid:true}),f({kind:'seed',path:'/seed',label:'Root seed',description:'Authoritative deterministic seed',defaultValue:'seed.default',value:recipe.seed,valid:true})]},{id:'parameters',label:'Parameters',fields:[f({kind:'text',path:'/parameters/subtype',label:'Subtype',description:'Admitted subtype',defaultValue:'slab',value:String(p.subtype??''),valid:true}),f({kind:'number',path:'/parameters/tier',label:'Tier',description:'1-5 production tier',defaultValue:1,value:Number(p.tier??1),min:1,max:5,step:1,valid:true}),f({kind:'enum',path:'/parameters/rank',label:'Rank',description:'Rarity/rank',defaultValue:'common',value:String(p.rank??'common'),values:['common','uncommon','rare','epic','legendary'],valid:true}),f({kind:'number',path:'/parameters/size',label:'Size',description:'Meters scalar',defaultValue:1,value:Number(p.size??1),min:.25,max:8,step:.01,units:'m',valid:true}),f({kind:'number',path:'/parameters/damage',label:'Damage',description:'Damage state 0-1',defaultValue:0,value:Number(p.damage??0),min:0,max:1,step:.01,valid:true}),f({kind:'number',path:'/parameters/corruption',label:'Corruption',description:'Corruption state 0-1',defaultValue:0,value:Number(p.corruption??0),min:0,max:1,step:.01,valid:true}),f({kind:'text',path:'/parameters/environment',label:'Environment',description:'Environment variant',defaultValue:'catacombs',value:String(p.environment??'catacombs'),valid:true})]}]};}
function setPath(obj:any,path:string,value:JsonValue){const parts=path.split('/').filter(Boolean);const root=clone(obj);let at=root;for(let i=0;i<parts.length-1;i++)at=at[parts[i]]??(at[parts[i]]={});at[parts.at(-1)!]=value;return root;}
export function applyStructuredField(recipe:AssetForgeRecipe,field:AssetAuthoringField,value:JsonValue){if(field.kind==='number'&&(typeof value!=='number'||!Number.isFinite(value)||!Number.isSafeInteger(value)&&Number.isInteger(value)||(field.min!==undefined&&value<field.min)||(field.max!==undefined&&value>field.max)))return{ok:false as const,diagnostic:diag(diagnostic('AF_SCHEMA_VIOLATION','invalid numeric authoring value','serialization',field.path))};const raw=setPath(recipe,field.path,value);const n=normalizeAssetForgeRecipe(raw);return n.ok?{ok:true as const,recipe:n.value}:{ok:false as const,diagnostic:diag(n.error)};}
export function parseAndAdmitRecipeJson(text:string,last:AssetForgeRecipe){if(text.length>limits.maxProjectBytes)return{ok:false as const,recipe:last,diagnostics:[diag(diagnostic('AF_UNSAFE_SERIALIZATION_VALUE','import exceeds workbench size limit','serialization'))]};const parsed=parseSafeJson(text,{maxDepth:12,maxEntries:4096,maxStringLength:8192,maxArrayLength:2048,minNumber:-1e12,maxNumber:1e12});if(!parsed.ok)return{ok:false as const,recipe:last,diagnostics:[diag(parsed.error)]};if(JSON.stringify(parsed.value).match(urlish))return{ok:false as const,recipe:last,diagnostics:[diag(diagnostic('AF_UNSAFE_SERIALIZATION_VALUE','executable, URL, absolute path, or traversal content rejected','serialization'))]};const n=normalizeAssetForgeRecipe(parsed.value);return n.ok?{ok:true as const,recipe:n.value,diagnostics:[]}:{ok:false as const,recipe:last,diagnostics:[diag(n.error)]};}
export function createRecipeEditorState(recipe:AssetForgeRecipe):AssetRecipeEditorState{return{structured:buildAuthoringSchema(recipe),jsonText:JSON.stringify(recipe,null,2),lastAdmittedDraft:recipe,parseDiagnostics:[],admissionDiagnostics:[]};}
export function normalizeWorkbenchSeed(seed:string){return String(seed).trim().normalize('NFKC').replace(/\s+/g,'.').toLowerCase().slice(0,128)||'seed.default';}
export function nextSeed(seed:string,delta=1){const m=normalizeWorkbenchSeed(seed).match(/^(.*?)(\d+)$/);return m?`${m[1]}${Math.max(0,Number(m[2])+delta)}`:`${normalizeWorkbenchSeed(seed)}.${delta>0?'next':'prev'}`;}
export function randomizeSeedFromBrowserEntropy(bytes:Uint32Array){return `seed.${Array.from(bytes).map(v=>v.toString(16).padStart(8,'0')).join('').slice(0,32)}`;}
export function computeBudgetSummary(asset?:GeneratedAssetDefinition):AssetBudgetSummary{const current:Partial<AssetBudget>={components:asset?.components.length??0,materials:asset?.materials.length??0,lods:asset?.lods.length??0,colliders:asset?.physics?.colliders.length??0,externalDependencies:asset?.dependencies.length??0,diagnostics:asset?.diagnostics.length??0,vertices:asset?.components.reduce((s,c)=>s+(c.geometry?.vertexBudget??0),0)??0,indices:asset?.components.reduce((s,c)=>s+(c.geometry?.indexBudget??0),0)??0};const remaining:any={},util:any={},ex:string[]=[];for(const [k,limit] of Object.entries(DEFAULT_ASSET_BUDGET) as [keyof AssetBudget,number][]){const v=(current[k]??0) as number;remaining[k]=Math.max(0,limit-v);util[k]=limit?Number((v/limit).toFixed(4)):0;if(v>limit)ex.push(k);}return{current,limit:DEFAULT_ASSET_BUDGET,remaining,exceeded:ex,utilization:util};}
export function readiness(status:AssetWorkbenchStatus, project:AssetForgeWorkbenchProject, result?:GeneratedAssetDefinition):AssetReadinessStatus{if(status==='DIRTY'||digestRecipe(project.recipeDraft)!==digestRecipe(project.generationRequest.recipe))return 'DIRTY';if(status==='FAILED')return 'GENERATION_FAILED';if(!result)return 'DRAFT';if(!result.validation?.passed)return 'VALIDATION_FAILED';if(result.diagnostics.some(d=>(d.severity??'ERROR')==='ERROR'))return 'VALIDATION_FAILED';if(computeBudgetSummary(result).exceeded.length)return 'VALIDATION_FAILED';if(result.diagnostics.some(d=>(d.severity)==='WARNING'))return 'VALID_WITH_WARNINGS';return result.integrity?.digest?'CANDIDATE_READY':'VALID';}
export function buildHierarchy(asset?:GeneratedAssetDefinition):readonly AssetHierarchyNode[]{if(!asset)return[];const nodes:AssetHierarchyNode[]=[];for(const c of asset.components)nodes.push({id:c.id,kind:'component',label:c.id,...(c.parentId?{parentId:c.parentId}:{}),children:[...(c.children??[]),...(c.geometry?[c.geometry.id]:[]),...c.materialBindings.map(m=>m.materialId)],diagnosticCount:asset.diagnostics.filter(d=>d.componentId===c.id||d.affectedId===c.id).length});for(const c of asset.components)if(c.geometry)nodes.push({id:c.geometry.id,kind:'geometry',label:c.geometry.kind,parentId:c.id,children:[],diagnosticCount:0});for(const m of asset.materials)nodes.push({id:m.id,kind:'material',label:m.name??m.family,children:[],diagnosticCount:0});for(const s of asset.sockets)nodes.push({id:s.id,kind:'socket',label:s.kind,...(s.target.componentId?{parentId:s.target.componentId}:{}),children:[],diagnosticCount:0});for(const i of asset.interactions)nodes.push({id:i.id,kind:'interaction',label:i.kind,...(i.componentId?{parentId:i.componentId}:{}),children:[],diagnosticCount:0});for(const l of asset.lods)nodes.push({id:l.id,kind:'lod',label:`LOD ${l.level}`,children:[],diagnosticCount:0});return nodes.sort((a,b)=>`${a.kind}:${a.id}`.localeCompare(`${b.kind}:${b.id}`));}
export function buildInspectorSections(project:AssetForgeWorkbenchProject, asset?:GeneratedAssetDefinition):readonly AssetInspectorSection[]{const sections:AssetInspectorSection[]=[{id:'recipe',title:'Recipe',rows:[['Recipe ID',project.recipeDraft.recipeId],['Generator',`${project.recipeDraft.generator.id}@${project.recipeDraft.generator.version}`],['Seed',project.recipeDraft.seed],['Revision',String(project.recipeRevision)]].map(([label,value])=>({label,value}))}];if(asset){sections.push({id:'geometry',title:'Geometry',rows:[['Components',String(asset.components.length)],['Meshes',String(asset.components.filter(c=>c.geometry).length)],['Vertices',String(computeBudgetSummary(asset).current.vertices??0)],['Indices',String(computeBudgetSummary(asset).current.indices??0)],['Sockets',String(asset.sockets.length)],['LODs',String(asset.lods.length)]].map(([label,value])=>({label,value}))},{id:'provenance',title:'Provenance',rows:[['Digest',asset.integrity.digest],['Root seed',asset.provenance.rootSeed],['Validation',asset.validation.profile]].map(([label,value])=>({label,value}))});}return sections;}
export function diffRevisions(a:AssetRevision,b:AssetRevision):AssetRevisionDiff{const changes:any[]=[];const walk=(x:any,y:any,p='')=>{if(changes.length>=limits.maxDiffs)return;if(JSON.stringify(x)===JSON.stringify(y))return;if(!x||!y||typeof x!=='object'||typeof y!=='object'){changes.push({path:p||'/',classification:p.includes('material')?'Material-binding change':p.includes('socket')||p.includes('interaction')?'Interaction change':p.includes('seed')||p.includes('generator')||p.includes('recipeId')?'Recipe identity change':'Generated geometry change',before:String(x),after:String(y)});return;}for(const k of Array.from(new Set([...Object.keys(x),...Object.keys(y)])).sort())walk(x[k],y[k],`${p}/${k}`);};walk(a.recipe,b.recipe);return{fromRevision:a.revision,toRevision:b.revision,changes,truncated:changes.length>=limits.maxDiffs};}
export class AssetWorkbenchGenerationController{private seq=0;private abort?:AbortController;constructor(private registry=createRegisteredAssetGeneratorRegistry()){}cancel(){this.abort?.abort();}async generate(project:AssetForgeWorkbenchProject,onState?:(s:AssetWorkbenchStatus)=>void){const seq=++this.seq;this.abort?.abort();this.abort=new AbortController();onState?.('ADMITTING');const admitted=admitJsonObject(project.recipeDraft);if(!admitted.ok)return{status:'FAILED' as const,diagnostics:[diag(admitted.error)]};onState?.('GENERATING');const result=await generateAsset({recipe:project.recipeDraft,targetSchemaVersion:ASSET_FORGE_RECIPE_SCHEMA_VERSION},{registry:this.registry,signal:this.abort.signal,onProgress:e=>{void e;}});if(seq!==this.seq)return{status:'STALE' as const,diagnostics:[diag(diagnostic('AF_CANONICAL_AUTHORITY_VIOLATION','stale generation result ignored','validation'))]};if(result.status==='CANCELLED')return{status:'CANCELLED' as const,diagnostics:result.diagnostics.map(diag)};if(result.status==='FAILED')return{status:'FAILED' as const,diagnostics:result.diagnostics.map(diag)};if(result.status==='SUCCEEDED')return{status:'SUCCEEDED' as const,asset:result.asset,diagnostics:result.diagnostics.map(diag)};return{status:'FAILED' as const,diagnostics:[]};}}
export interface AssetPreviewController { readonly state: AssetPreviewState; dispose():void; replace(asset:GeneratedAssetDefinition):void; setMode(mode:AssetPreviewMode):void; }
export class BrowserAssetPreviewController implements AssetPreviewController{private adapter?:ThreeAssetPreviewAdapter;state:AssetPreviewState={mode:'neutral-clay',overlays:['grid','axes','bounds'],cameraPreset:'isometric-inspection',adapterOwned:true,disposedResources:0,contextLost:false};constructor(private host:HTMLElement){}replace(asset:GeneratedAssetDefinition){this.adapter?.dispose();this.adapter=new ThreeAssetPreviewAdapter(this.host);this.adapter.initialize({candidate:{id:asset.recipe.recipeId,requirementId:'authoring',reviewReadiness:'READY_FOR_HUMAN_REVIEW',integrity:asset.integrity,spatial:{bounds:asset.components[0]?.geometry?.bounds},previewPrimitiveAssembly:{primitives:[]}} as any,overlays:[...this.state.overlays]});this.state={...this.state,disposedResources:this.adapter.state.disposed,contextLost:false};}setMode(mode:AssetPreviewMode){this.state={...this.state,mode};this.adapter?.setMode(mode==='wireframe'?'wireframe':mode==='uv-checker'?'uvChecker':'solid');}dispose(){this.adapter?.dispose();this.host.replaceChildren();}}
export interface AssetWorkbenchPersistenceAdapter { load(key:string):string|null; save(key:string,value:string):void; delete(key:string):void; }
export class AssetWorkbenchProjectStore{constructor(private storage:AssetWorkbenchPersistenceAdapter={load:k=>globalThis.localStorage?.getItem(k)??null,save:(k,v)=>globalThis.localStorage?.setItem(k,v),delete:k=>globalThis.localStorage?.removeItem(k)}){}saveProject(project:AssetForgeWorkbenchProject){const text=JSON.stringify(project);if(text.length>limits.maxProjectBytes)throw new Error('Asset Forge project exceeds bounded storage size');this.storage.save(`af.workbench.project.${project.projectId}.v1`,text);}loadProject(projectId:string){const raw=this.storage.load(`af.workbench.project.${projectId}.v1`);if(!raw)return undefined;try{return migrateWorkbenchProject(JSON.parse(raw));}catch{return undefined;}}deleteProject(projectId:string){this.storage.delete(`af.workbench.project.${projectId}.v1`);}}
export function migrateWorkbenchProject(input:unknown):AssetForgeWorkbenchProject{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('invalid project');for(const k of Object.keys(input as any))if(!closedProjectKeys.has(k))throw new Error('unknown project field');const p=input as any;const nr=normalizeAssetForgeRecipe(p.recipeDraft??p.recipe);if(!nr.ok)throw new Error(nr.error.summary);return Object.freeze({projectVersion:AssetForgeWorkbenchProjectVersion,projectId:String(p.projectId??`project.${digestRecipe(nr.value).slice(0,16)}`),title:String(p.title??nr.value.metadata.name??'Asset Forge Project'),recipeDraft:nr.value,recipeRevision:Number.isSafeInteger(p.recipeRevision)?p.recipeRevision:0,generationRequest:{recipe:nr.value,targetSchemaVersion:ASSET_FORGE_RECIPE_SCHEMA_VERSION},...(p.lastSuccessfulIdentity?{lastSuccessfulIdentity:String(p.lastSuccessfulIdentity)}:{}),...(p.authoringMetadata?{authoringMetadata:p.authoringMetadata}:{})});}
export function importWorkbenchJson(text:string,preserved:AssetForgeWorkbenchProject):AssetWorkbenchImportResult{const admitted=parseAndAdmitRecipeJson(text,preserved.recipeDraft);if(admitted.ok)return{status:'IMPORTED',project:createDefaultAssetForgeWorkbenchProject(admitted.recipe),diagnostics:[]};try{return{status:'IMPORTED',project:migrateWorkbenchProject(JSON.parse(text)),diagnostics:[]};}catch{return{status:'REJECTED',diagnostics:admitted.diagnostics,preservedProject:preserved};}}
export function exportWorkbench(project:AssetForgeWorkbenchProject,req:AssetWorkbenchExportRequest,asset?:GeneratedAssetDefinition){const body=req.kind==='canonical-recipe'?project.recipeDraft:req.kind==='workbench-project'?project:req.kind==='integrity-record'?asset?.integrity:req.kind==='provenance-report'?asset?.provenance:req.kind==='diagnostic-report'?asset?.diagnostics:req.kind==='geometry-metrics-report'?computeBudgetSummary(asset):{projectId:project.projectId,readiness:readiness('SUCCEEDED',project,asset),sections:buildInspectorSections(project,asset)};return JSON.stringify(body??{},null,2);}
const presetFamilies=['floor','wall','arch','door-frame','pillar','sarcophagus','crate','chest','brazier','mechanism','sword','shield','helmet','armor','catacombs-fallback'];
export const assetWorkbenchPresetRegistry:AssetWorkbenchPresetRegistry={list:()=>presetFamilies.map(f=>({presetId:`preset.${f}`,version:'1.0.0',generator:f.match(/sword|shield|helmet|armor/)?{id:'af.generator.equipment',version:'1.0.0'}:f==='catacombs-fallback'?{id:'af.generator.catacombs',version:'1.0.0'}:{id:f.match(/floor|wall|arch|door|pillar|sarcophagus/)?'af.generator.architecture':'af.generator.environment-props',version:'1.0.0'},family:f==='catacombs-fallback'?'catacombs':f,subtype:f,configuration:{family:f,subtype:f,tier:1,rank:'common',size:1},compatibleRecipeVersion:ASSET_FORGE_RECIPE_SCHEMA_VERSION,description:`Representative ${f} authoring preset`,tags:['af-dev3',f],budgetClassification:'standard',capabilityRequirements:{webgl:2}})),get:(id,version)=>assetWorkbenchPresetRegistry.list().find(p=>p.presetId===id&&(!version||p.version===version))};
export function catacombsCompatibilityViews():readonly CatacombsAssetCompatibilityView[]{return CATACOMBS_REFERENCE_ASSET_REGISTRY.assets.map(a=>({assetId:a.id,generatorBinding:'af.generator.catacombs@1.0.0',registryFamily:a.family,placementCategories:[a.category],authoredCandidate:true,proceduralFallback:true,connectionMetadata:{snap:(a as any).snap??'grid',pivot:(a as any).pivot??'center'},status:'SUPPORTED' as const,blockingDiagnostics:[]})).sort((a,b)=>a.assetId.localeCompare(b.assetId));}
export class AssetWorkbenchController{readonly generation=new AssetWorkbenchGenerationController();state:AssetForgeWorkbenchState;constructor(project=createDefaultAssetForgeWorkbenchProject()){const rev={revision:project.recipeRevision,recipe:project.recipeDraft,canonicalDigest:digestRecipe(project.recipeDraft)};this.state={project,ui:createDefaultAssetForgeWorkbenchUiState(),status:'IDLE',readiness:'DRAFT',dirty:false,generating:false,diagnostics:[],revisions:[rev],redo:[]};}dispatch(action:AssetWorkbenchAction){if(action.type==='SET_UI'){this.state={...this.state,ui:{...this.state.ui,...action.ui}};return;}if(action.type==='SET_FIELD'){const field=buildAuthoringSchema(this.state.project.recipeDraft).groups.flatMap(g=>g.fields).find(f=>f.path===action.path);if(!field)return;const applied=applyStructuredField(this.state.project.recipeDraft,field,action.value);if(!applied.ok){this.state={...this.state,diagnostics:[applied.diagnostic]};return;}const rev=this.state.project.recipeRevision+1;const project={...this.state.project,recipeDraft:applied.recipe,recipeRevision:rev,generationRequest:{...this.state.project.generationRequest,recipe:applied.recipe}};this.state={...this.state,project,status:'DIRTY',readiness:'DIRTY',dirty:true,revisions:[...this.state.revisions,{revision:rev,recipe:applied.recipe,canonicalDigest:digestRecipe(applied.recipe)}].slice(-50),redo:[]};}}async generate(){this.state={...this.state,status:'GENERATING',generating:true};const r=await this.generation.generate(this.state.project,s=>{this.state={...this.state,status:s};});if(r.status==='SUCCEEDED'){const project={...this.state.project,lastSuccessfulIdentity:r.asset.integrity.digest};this.state={...this.state,project,result:r.asset,lastSuccessfulResult:r.asset,status:'SUCCEEDED',generating:false,dirty:false,diagnostics:r.diagnostics,readiness:readiness('SUCCEEDED',project,r.asset)};}else this.state={...this.state,status:r.status==='STALE'?'STALE':r.status,readiness:r.status==='CANCELLED'?'DRAFT':'GENERATION_FAILED',generating:false,diagnostics:r.diagnostics};} }
export const AssetForgeWorkbench = AssetWorkbenchController;
