import Ajv2020Module, { type ErrorObject, type ValidateFunction } from 'ajv/dist/2020.js'; import addFormatsModule from 'ajv-formats';
const Ajv2020 = Ajv2020Module as unknown as new (opts: Record<string, unknown>) => { addSchema: unknown; getSchema(id: string): ValidateFunction | undefined; compile(schema: unknown): ValidateFunction };
const addFormats = addFormatsModule as unknown as (ajv: unknown) => void;
import dungeonConfig from '../../../docs/blueprints/catacombs-reference-generator/schemas/dungeon-config.schema.json' with { type: 'json' }; import envProfile from '../../../docs/blueprints/catacombs-reference-generator/schemas/environment-profile.schema.json' with { type: 'json' }; import graphTemplate from '../../../docs/blueprints/catacombs-reference-generator/schemas/graph-template.schema.json' with { type: 'json' }; import assetRegistry from '../../../docs/blueprints/catacombs-reference-generator/schemas/asset-registry.schema.json' with { type: 'json' }; import manifest from '../../../docs/blueprints/catacombs-reference-generator/schemas/authorized-dungeon-manifest.schema.json' with { type: 'json' }; import resolvedDungeon from '../../../docs/blueprints/catacombs-reference-generator/schemas/resolved-dungeon.schema.json' with { type: 'json' }; import diagnostics from '../../../docs/blueprints/catacombs-reference-generator/schemas/generation-diagnostics.schema.json' with { type: 'json' }; import validationResult from '../../../docs/blueprints/catacombs-reference-generator/schemas/validation-result.schema.json' with { type: 'json' };
import type { AssetRegistry, AuthorizedDungeonManifest, DungeonConfig, EnvironmentProfile, GenerationDiagnostics, GraphTemplate, ResolvedDungeon, ValidationResult } from '../contracts/index.js';
export interface SchemaValidationIssue{readonly instancePath:string;readonly schemaPath:string;readonly keyword:string;readonly message:string;readonly params?:Readonly<Record<string,unknown>>;} export interface SchemaValidationResult<T>{readonly valid:boolean;readonly value?:T;readonly issues:readonly SchemaValidationIssue[];}
const ajv=new Ajv2020({allErrors:true,strict:true,schemas:[dungeonConfig,envProfile,graphTemplate,assetRegistry,manifest,resolvedDungeon,diagnostics,validationResult]}); addFormats(ajv);
function compile(id:string):ValidateFunction{return ajv.getSchema(id)??ajv.compile({$ref:id});} const ids={cfg:'https://example.invalid/schemas/catacombs-reference-generator/dungeon-config.schema.json',env:'https://example.invalid/schemas/catacombs-reference-generator/environment-profile.schema.json',graph:'https://example.invalid/schemas/catacombs-reference-generator/graph-template.schema.json',asset:'https://example.invalid/schemas/catacombs-reference-generator/asset-registry.schema.json',manifest:'https://example.invalid/schemas/catacombs-reference-generator/authorized-dungeon-manifest.schema.json',resolved:'https://example.invalid/schemas/catacombs-reference-generator/resolved-dungeon.schema.json',diag:'https://example.invalid/schemas/catacombs-reference-generator/generation-diagnostics.schema.json',val:'https://example.invalid/schemas/catacombs-reference-generator/validation-result.schema.json'} as const;
function safe(errors:ErrorObject[]|null|undefined):SchemaValidationIssue[]{return (errors??[]).map(e=>({instancePath:e.instancePath,schemaPath:e.schemaPath,keyword:e.keyword,message:e.message??'schema validation failed',params:e.params as Record<string,unknown>}));} function run<T>(v:ValidateFunction,input:unknown):SchemaValidationResult<T>{const ok=v(input); return ok?{valid:true,value:input as T,issues:[]}:{valid:false,issues:safe(v.errors)};}
export const validators={dungeonConfig:compile(ids.cfg),environmentProfile:compile(ids.env),graphTemplate:compile(ids.graph),assetRegistry:compile(ids.asset),authorizedManifest:compile(ids.manifest),resolvedDungeon:compile(ids.resolved),generationDiagnostics:compile(ids.diag),validationResult:compile(ids.val)} as const;
export function validateDungeonConfig(input:unknown){return run<DungeonConfig>(validators.dungeonConfig,input);} export function validateEnvironmentProfile(input:unknown){return run<EnvironmentProfile>(validators.environmentProfile,input);} export function validateGraphTemplate(input:unknown){return run<GraphTemplate>(validators.graphTemplate,input);} export function validateAssetRegistry(input:unknown){return run<AssetRegistry>(validators.assetRegistry,input);} export function validateAuthorizedManifest(input:unknown){return run<AuthorizedDungeonManifest>(validators.authorizedManifest,input);} export function validateResolvedDungeon(input:unknown){return run<ResolvedDungeon>(validators.resolvedDungeon,input);} export function validateGenerationDiagnostics(input:unknown){return run<GenerationDiagnostics>(validators.generationDiagnostics,input);} export function validateValidationResult(input:unknown){return run<ValidationResult>(validators.validationResult,input);}
