import { generateAsset } from '../../../src/workbench/asset-forge/generators/runtime.js';
import { AssetGeneratorRegistry } from '../../../src/workbench/asset-forge/generators/registry.js';
import { createDefaultTrustedOperationRegistry } from '../../../src/workbench/asset-forge/operations/registry.js';
import { AssetRecipeMigrationRegistry } from '../../../src/workbench/asset-forge/migrations/registry.js';
import { ok } from '../../../src/workbench/asset-forge/core/results.js';
import { DeterministicRandomContext } from '../../../src/workbench/asset-forge/random/deterministicRandom.js';
import type { AssetGeneratorPack, AssetForgeRecipe, GeneratedAssetDefinition, JsonObject } from '../../../src/workbench/asset-forge/contracts/authoritative.js';

const budget={components:16,hierarchyDepth:4,geometryOperations:16,vertices:1000,indices:3000,instances:16,bones:8,skinInfluences:4,animationClips:4,animationTracks:8,animationKeys:64,animationDurationSeconds:30,colliders:8,joints:4,materials:8,textures:4,textureDimension:128,textureDecodedBytes:1048576,lods:4,externalDependencies:4,packageBytes:1048576,workUnits:1000,diagnostics:32,inputDepth:8,collectionSize:64};
function recipe(seed='a'):AssetForgeRecipe{return{schemaVersion:'asset-forge.recipe.v1',recipeId:'r.test',origin:'PROCEDURAL',generator:{id:'test.gen',version:'1.0.0',familyId:'test'},seed,parameters:{size:1},components:[],materials:[],sockets:[],interactions:[],lods:[],metadata:{}};}
function pack():AssetGeneratorPack{return{descriptor:{id:'test.gen',version:'1.0.0',familyIds:['test'],supportedOrigins:['PROCEDURAL'],capabilities:{webgl:2},requiredTrustedOperations:[{id:'af.primitive',version:'1.0.0'}],inputSchemaVersion:'1.0.0',outputContractVersion:'asset-forge.generated.v1',budgetLimits:budget,migrationCompatibility:['asset-forge.recipe.v1'],runtimeRequirements:{webgl:2}},normalizeConfig(input:unknown){return ok(input as JsonObject);},async generate(ctx){const n=ctx.random.next('geometry');const asset={contractVersion:'asset-forge.generated.v1',recipe:ctx.recipe,components:[],geometries:[],materials:[],sockets:[],interactions:[],lods:[],dependencies:[],capabilities:{status:'SUPPORTED',capabilities:{webgl:2,maxTextureSize:128,maxVertices:1000,floatTextures:false,maxSkinJoints:8,instancing:true,sdf:false,rapier:false,animation:'NONE',glb:true},notes:[]},diagnostics:[],validation:{profile:'',passed:true,diagnostics:[]},provenance:{} as never,integrity:{} as never,metadata:{n}} as GeneratedAssetDefinition&{metadata:{n:number}};return{status:'SUCCEEDED',asset,diagnostics:[]};}};}

test('AF-DEV1 deterministic runtime digest, version lookup, duplicate registration, capabilities, budget, migration, and cancellation',async()=>{const reg=new AssetGeneratorRegistry();expect(reg.register(pack()).ok).toBe(true);expect(reg.register(pack()).ok).toBe(false);expect(reg.get('test.gen','2.0.0')).toBeUndefined();const a=await generateAsset({recipe:recipe('same'),capabilities:{webgl:2}},{registry:reg});const b=await generateAsset({recipe:recipe('same'),capabilities:{webgl:2}},{registry:reg});const c=await generateAsset({recipe:recipe('other'),capabilities:{webgl:2}},{registry:reg});expect(a.status).toBe('SUCCEEDED');expect(b.status).toBe('SUCCEEDED');expect(c.status).toBe('SUCCEEDED');if(a.status==='SUCCEEDED'&&b.status==='SUCCEEDED'&&c.status==='SUCCEEDED'){expect(a.asset.integrity.digest).toBe(b.asset.integrity.digest);expect(a.asset.integrity.digest).not.toBe(c.asset.integrity.digest);expect(JSON.stringify(a.asset)).not.toMatch(/Object3D|BufferGeometry|Material|Rapier|function/);}const badCap=await generateAsset({recipe:recipe(),capabilities:{webgl:1}},{registry:reg});expect(badCap.status).toBe('FAILED');const badBudget=await generateAsset({recipe:{...recipe(),components:new Array(17).fill(0).map((_,i)=>({id:`c${i}`,transform:{position:[0,0,0],rotation:[0,0,0,1],scale:[1,1,1]},visible:true,renderIntent:'OPAQUE',materialBindings:[]}))},capabilities:{webgl:2}},{registry:reg});expect(badBudget.status).toBe('FAILED');const migrations=new AssetRecipeMigrationRegistry();expect(migrations.register({id:'m1',sourceVersion:'old',targetVersion:'asset-forge.recipe.v1',migrate(input){return ok({...input,schemaVersion:'asset-forge.recipe.v1'} as JsonObject);}}).ok).toBe(true);expect((await generateAsset({recipe:{...recipe(),schemaVersion:'old'},targetSchemaVersion:'asset-forge.recipe.v1',capabilities:{webgl:2}},{registry:reg,migrations})).status).toBe('SUCCEEDED');const ac=new AbortController();ac.abort();expect((await generateAsset({recipe:recipe(),capabilities:{webgl:2}},{registry:reg,signal:ac.signal})).status).toBe('CANCELLED');});

test('AF-DEV1 admission rejects prototype tricks, executable values, unknown operations; substreams isolated',async()=>{const r=new DeterministicRandomContext('seed','id');const g1=r.next('geometry');r.next('materials');const r2=new DeterministicRandomContext('seed','id');expect(r2.next('geometry')).toBe(g1);const reg=new AssetGeneratorRegistry();const p=pack();reg.register({...p,descriptor:{...p.descriptor,requiredTrustedOperations:[{id:'missing.op',version:'1.0.0'}]}});expect((await generateAsset({recipe:recipe(),capabilities:{webgl:2}},{registry:reg,operations:createDefaultTrustedOperationRegistry()})).status).toBe('FAILED');expect((await generateAsset({recipe:{...recipe(),parameters:{fn:()=>1}},capabilities:{webgl:2}},{registry:new AssetGeneratorRegistry()})).status).toBe('FAILED');const polluted=JSON.parse('{"schemaVersion":"asset-forge.recipe.v1","__proto__":{"polluted":true}}');expect((await generateAsset({recipe:polluted},{registry:new AssetGeneratorRegistry()})).status).toBe('FAILED');});
