import { ENVIRONMENTAL_PROP_REGISTRY, buildEnvironmentalPropViews, environmentalCategoryForRecord, summarizeEnvironmentalProps } from '../../../src/dungeon/environmentalProps.js';
import { generateCatacombs } from '../../../src/dungeon/generationPipeline.js';
import { canonicalStringify } from '../../../src/dungeon/canonical/serializer.js';

const config={schemaVersion:'1.0.0',generatorVersion:'catacombs-gen-1',rootSeed:'12345',generationMode:'procedural',environmentId:'catacombs',layoutProfileId:'graph.catacombs.layered_braided',gameType:'hunt',difficulty:'normal',authorizedPlayerCount:4,structuralModifiers:[],gameplayModifiers:[],contentTableVersions:{monsters:'1'},assetRegistryVersion:'catacombs-assets-1'} as const;
function dungeon(seed='12345',rooms=18){const r=generateCatacombs({config:{...config,rootSeed:seed},generation:{targetRoomCount:rooms,sizeProfile:rooms>30?'large':'small',areaBudget:rooms>30?42000:14000,targetPackingDensity:.34,minimumRoomPadding:3,maximumNodeDegree:5,softForwardBiasWeight:.12},requireReturnPortal:true}); if(!r.ok)throw new Error(r.failure.message); return r;}

describe('DTD-D2 environmental prop taxonomy and placement views',()=>{
  test('registry covers required categories and maps unknown explicitly',()=>{expect(ENVIRONMENTAL_PROP_REGISTRY.map(e=>e.category)).toEqual(expect.arrayContaining(['COFFIN','SARCOPHAGUS','TOMB_MARKER','PILLAR','BROKEN_PILLAR','RUBBLE','DEBRIS','CANDLE','CANDLE_CLUSTER','STATUE','SHRINE','CHAIN','WALL_DECORATION','FLOOR_DECORATION','ARCHITECTURAL_TRIM','UNKNOWN_ENVIRONMENTAL_PROP'])); expect(environmentalCategoryForRecord({category:'prop',requestedAssetFamily:'not_real',id:'x',source:{roomId:'r'},assetResolutionState:'FALLBACK',transform:{position:{x:0,y:0,z:0},orientation:0,scale:[1,1,1]},materialGroupIds:[],placementRole:'room_prop',deterministicVariant:{seedNamespace:'construction',candidateIds:[]},canonicalTags:[]} as never)).toBe('UNKNOWN_ENVIRONMENTAL_PROP');});
  test('same seed creates stable environmental view ordering and IDs',()=>{const a=buildEnvironmentalPropViews(dungeon().construction.records); const b=buildEnvironmentalPropViews(dungeon().construction.records); expect(a.map(v=>v.id)).toEqual(b.map(v=>v.id)); expect(canonicalStringify(a as never)).toBe(canonicalStringify(b as never)); expect(a.length).toBeGreaterThan(20); expect(a.every(v=>v.ownerId&&v.validationState==='valid')).toBe(true);});
  test('different seeds vary within bounded density and large dungeon remains bounded',()=>{const a=summarizeEnvironmentalProps(dungeon('12345').construction.records); const b=summarizeEnvironmentalProps(dungeon('12346').construction.records); const large=summarizeEnvironmentalProps(dungeon('77777',24).construction.records); expect(a.total).toBeGreaterThan(0); expect(b.total).toBeGreaterThan(0); expect(Math.abs(a.total-b.total)).toBeLessThan(200); expect(large.total).toBeLessThan(1200);});
  test('presentation options and overlays do not change canonical render input serialization',()=>{const r=dungeon(); const before=canonicalStringify({renderInput:r.renderInput,construction:r.construction.canonicalProjection,gameplay:r.gameplay.canonicalProjection} as never); const overlay={environmental:{enabled:false,categories:{COFFIN:false}},selection:'environment.any',quality:'low',reducedMotion:true}; const after=canonicalStringify({renderInput:r.renderInput,construction:r.construction.canonicalProjection,gameplay:r.gameplay.canonicalProjection} as never); expect(overlay).toBeTruthy(); expect(after).toBe(before);});
  test('invalid transforms are classified invalid and omitted by render callers',()=>{const views=buildEnvironmentalPropViews([{category:'prop',requestedAssetFamily:'coffin',id:'bad',source:{roomId:'r'},assetResolutionState:'FALLBACK',transform:{position:{x:NaN,y:0,z:0},orientation:0,scale:[1,1,1]},materialGroupIds:[],placementRole:'room_prop',deterministicVariant:{seedNamespace:'construction',candidateIds:[]},canonicalTags:[]} as never]); expect(views[0]!.validationState).toBe('invalid');});
});
