/** @jest-environment jsdom */
import { jest } from '@jest/globals';
class V{constructor(public x=0,public y=0,public z=0){} set(x:number,y:number,z:number){this.x=x;this.y=y;this.z=z;return this;} toArray(){return [this.x,this.y,this.z];}}
class O{children:any[]=[];name='';visible=true;position=new V();parent?:any; add(...o:any[]){this.children.push(...o); o.forEach(x=>x.parent=this);} clear(){this.children=[];} removeFromParent(){this.parent?.children.splice(this.parent.children.indexOf(this),1);} traverse(cb:any){cb(this); this.children.forEach(c=>c.traverse?.(cb));}}
class Scene extends O{background:any;fog:any;} class Group extends O{} class Mesh extends O{constructor(public geometry:any,public material:any){super();}} class InstancedMesh extends Mesh{matrices:any[]=[]; constructor(g:any,m:any,public count:number){super(g,m);} setMatrixAt(i:number,m:any){this.matrices[i]=m;}}
class LineSegments extends Mesh{} class Material{opacity=1;needsUpdate=false; constructor(public opts:any={}){} dispose(){this.disposed=true;} disposed=false;} class MeshStandardMaterial extends Material{} class LineBasicMaterial extends Material{}
class Geometry{points:any[]=[]; constructor(public type='BufferGeometry'){} dispose(){this.disposed=true;} disposed=false; setFromPoints(p:any[]){this.points=p;return this;}} class BoxGeometry extends Geometry{constructor(...a:any[]){super('BoxGeometry');}} class ConeGeometry extends Geometry{constructor(...a:any[]){super('ConeGeometry');}} class BufferGeometry extends Geometry{}
class Matrix4{makeTranslation(){return this;} compose(){return this;}} class Quaternion{setFromEuler(){return this;}} class Euler{constructor(...a:any[]){} } class Color{constructor(public c:any){}} class Fog{constructor(...a:any[]){} } class HemisphereLight extends O{constructor(...a:any[]){super();}} class DirectionalLight extends O{constructor(...a:any[]){super();}}
class OrthographicCamera extends O{left:any;right:any;top:any;bottom:any;zoom=1; constructor(l:any,r:any,t:any,b:any){super(); this.left=l;this.right=r;this.top=t;this.bottom=b;} lookAt(...a:any[]){} updateProjectionMatrix(){this.updated=true;} updated=false;}
class WebGLRenderer{last:any; domElement=document.createElement('canvas'); outputColorSpace:any; shadowMap:any={enabled:false}; info={render:{calls:7,triangles:11}}; constructor(public opts:any){} setPixelRatio(v:number){this.pixelRatio=v;} setSize(w:number,h:number){this.size=[w,h];} render(s:any,c:any){this.last=[s,c];} dispose(){this.disposed=true;} pixelRatio=0; size:any; disposed=false;}
await jest.unstable_mockModule('three',()=>({Scene,Group,Mesh,InstancedMesh,LineSegments,MeshStandardMaterial,LineBasicMaterial,BoxGeometry,ConeGeometry,BufferGeometry,Matrix4,Quaternion,Euler,Vector3:V,Color,Fog,HemisphereLight,DirectionalLight,OrthographicCamera,WebGLRenderer,SRGBColorSpace:'srgb',MathUtils:{clamp:(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v))}}));
const { ThreeDungeonRenderer } = await import('../../../src/dungeon/rendering/DungeonRenderer.js');
const { DEFAULT_RENDERER_OPTIONS } = await import('../../../src/dungeon/rendering/types.js');
const input={schemaVersion:'1.0.0',rendererContractVersion:'catacombs.render_input.d2.v1',environment:{environmentId:'catacombs',environmentVersion:'1',displayName:'Catacombs'},geometry:{corridors:[{id:'c',graphEdgeId:'e',category:'x',width:1,bendCount:0,strategy:'s',centerline:[{x:0,y:0,level:0},{x:1,y:1,level:0}],footprint:[{x:0,y:0,level:0}]}],doorways:[{cells:[{x:0,y:0,level:0}]}],boundaries:[{tile:{x:0,y:0,level:0},side:'s',boundaryType:'wall'},{tile:{x:0,y:0,level:0},side:'s',boundaryType:'wall'},{tile:{x:1,y:1,level:0},side:'n',boundaryType:'secret_door'}],tileLayers:{width:2,height:2,layers:[{id:'tileType',base64:Buffer.from(Uint8Array.from([1,2,3,0])).toString('base64')},{id:'roomOwner',length:4}]}},construction:{records:[],sockets:[],batches:[],assetResolutions:[]},gameplayPresentation:{placements:[{id:'g',kind:'BOSS'}],dependencies:[]},telegraphs:[]};

describe('T1B real browser renderer lifecycle boundary with deterministic WebGL adapter',()=>{
 beforeEach(()=>{jest.useFakeTimers(); (globalThis as any).requestAnimationFrame=jest.fn(()=>123); (globalThis as any).cancelAnimationFrame=jest.fn(); (HTMLCanvasElement.prototype as any).setPointerCapture=jest.fn(); Object.defineProperty(window,'devicePixelRatio',{value:3,configurable:true});}); afterEach(()=>jest.useRealTimers());
 test('mount creates canvas, controls, resize caps DPI, frames, context menu, and dispose removes listeners',async()=>{const r=new ThreeDungeonRenderer(); const c=document.createElement('main'); Object.defineProperty(c,'clientWidth',{value:320}); Object.defineProperty(c,'clientHeight',{value:200}); await r.mount(c); expect(c.querySelector('canvas')).toBeTruthy(); const canvas=c.querySelector('canvas')!; canvas.dispatchEvent(Object.assign(new MouseEvent('pointerdown',{clientX:1,clientY:2}),{pointerId:1})); canvas.dispatchEvent(Object.assign(new MouseEvent('pointermove',{clientX:3,clientY:4}),{pointerId:1})); canvas.dispatchEvent(new MouseEvent('pointerup')); const wheel=new WheelEvent('wheel',{deltaY:1,cancelable:true}); canvas.dispatchEvent(wheel); expect(wheel.defaultPrevented).toBe(true); await r.render(input as any,{...DEFAULT_RENDERER_OPTIONS,quality:'high',animateBuild:true,reducedMotion:false,animationSpeed:.5}); jest.runOnlyPendingTimers(); r.setOverlayState({preset:'none',enabled:{doorways:false,corridor_centerlines:false}}); r.resize(10,5,10); expect(r.getStats()).toMatchObject({drawCalls:7,triangles:11}); r.dispose(); expect(c.childElementCount).toBe(0);});
 test('empty scenes, stale construction loads, presentation defaults, and duplicate disposal are stable',async()=>{const r=new ThreeDungeonRenderer(); await r.render({...input,geometry:{...input.geometry,corridors:[],doorways:[],boundaries:[],tileLayers:{width:1,height:1,layers:[]}},construction:{...input.construction,records:[{id:'late',requestedAssetFamily:'asset',transform:{position:{x:0,y:0}},source:{}}]}} as any,{...DEFAULT_RENDERER_OPTIONS,quality:'medium',animateBuild:false}); r.updatePresentation({wallFading:true}); r.disposeDungeon(); r.dispose(); r.dispose(); expect(r.getStats().objects).toBe(0);});
});
